/*
 * Portfolio Management API
 * API documentation for the Asset Management Portfolio application
 *
 * The version of the OpenAPI document: v1.0
 * Contact: portfolio-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.am.portfolio.client.model.CoreIdentifiers;
import com.am.portfolio.client.model.FeatureConfiguration;
import com.am.portfolio.client.model.FeatureToggles;
import com.am.portfolio.client.model.PaginationRequest;
import com.am.portfolio.client.model.TimeFrameRequest;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.portfolio.client.invoker.ApiClient;
/**
 * AdvancedAnalyticsRequest
 */
@JsonPropertyOrder({
  AdvancedAnalyticsRequest.JSON_PROPERTY_FROM_DATE,
  AdvancedAnalyticsRequest.JSON_PROPERTY_TO_DATE,
  AdvancedAnalyticsRequest.JSON_PROPERTY_TIME_FRAME,
  AdvancedAnalyticsRequest.JSON_PROPERTY_CORE_IDENTIFIERS,
  AdvancedAnalyticsRequest.JSON_PROPERTY_PAGINATION,
  AdvancedAnalyticsRequest.JSON_PROPERTY_FEATURE_TOGGLES,
  AdvancedAnalyticsRequest.JSON_PROPERTY_FEATURE_CONFIGURATION,
  AdvancedAnalyticsRequest.JSON_PROPERTY_TIME_FRAME_REQUEST
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-26T23:23:15.876134200+05:30[Asia/Calcutta]", comments = "Generator version: 7.20.0")
public class AdvancedAnalyticsRequest {
  public static final String JSON_PROPERTY_FROM_DATE = "fromDate";
  @javax.annotation.Nullable
  private LocalDate fromDate;

  public static final String JSON_PROPERTY_TO_DATE = "toDate";
  @javax.annotation.Nullable
  private LocalDate toDate;

  /**
   * Gets or Sets timeFrame
   */
  public enum TimeFrameEnum {
    _1M(String.valueOf("1m")),
    
    _3M(String.valueOf("3m")),
    
    _5M(String.valueOf("5m")),
    
    _10M(String.valueOf("10m")),
    
    _15M(String.valueOf("15m")),
    
    _30M(String.valueOf("30m")),
    
    _1_H(String.valueOf("1H")),
    
    _4_H(String.valueOf("4H")),
    
    _1_D(String.valueOf("1D")),
    
    _1_W(String.valueOf("1W")),
    
    _1_M(String.valueOf("1M")),
    
    _1_Y(String.valueOf("1Y"));

    private String value;

    TimeFrameEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TimeFrameEnum fromValue(String value) {
      for (TimeFrameEnum b : TimeFrameEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TIME_FRAME = "timeFrame";
  @javax.annotation.Nullable
  private TimeFrameEnum timeFrame;

  public static final String JSON_PROPERTY_CORE_IDENTIFIERS = "coreIdentifiers";
  @javax.annotation.Nullable
  private CoreIdentifiers coreIdentifiers;

  public static final String JSON_PROPERTY_PAGINATION = "pagination";
  @javax.annotation.Nullable
  private PaginationRequest pagination;

  public static final String JSON_PROPERTY_FEATURE_TOGGLES = "featureToggles";
  @javax.annotation.Nullable
  private FeatureToggles featureToggles;

  public static final String JSON_PROPERTY_FEATURE_CONFIGURATION = "featureConfiguration";
  @javax.annotation.Nullable
  private FeatureConfiguration featureConfiguration;

  public static final String JSON_PROPERTY_TIME_FRAME_REQUEST = "timeFrameRequest";
  @javax.annotation.Nullable
  private TimeFrameRequest timeFrameRequest;

  public AdvancedAnalyticsRequest() { 
  }

  public AdvancedAnalyticsRequest fromDate(@javax.annotation.Nullable LocalDate fromDate) {
    this.fromDate = fromDate;
    return this;
  }

  /**
   * Get fromDate
   * @return fromDate
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FROM_DATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public LocalDate getFromDate() {
    return fromDate;
  }


  @JsonProperty(value = JSON_PROPERTY_FROM_DATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFromDate(@javax.annotation.Nullable LocalDate fromDate) {
    this.fromDate = fromDate;
  }


  public AdvancedAnalyticsRequest toDate(@javax.annotation.Nullable LocalDate toDate) {
    this.toDate = toDate;
    return this;
  }

  /**
   * Get toDate
   * @return toDate
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TO_DATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public LocalDate getToDate() {
    return toDate;
  }


  @JsonProperty(value = JSON_PROPERTY_TO_DATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setToDate(@javax.annotation.Nullable LocalDate toDate) {
    this.toDate = toDate;
  }


  public AdvancedAnalyticsRequest timeFrame(@javax.annotation.Nullable TimeFrameEnum timeFrame) {
    this.timeFrame = timeFrame;
    return this;
  }

  /**
   * Get timeFrame
   * @return timeFrame
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIME_FRAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public TimeFrameEnum getTimeFrame() {
    return timeFrame;
  }


  @JsonProperty(value = JSON_PROPERTY_TIME_FRAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimeFrame(@javax.annotation.Nullable TimeFrameEnum timeFrame) {
    this.timeFrame = timeFrame;
  }


  public AdvancedAnalyticsRequest coreIdentifiers(@javax.annotation.Nullable CoreIdentifiers coreIdentifiers) {
    this.coreIdentifiers = coreIdentifiers;
    return this;
  }

  /**
   * Get coreIdentifiers
   * @return coreIdentifiers
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CORE_IDENTIFIERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CoreIdentifiers getCoreIdentifiers() {
    return coreIdentifiers;
  }


  @JsonProperty(value = JSON_PROPERTY_CORE_IDENTIFIERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCoreIdentifiers(@javax.annotation.Nullable CoreIdentifiers coreIdentifiers) {
    this.coreIdentifiers = coreIdentifiers;
  }


  public AdvancedAnalyticsRequest pagination(@javax.annotation.Nullable PaginationRequest pagination) {
    this.pagination = pagination;
    return this;
  }

  /**
   * Get pagination
   * @return pagination
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PAGINATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public PaginationRequest getPagination() {
    return pagination;
  }


  @JsonProperty(value = JSON_PROPERTY_PAGINATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPagination(@javax.annotation.Nullable PaginationRequest pagination) {
    this.pagination = pagination;
  }


  public AdvancedAnalyticsRequest featureToggles(@javax.annotation.Nullable FeatureToggles featureToggles) {
    this.featureToggles = featureToggles;
    return this;
  }

  /**
   * Get featureToggles
   * @return featureToggles
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FEATURE_TOGGLES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public FeatureToggles getFeatureToggles() {
    return featureToggles;
  }


  @JsonProperty(value = JSON_PROPERTY_FEATURE_TOGGLES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFeatureToggles(@javax.annotation.Nullable FeatureToggles featureToggles) {
    this.featureToggles = featureToggles;
  }


  public AdvancedAnalyticsRequest featureConfiguration(@javax.annotation.Nullable FeatureConfiguration featureConfiguration) {
    this.featureConfiguration = featureConfiguration;
    return this;
  }

  /**
   * Get featureConfiguration
   * @return featureConfiguration
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FEATURE_CONFIGURATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public FeatureConfiguration getFeatureConfiguration() {
    return featureConfiguration;
  }


  @JsonProperty(value = JSON_PROPERTY_FEATURE_CONFIGURATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFeatureConfiguration(@javax.annotation.Nullable FeatureConfiguration featureConfiguration) {
    this.featureConfiguration = featureConfiguration;
  }


  public AdvancedAnalyticsRequest timeFrameRequest(@javax.annotation.Nullable TimeFrameRequest timeFrameRequest) {
    this.timeFrameRequest = timeFrameRequest;
    return this;
  }

  /**
   * Get timeFrameRequest
   * @return timeFrameRequest
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIME_FRAME_REQUEST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public TimeFrameRequest getTimeFrameRequest() {
    return timeFrameRequest;
  }


  @JsonProperty(value = JSON_PROPERTY_TIME_FRAME_REQUEST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimeFrameRequest(@javax.annotation.Nullable TimeFrameRequest timeFrameRequest) {
    this.timeFrameRequest = timeFrameRequest;
  }


  /**
   * Return true if this AdvancedAnalyticsRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdvancedAnalyticsRequest advancedAnalyticsRequest = (AdvancedAnalyticsRequest) o;
    return Objects.equals(this.fromDate, advancedAnalyticsRequest.fromDate) &&
        Objects.equals(this.toDate, advancedAnalyticsRequest.toDate) &&
        Objects.equals(this.timeFrame, advancedAnalyticsRequest.timeFrame) &&
        Objects.equals(this.coreIdentifiers, advancedAnalyticsRequest.coreIdentifiers) &&
        Objects.equals(this.pagination, advancedAnalyticsRequest.pagination) &&
        Objects.equals(this.featureToggles, advancedAnalyticsRequest.featureToggles) &&
        Objects.equals(this.featureConfiguration, advancedAnalyticsRequest.featureConfiguration) &&
        Objects.equals(this.timeFrameRequest, advancedAnalyticsRequest.timeFrameRequest);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fromDate, toDate, timeFrame, coreIdentifiers, pagination, featureToggles, featureConfiguration, timeFrameRequest);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdvancedAnalyticsRequest {\n");
    sb.append("    fromDate: ").append(toIndentedString(fromDate)).append("\n");
    sb.append("    toDate: ").append(toIndentedString(toDate)).append("\n");
    sb.append("    timeFrame: ").append(toIndentedString(timeFrame)).append("\n");
    sb.append("    coreIdentifiers: ").append(toIndentedString(coreIdentifiers)).append("\n");
    sb.append("    pagination: ").append(toIndentedString(pagination)).append("\n");
    sb.append("    featureToggles: ").append(toIndentedString(featureToggles)).append("\n");
    sb.append("    featureConfiguration: ").append(toIndentedString(featureConfiguration)).append("\n");
    sb.append("    timeFrameRequest: ").append(toIndentedString(timeFrameRequest)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `fromDate` to the URL query string
    if (getFromDate() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfromDate%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFromDate()))));
    }

    // add `toDate` to the URL query string
    if (getToDate() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stoDate%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getToDate()))));
    }

    // add `timeFrame` to the URL query string
    if (getTimeFrame() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stimeFrame%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTimeFrame()))));
    }

    // add `coreIdentifiers` to the URL query string
    if (getCoreIdentifiers() != null) {
      joiner.add(getCoreIdentifiers().toUrlQueryString(prefix + "coreIdentifiers" + suffix));
    }

    // add `pagination` to the URL query string
    if (getPagination() != null) {
      joiner.add(getPagination().toUrlQueryString(prefix + "pagination" + suffix));
    }

    // add `featureToggles` to the URL query string
    if (getFeatureToggles() != null) {
      joiner.add(getFeatureToggles().toUrlQueryString(prefix + "featureToggles" + suffix));
    }

    // add `featureConfiguration` to the URL query string
    if (getFeatureConfiguration() != null) {
      joiner.add(getFeatureConfiguration().toUrlQueryString(prefix + "featureConfiguration" + suffix));
    }

    // add `timeFrameRequest` to the URL query string
    if (getTimeFrameRequest() != null) {
      joiner.add(getTimeFrameRequest().toUrlQueryString(prefix + "timeFrameRequest" + suffix));
    }

    return joiner.toString();
  }
}

