/*
 * Portfolio Management API
 * API documentation for the Asset Management Portfolio application
 *
 * The version of the OpenAPI document: v1.0
 * Contact: portfolio-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.portfolio.client.invoker.ApiClient;
/**
 * BrokerPortfolioSummary
 */
@JsonPropertyOrder({
  BrokerPortfolioSummary.JSON_PROPERTY_INVESTMENT_VALUE,
  BrokerPortfolioSummary.JSON_PROPERTY_CURRENT_VALUE,
  BrokerPortfolioSummary.JSON_PROPERTY_TOTAL_GAIN_LOSS,
  BrokerPortfolioSummary.JSON_PROPERTY_TOTAL_GAIN_LOSS_PERCENTAGE,
  BrokerPortfolioSummary.JSON_PROPERTY_TODAY_GAIN_LOSS,
  BrokerPortfolioSummary.JSON_PROPERTY_TODAY_GAIN_LOSS_PERCENTAGE,
  BrokerPortfolioSummary.JSON_PROPERTY_TOTAL_ASSETS,
  BrokerPortfolioSummary.JSON_PROPERTY_GAINERS_COUNT,
  BrokerPortfolioSummary.JSON_PROPERTY_LOSERS_COUNT,
  BrokerPortfolioSummary.JSON_PROPERTY_TODAY_GAINERS_COUNT,
  BrokerPortfolioSummary.JSON_PROPERTY_TODAY_LOSERS_COUNT,
  BrokerPortfolioSummary.JSON_PROPERTY_LAST_UPDATED,
  BrokerPortfolioSummary.JSON_PROPERTY_BROKER_TYPE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-26T23:23:15.876134200+05:30[Asia/Calcutta]", comments = "Generator version: 7.20.0")
public class BrokerPortfolioSummary {
  public static final String JSON_PROPERTY_INVESTMENT_VALUE = "investmentValue";
  @javax.annotation.Nullable
  private Double investmentValue;

  public static final String JSON_PROPERTY_CURRENT_VALUE = "currentValue";
  @javax.annotation.Nullable
  private Double currentValue;

  public static final String JSON_PROPERTY_TOTAL_GAIN_LOSS = "totalGainLoss";
  @javax.annotation.Nullable
  private Double totalGainLoss;

  public static final String JSON_PROPERTY_TOTAL_GAIN_LOSS_PERCENTAGE = "totalGainLossPercentage";
  @javax.annotation.Nullable
  private Double totalGainLossPercentage;

  public static final String JSON_PROPERTY_TODAY_GAIN_LOSS = "todayGainLoss";
  @javax.annotation.Nullable
  private Double todayGainLoss;

  public static final String JSON_PROPERTY_TODAY_GAIN_LOSS_PERCENTAGE = "todayGainLossPercentage";
  @javax.annotation.Nullable
  private Double todayGainLossPercentage;

  public static final String JSON_PROPERTY_TOTAL_ASSETS = "totalAssets";
  @javax.annotation.Nullable
  private Integer totalAssets;

  public static final String JSON_PROPERTY_GAINERS_COUNT = "gainersCount";
  @javax.annotation.Nullable
  private Integer gainersCount;

  public static final String JSON_PROPERTY_LOSERS_COUNT = "losersCount";
  @javax.annotation.Nullable
  private Integer losersCount;

  public static final String JSON_PROPERTY_TODAY_GAINERS_COUNT = "todayGainersCount";
  @javax.annotation.Nullable
  private Integer todayGainersCount;

  public static final String JSON_PROPERTY_TODAY_LOSERS_COUNT = "todayLosersCount";
  @javax.annotation.Nullable
  private Integer todayLosersCount;

  public static final String JSON_PROPERTY_LAST_UPDATED = "lastUpdated";
  @javax.annotation.Nullable
  private OffsetDateTime lastUpdated;

  /**
   * Gets or Sets brokerType
   */
  public enum BrokerTypeEnum {
    DHAN(String.valueOf("DHAN")),
    
    ZERODHA(String.valueOf("ZERODHA")),
    
    MSTOCK(String.valueOf("MSTOCK")),
    
    GROW(String.valueOf("GROW")),
    
    KOTAK(String.valueOf("KOTAK"));

    private String value;

    BrokerTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static BrokerTypeEnum fromValue(String value) {
      for (BrokerTypeEnum b : BrokerTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_BROKER_TYPE = "brokerType";
  @javax.annotation.Nullable
  private BrokerTypeEnum brokerType;

  public BrokerPortfolioSummary() { 
  }

  public BrokerPortfolioSummary investmentValue(@javax.annotation.Nullable Double investmentValue) {
    this.investmentValue = investmentValue;
    return this;
  }

  /**
   * Get investmentValue
   * @return investmentValue
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INVESTMENT_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getInvestmentValue() {
    return investmentValue;
  }


  @JsonProperty(value = JSON_PROPERTY_INVESTMENT_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInvestmentValue(@javax.annotation.Nullable Double investmentValue) {
    this.investmentValue = investmentValue;
  }


  public BrokerPortfolioSummary currentValue(@javax.annotation.Nullable Double currentValue) {
    this.currentValue = currentValue;
    return this;
  }

  /**
   * Get currentValue
   * @return currentValue
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CURRENT_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getCurrentValue() {
    return currentValue;
  }


  @JsonProperty(value = JSON_PROPERTY_CURRENT_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCurrentValue(@javax.annotation.Nullable Double currentValue) {
    this.currentValue = currentValue;
  }


  public BrokerPortfolioSummary totalGainLoss(@javax.annotation.Nullable Double totalGainLoss) {
    this.totalGainLoss = totalGainLoss;
    return this;
  }

  /**
   * Get totalGainLoss
   * @return totalGainLoss
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOTAL_GAIN_LOSS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getTotalGainLoss() {
    return totalGainLoss;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL_GAIN_LOSS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalGainLoss(@javax.annotation.Nullable Double totalGainLoss) {
    this.totalGainLoss = totalGainLoss;
  }


  public BrokerPortfolioSummary totalGainLossPercentage(@javax.annotation.Nullable Double totalGainLossPercentage) {
    this.totalGainLossPercentage = totalGainLossPercentage;
    return this;
  }

  /**
   * Get totalGainLossPercentage
   * @return totalGainLossPercentage
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOTAL_GAIN_LOSS_PERCENTAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getTotalGainLossPercentage() {
    return totalGainLossPercentage;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL_GAIN_LOSS_PERCENTAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalGainLossPercentage(@javax.annotation.Nullable Double totalGainLossPercentage) {
    this.totalGainLossPercentage = totalGainLossPercentage;
  }


  public BrokerPortfolioSummary todayGainLoss(@javax.annotation.Nullable Double todayGainLoss) {
    this.todayGainLoss = todayGainLoss;
    return this;
  }

  /**
   * Get todayGainLoss
   * @return todayGainLoss
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TODAY_GAIN_LOSS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getTodayGainLoss() {
    return todayGainLoss;
  }


  @JsonProperty(value = JSON_PROPERTY_TODAY_GAIN_LOSS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTodayGainLoss(@javax.annotation.Nullable Double todayGainLoss) {
    this.todayGainLoss = todayGainLoss;
  }


  public BrokerPortfolioSummary todayGainLossPercentage(@javax.annotation.Nullable Double todayGainLossPercentage) {
    this.todayGainLossPercentage = todayGainLossPercentage;
    return this;
  }

  /**
   * Get todayGainLossPercentage
   * @return todayGainLossPercentage
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TODAY_GAIN_LOSS_PERCENTAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getTodayGainLossPercentage() {
    return todayGainLossPercentage;
  }


  @JsonProperty(value = JSON_PROPERTY_TODAY_GAIN_LOSS_PERCENTAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTodayGainLossPercentage(@javax.annotation.Nullable Double todayGainLossPercentage) {
    this.todayGainLossPercentage = todayGainLossPercentage;
  }


  public BrokerPortfolioSummary totalAssets(@javax.annotation.Nullable Integer totalAssets) {
    this.totalAssets = totalAssets;
    return this;
  }

  /**
   * Get totalAssets
   * @return totalAssets
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOTAL_ASSETS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getTotalAssets() {
    return totalAssets;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL_ASSETS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalAssets(@javax.annotation.Nullable Integer totalAssets) {
    this.totalAssets = totalAssets;
  }


  public BrokerPortfolioSummary gainersCount(@javax.annotation.Nullable Integer gainersCount) {
    this.gainersCount = gainersCount;
    return this;
  }

  /**
   * Get gainersCount
   * @return gainersCount
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_GAINERS_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getGainersCount() {
    return gainersCount;
  }


  @JsonProperty(value = JSON_PROPERTY_GAINERS_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGainersCount(@javax.annotation.Nullable Integer gainersCount) {
    this.gainersCount = gainersCount;
  }


  public BrokerPortfolioSummary losersCount(@javax.annotation.Nullable Integer losersCount) {
    this.losersCount = losersCount;
    return this;
  }

  /**
   * Get losersCount
   * @return losersCount
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LOSERS_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getLosersCount() {
    return losersCount;
  }


  @JsonProperty(value = JSON_PROPERTY_LOSERS_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLosersCount(@javax.annotation.Nullable Integer losersCount) {
    this.losersCount = losersCount;
  }


  public BrokerPortfolioSummary todayGainersCount(@javax.annotation.Nullable Integer todayGainersCount) {
    this.todayGainersCount = todayGainersCount;
    return this;
  }

  /**
   * Get todayGainersCount
   * @return todayGainersCount
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TODAY_GAINERS_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getTodayGainersCount() {
    return todayGainersCount;
  }


  @JsonProperty(value = JSON_PROPERTY_TODAY_GAINERS_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTodayGainersCount(@javax.annotation.Nullable Integer todayGainersCount) {
    this.todayGainersCount = todayGainersCount;
  }


  public BrokerPortfolioSummary todayLosersCount(@javax.annotation.Nullable Integer todayLosersCount) {
    this.todayLosersCount = todayLosersCount;
    return this;
  }

  /**
   * Get todayLosersCount
   * @return todayLosersCount
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TODAY_LOSERS_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getTodayLosersCount() {
    return todayLosersCount;
  }


  @JsonProperty(value = JSON_PROPERTY_TODAY_LOSERS_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTodayLosersCount(@javax.annotation.Nullable Integer todayLosersCount) {
    this.todayLosersCount = todayLosersCount;
  }


  public BrokerPortfolioSummary lastUpdated(@javax.annotation.Nullable OffsetDateTime lastUpdated) {
    this.lastUpdated = lastUpdated;
    return this;
  }

  /**
   * Get lastUpdated
   * @return lastUpdated
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LAST_UPDATED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getLastUpdated() {
    return lastUpdated;
  }


  @JsonProperty(value = JSON_PROPERTY_LAST_UPDATED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastUpdated(@javax.annotation.Nullable OffsetDateTime lastUpdated) {
    this.lastUpdated = lastUpdated;
  }


  public BrokerPortfolioSummary brokerType(@javax.annotation.Nullable BrokerTypeEnum brokerType) {
    this.brokerType = brokerType;
    return this;
  }

  /**
   * Get brokerType
   * @return brokerType
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BROKER_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BrokerTypeEnum getBrokerType() {
    return brokerType;
  }


  @JsonProperty(value = JSON_PROPERTY_BROKER_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBrokerType(@javax.annotation.Nullable BrokerTypeEnum brokerType) {
    this.brokerType = brokerType;
  }


  /**
   * Return true if this BrokerPortfolioSummary object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BrokerPortfolioSummary brokerPortfolioSummary = (BrokerPortfolioSummary) o;
    return Objects.equals(this.investmentValue, brokerPortfolioSummary.investmentValue) &&
        Objects.equals(this.currentValue, brokerPortfolioSummary.currentValue) &&
        Objects.equals(this.totalGainLoss, brokerPortfolioSummary.totalGainLoss) &&
        Objects.equals(this.totalGainLossPercentage, brokerPortfolioSummary.totalGainLossPercentage) &&
        Objects.equals(this.todayGainLoss, brokerPortfolioSummary.todayGainLoss) &&
        Objects.equals(this.todayGainLossPercentage, brokerPortfolioSummary.todayGainLossPercentage) &&
        Objects.equals(this.totalAssets, brokerPortfolioSummary.totalAssets) &&
        Objects.equals(this.gainersCount, brokerPortfolioSummary.gainersCount) &&
        Objects.equals(this.losersCount, brokerPortfolioSummary.losersCount) &&
        Objects.equals(this.todayGainersCount, brokerPortfolioSummary.todayGainersCount) &&
        Objects.equals(this.todayLosersCount, brokerPortfolioSummary.todayLosersCount) &&
        Objects.equals(this.lastUpdated, brokerPortfolioSummary.lastUpdated) &&
        Objects.equals(this.brokerType, brokerPortfolioSummary.brokerType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(investmentValue, currentValue, totalGainLoss, totalGainLossPercentage, todayGainLoss, todayGainLossPercentage, totalAssets, gainersCount, losersCount, todayGainersCount, todayLosersCount, lastUpdated, brokerType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BrokerPortfolioSummary {\n");
    sb.append("    investmentValue: ").append(toIndentedString(investmentValue)).append("\n");
    sb.append("    currentValue: ").append(toIndentedString(currentValue)).append("\n");
    sb.append("    totalGainLoss: ").append(toIndentedString(totalGainLoss)).append("\n");
    sb.append("    totalGainLossPercentage: ").append(toIndentedString(totalGainLossPercentage)).append("\n");
    sb.append("    todayGainLoss: ").append(toIndentedString(todayGainLoss)).append("\n");
    sb.append("    todayGainLossPercentage: ").append(toIndentedString(todayGainLossPercentage)).append("\n");
    sb.append("    totalAssets: ").append(toIndentedString(totalAssets)).append("\n");
    sb.append("    gainersCount: ").append(toIndentedString(gainersCount)).append("\n");
    sb.append("    losersCount: ").append(toIndentedString(losersCount)).append("\n");
    sb.append("    todayGainersCount: ").append(toIndentedString(todayGainersCount)).append("\n");
    sb.append("    todayLosersCount: ").append(toIndentedString(todayLosersCount)).append("\n");
    sb.append("    lastUpdated: ").append(toIndentedString(lastUpdated)).append("\n");
    sb.append("    brokerType: ").append(toIndentedString(brokerType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `investmentValue` to the URL query string
    if (getInvestmentValue() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sinvestmentValue%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getInvestmentValue()))));
    }

    // add `currentValue` to the URL query string
    if (getCurrentValue() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scurrentValue%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCurrentValue()))));
    }

    // add `totalGainLoss` to the URL query string
    if (getTotalGainLoss() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stotalGainLoss%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTotalGainLoss()))));
    }

    // add `totalGainLossPercentage` to the URL query string
    if (getTotalGainLossPercentage() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stotalGainLossPercentage%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTotalGainLossPercentage()))));
    }

    // add `todayGainLoss` to the URL query string
    if (getTodayGainLoss() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stodayGainLoss%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTodayGainLoss()))));
    }

    // add `todayGainLossPercentage` to the URL query string
    if (getTodayGainLossPercentage() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stodayGainLossPercentage%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTodayGainLossPercentage()))));
    }

    // add `totalAssets` to the URL query string
    if (getTotalAssets() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stotalAssets%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTotalAssets()))));
    }

    // add `gainersCount` to the URL query string
    if (getGainersCount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sgainersCount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getGainersCount()))));
    }

    // add `losersCount` to the URL query string
    if (getLosersCount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slosersCount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLosersCount()))));
    }

    // add `todayGainersCount` to the URL query string
    if (getTodayGainersCount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stodayGainersCount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTodayGainersCount()))));
    }

    // add `todayLosersCount` to the URL query string
    if (getTodayLosersCount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stodayLosersCount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTodayLosersCount()))));
    }

    // add `lastUpdated` to the URL query string
    if (getLastUpdated() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slastUpdated%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLastUpdated()))));
    }

    // add `brokerType` to the URL query string
    if (getBrokerType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbrokerType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBrokerType()))));
    }

    return joiner.toString();
  }
}

