/*
 * Portfolio Management API
 * API documentation for the Asset Management Portfolio application
 *
 * The version of the OpenAPI document: v1.0
 * Contact: portfolio-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.portfolio.client.invoker.ApiClient;
/**
 * CapSegment
 */
@JsonPropertyOrder({
  CapSegment.JSON_PROPERTY_SEGMENT_NAME,
  CapSegment.JSON_PROPERTY_WEIGHT_PERCENTAGE,
  CapSegment.JSON_PROPERTY_SEGMENT_VALUE,
  CapSegment.JSON_PROPERTY_NUMBER_OF_STOCKS,
  CapSegment.JSON_PROPERTY_TOP_STOCKS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-26T23:23:15.876134200+05:30[Asia/Calcutta]", comments = "Generator version: 7.20.0")
public class CapSegment {
  public static final String JSON_PROPERTY_SEGMENT_NAME = "segmentName";
  @javax.annotation.Nullable
  private String segmentName;

  public static final String JSON_PROPERTY_WEIGHT_PERCENTAGE = "weightPercentage";
  @javax.annotation.Nullable
  private Double weightPercentage;

  public static final String JSON_PROPERTY_SEGMENT_VALUE = "segmentValue";
  @javax.annotation.Nullable
  private Double segmentValue;

  public static final String JSON_PROPERTY_NUMBER_OF_STOCKS = "numberOfStocks";
  @javax.annotation.Nullable
  private Integer numberOfStocks;

  public static final String JSON_PROPERTY_TOP_STOCKS = "topStocks";
  @javax.annotation.Nullable
  private List<String> topStocks = new ArrayList<>();

  public CapSegment() { 
  }

  public CapSegment segmentName(@javax.annotation.Nullable String segmentName) {
    this.segmentName = segmentName;
    return this;
  }

  /**
   * Get segmentName
   * @return segmentName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SEGMENT_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSegmentName() {
    return segmentName;
  }


  @JsonProperty(value = JSON_PROPERTY_SEGMENT_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSegmentName(@javax.annotation.Nullable String segmentName) {
    this.segmentName = segmentName;
  }


  public CapSegment weightPercentage(@javax.annotation.Nullable Double weightPercentage) {
    this.weightPercentage = weightPercentage;
    return this;
  }

  /**
   * Get weightPercentage
   * @return weightPercentage
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WEIGHT_PERCENTAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getWeightPercentage() {
    return weightPercentage;
  }


  @JsonProperty(value = JSON_PROPERTY_WEIGHT_PERCENTAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWeightPercentage(@javax.annotation.Nullable Double weightPercentage) {
    this.weightPercentage = weightPercentage;
  }


  public CapSegment segmentValue(@javax.annotation.Nullable Double segmentValue) {
    this.segmentValue = segmentValue;
    return this;
  }

  /**
   * Get segmentValue
   * @return segmentValue
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SEGMENT_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getSegmentValue() {
    return segmentValue;
  }


  @JsonProperty(value = JSON_PROPERTY_SEGMENT_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSegmentValue(@javax.annotation.Nullable Double segmentValue) {
    this.segmentValue = segmentValue;
  }


  public CapSegment numberOfStocks(@javax.annotation.Nullable Integer numberOfStocks) {
    this.numberOfStocks = numberOfStocks;
    return this;
  }

  /**
   * Get numberOfStocks
   * @return numberOfStocks
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NUMBER_OF_STOCKS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getNumberOfStocks() {
    return numberOfStocks;
  }


  @JsonProperty(value = JSON_PROPERTY_NUMBER_OF_STOCKS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNumberOfStocks(@javax.annotation.Nullable Integer numberOfStocks) {
    this.numberOfStocks = numberOfStocks;
  }


  public CapSegment topStocks(@javax.annotation.Nullable List<String> topStocks) {
    this.topStocks = topStocks;
    return this;
  }

  public CapSegment addTopStocksItem(String topStocksItem) {
    if (this.topStocks == null) {
      this.topStocks = new ArrayList<>();
    }
    this.topStocks.add(topStocksItem);
    return this;
  }

  /**
   * Get topStocks
   * @return topStocks
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOP_STOCKS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getTopStocks() {
    return topStocks;
  }


  @JsonProperty(value = JSON_PROPERTY_TOP_STOCKS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTopStocks(@javax.annotation.Nullable List<String> topStocks) {
    this.topStocks = topStocks;
  }


  /**
   * Return true if this CapSegment object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CapSegment capSegment = (CapSegment) o;
    return Objects.equals(this.segmentName, capSegment.segmentName) &&
        Objects.equals(this.weightPercentage, capSegment.weightPercentage) &&
        Objects.equals(this.segmentValue, capSegment.segmentValue) &&
        Objects.equals(this.numberOfStocks, capSegment.numberOfStocks) &&
        Objects.equals(this.topStocks, capSegment.topStocks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(segmentName, weightPercentage, segmentValue, numberOfStocks, topStocks);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CapSegment {\n");
    sb.append("    segmentName: ").append(toIndentedString(segmentName)).append("\n");
    sb.append("    weightPercentage: ").append(toIndentedString(weightPercentage)).append("\n");
    sb.append("    segmentValue: ").append(toIndentedString(segmentValue)).append("\n");
    sb.append("    numberOfStocks: ").append(toIndentedString(numberOfStocks)).append("\n");
    sb.append("    topStocks: ").append(toIndentedString(topStocks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `segmentName` to the URL query string
    if (getSegmentName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssegmentName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSegmentName()))));
    }

    // add `weightPercentage` to the URL query string
    if (getWeightPercentage() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sweightPercentage%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getWeightPercentage()))));
    }

    // add `segmentValue` to the URL query string
    if (getSegmentValue() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssegmentValue%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSegmentValue()))));
    }

    // add `numberOfStocks` to the URL query string
    if (getNumberOfStocks() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%snumberOfStocks%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getNumberOfStocks()))));
    }

    // add `topStocks` to the URL query string
    if (getTopStocks() != null) {
      for (int i = 0; i < getTopStocks().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%stopStocks%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getTopStocks().get(i)))));
      }
    }

    return joiner.toString();
  }
}

