/*
 * Portfolio Management API
 * API documentation for the Asset Management Portfolio application
 *
 * The version of the OpenAPI document: v1.0
 * Contact: portfolio-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.am.portfolio.client.model.SectorMovement;
import com.am.portfolio.client.model.StockMovement;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.portfolio.client.invoker.ApiClient;
/**
 * GainerLoser
 */
@JsonPropertyOrder({
  GainerLoser.JSON_PROPERTY_TOP_GAINERS,
  GainerLoser.JSON_PROPERTY_TOP_LOSERS,
  GainerLoser.JSON_PROPERTY_SECTOR_MOVEMENTS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-26T23:23:15.876134200+05:30[Asia/Calcutta]", comments = "Generator version: 7.20.0")
public class GainerLoser {
  public static final String JSON_PROPERTY_TOP_GAINERS = "topGainers";
  @javax.annotation.Nullable
  private List<StockMovement> topGainers = new ArrayList<>();

  public static final String JSON_PROPERTY_TOP_LOSERS = "topLosers";
  @javax.annotation.Nullable
  private List<StockMovement> topLosers = new ArrayList<>();

  public static final String JSON_PROPERTY_SECTOR_MOVEMENTS = "sectorMovements";
  @javax.annotation.Nullable
  private List<SectorMovement> sectorMovements = new ArrayList<>();

  public GainerLoser() { 
  }

  public GainerLoser topGainers(@javax.annotation.Nullable List<StockMovement> topGainers) {
    this.topGainers = topGainers;
    return this;
  }

  public GainerLoser addTopGainersItem(StockMovement topGainersItem) {
    if (this.topGainers == null) {
      this.topGainers = new ArrayList<>();
    }
    this.topGainers.add(topGainersItem);
    return this;
  }

  /**
   * Get topGainers
   * @return topGainers
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOP_GAINERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<StockMovement> getTopGainers() {
    return topGainers;
  }


  @JsonProperty(value = JSON_PROPERTY_TOP_GAINERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTopGainers(@javax.annotation.Nullable List<StockMovement> topGainers) {
    this.topGainers = topGainers;
  }


  public GainerLoser topLosers(@javax.annotation.Nullable List<StockMovement> topLosers) {
    this.topLosers = topLosers;
    return this;
  }

  public GainerLoser addTopLosersItem(StockMovement topLosersItem) {
    if (this.topLosers == null) {
      this.topLosers = new ArrayList<>();
    }
    this.topLosers.add(topLosersItem);
    return this;
  }

  /**
   * Get topLosers
   * @return topLosers
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOP_LOSERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<StockMovement> getTopLosers() {
    return topLosers;
  }


  @JsonProperty(value = JSON_PROPERTY_TOP_LOSERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTopLosers(@javax.annotation.Nullable List<StockMovement> topLosers) {
    this.topLosers = topLosers;
  }


  public GainerLoser sectorMovements(@javax.annotation.Nullable List<SectorMovement> sectorMovements) {
    this.sectorMovements = sectorMovements;
    return this;
  }

  public GainerLoser addSectorMovementsItem(SectorMovement sectorMovementsItem) {
    if (this.sectorMovements == null) {
      this.sectorMovements = new ArrayList<>();
    }
    this.sectorMovements.add(sectorMovementsItem);
    return this;
  }

  /**
   * Get sectorMovements
   * @return sectorMovements
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SECTOR_MOVEMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<SectorMovement> getSectorMovements() {
    return sectorMovements;
  }


  @JsonProperty(value = JSON_PROPERTY_SECTOR_MOVEMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSectorMovements(@javax.annotation.Nullable List<SectorMovement> sectorMovements) {
    this.sectorMovements = sectorMovements;
  }


  /**
   * Return true if this GainerLoser object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GainerLoser gainerLoser = (GainerLoser) o;
    return Objects.equals(this.topGainers, gainerLoser.topGainers) &&
        Objects.equals(this.topLosers, gainerLoser.topLosers) &&
        Objects.equals(this.sectorMovements, gainerLoser.sectorMovements);
  }

  @Override
  public int hashCode() {
    return Objects.hash(topGainers, topLosers, sectorMovements);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GainerLoser {\n");
    sb.append("    topGainers: ").append(toIndentedString(topGainers)).append("\n");
    sb.append("    topLosers: ").append(toIndentedString(topLosers)).append("\n");
    sb.append("    sectorMovements: ").append(toIndentedString(sectorMovements)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `topGainers` to the URL query string
    if (getTopGainers() != null) {
      for (int i = 0; i < getTopGainers().size(); i++) {
        if (getTopGainers().get(i) != null) {
          joiner.add(getTopGainers().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%stopGainers%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `topLosers` to the URL query string
    if (getTopLosers() != null) {
      for (int i = 0; i < getTopLosers().size(); i++) {
        if (getTopLosers().get(i) != null) {
          joiner.add(getTopLosers().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%stopLosers%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `sectorMovements` to the URL query string
    if (getSectorMovements() != null) {
      for (int i = 0; i < getSectorMovements().size(); i++) {
        if (getSectorMovements().get(i) != null) {
          joiner.add(getSectorMovements().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%ssectorMovements%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

