/*
 * Portfolio Management API
 * API documentation for the Asset Management Portfolio application
 *
 * The version of the OpenAPI document: v1.0
 * Contact: portfolio-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.am.portfolio.client.model.ChartPaths;
import com.am.portfolio.client.model.FundamentalRatios;
import com.am.portfolio.client.model.HistoricalComparison;
import com.am.portfolio.client.model.MarketBreadth;
import com.am.portfolio.client.model.MarketData;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.portfolio.client.invoker.ApiClient;
/**
 * MarketIndexIndices
 */
@JsonPropertyOrder({
  MarketIndexIndices.JSON_PROPERTY_KEY,
  MarketIndexIndices.JSON_PROPERTY_INDEX,
  MarketIndexIndices.JSON_PROPERTY_INDEX_SYMBOL,
  MarketIndexIndices.JSON_PROPERTY_MARKET_DATA,
  MarketIndexIndices.JSON_PROPERTY_FUNDAMENTAL_RATIOS,
  MarketIndexIndices.JSON_PROPERTY_MARKET_BREADTH,
  MarketIndexIndices.JSON_PROPERTY_HISTORICAL_COMPARISON,
  MarketIndexIndices.JSON_PROPERTY_CHART_PATHS,
  MarketIndexIndices.JSON_PROPERTY_TIMESTAMP
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-26T23:23:15.876134200+05:30[Asia/Calcutta]", comments = "Generator version: 7.20.0")
public class MarketIndexIndices {
  public static final String JSON_PROPERTY_KEY = "key";
  @javax.annotation.Nullable
  private String key;

  public static final String JSON_PROPERTY_INDEX = "index";
  @javax.annotation.Nullable
  private String index;

  public static final String JSON_PROPERTY_INDEX_SYMBOL = "indexSymbol";
  @javax.annotation.Nullable
  private String indexSymbol;

  public static final String JSON_PROPERTY_MARKET_DATA = "marketData";
  @javax.annotation.Nullable
  private MarketData marketData;

  public static final String JSON_PROPERTY_FUNDAMENTAL_RATIOS = "fundamentalRatios";
  @javax.annotation.Nullable
  private FundamentalRatios fundamentalRatios;

  public static final String JSON_PROPERTY_MARKET_BREADTH = "marketBreadth";
  @javax.annotation.Nullable
  private MarketBreadth marketBreadth;

  public static final String JSON_PROPERTY_HISTORICAL_COMPARISON = "historicalComparison";
  @javax.annotation.Nullable
  private HistoricalComparison historicalComparison;

  public static final String JSON_PROPERTY_CHART_PATHS = "chartPaths";
  @javax.annotation.Nullable
  private ChartPaths chartPaths;

  public static final String JSON_PROPERTY_TIMESTAMP = "timestamp";
  @javax.annotation.Nullable
  private OffsetDateTime timestamp;

  public MarketIndexIndices() { 
  }

  public MarketIndexIndices key(@javax.annotation.Nullable String key) {
    this.key = key;
    return this;
  }

  /**
   * Get key
   * @return key
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getKey() {
    return key;
  }


  @JsonProperty(value = JSON_PROPERTY_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKey(@javax.annotation.Nullable String key) {
    this.key = key;
  }


  public MarketIndexIndices index(@javax.annotation.Nullable String index) {
    this.index = index;
    return this;
  }

  /**
   * Get index
   * @return index
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INDEX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getIndex() {
    return index;
  }


  @JsonProperty(value = JSON_PROPERTY_INDEX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIndex(@javax.annotation.Nullable String index) {
    this.index = index;
  }


  public MarketIndexIndices indexSymbol(@javax.annotation.Nullable String indexSymbol) {
    this.indexSymbol = indexSymbol;
    return this;
  }

  /**
   * Get indexSymbol
   * @return indexSymbol
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INDEX_SYMBOL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getIndexSymbol() {
    return indexSymbol;
  }


  @JsonProperty(value = JSON_PROPERTY_INDEX_SYMBOL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIndexSymbol(@javax.annotation.Nullable String indexSymbol) {
    this.indexSymbol = indexSymbol;
  }


  public MarketIndexIndices marketData(@javax.annotation.Nullable MarketData marketData) {
    this.marketData = marketData;
    return this;
  }

  /**
   * Get marketData
   * @return marketData
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MARKET_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public MarketData getMarketData() {
    return marketData;
  }


  @JsonProperty(value = JSON_PROPERTY_MARKET_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMarketData(@javax.annotation.Nullable MarketData marketData) {
    this.marketData = marketData;
  }


  public MarketIndexIndices fundamentalRatios(@javax.annotation.Nullable FundamentalRatios fundamentalRatios) {
    this.fundamentalRatios = fundamentalRatios;
    return this;
  }

  /**
   * Get fundamentalRatios
   * @return fundamentalRatios
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FUNDAMENTAL_RATIOS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public FundamentalRatios getFundamentalRatios() {
    return fundamentalRatios;
  }


  @JsonProperty(value = JSON_PROPERTY_FUNDAMENTAL_RATIOS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFundamentalRatios(@javax.annotation.Nullable FundamentalRatios fundamentalRatios) {
    this.fundamentalRatios = fundamentalRatios;
  }


  public MarketIndexIndices marketBreadth(@javax.annotation.Nullable MarketBreadth marketBreadth) {
    this.marketBreadth = marketBreadth;
    return this;
  }

  /**
   * Get marketBreadth
   * @return marketBreadth
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MARKET_BREADTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public MarketBreadth getMarketBreadth() {
    return marketBreadth;
  }


  @JsonProperty(value = JSON_PROPERTY_MARKET_BREADTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMarketBreadth(@javax.annotation.Nullable MarketBreadth marketBreadth) {
    this.marketBreadth = marketBreadth;
  }


  public MarketIndexIndices historicalComparison(@javax.annotation.Nullable HistoricalComparison historicalComparison) {
    this.historicalComparison = historicalComparison;
    return this;
  }

  /**
   * Get historicalComparison
   * @return historicalComparison
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HISTORICAL_COMPARISON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public HistoricalComparison getHistoricalComparison() {
    return historicalComparison;
  }


  @JsonProperty(value = JSON_PROPERTY_HISTORICAL_COMPARISON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHistoricalComparison(@javax.annotation.Nullable HistoricalComparison historicalComparison) {
    this.historicalComparison = historicalComparison;
  }


  public MarketIndexIndices chartPaths(@javax.annotation.Nullable ChartPaths chartPaths) {
    this.chartPaths = chartPaths;
    return this;
  }

  /**
   * Get chartPaths
   * @return chartPaths
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CHART_PATHS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ChartPaths getChartPaths() {
    return chartPaths;
  }


  @JsonProperty(value = JSON_PROPERTY_CHART_PATHS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChartPaths(@javax.annotation.Nullable ChartPaths chartPaths) {
    this.chartPaths = chartPaths;
  }


  public MarketIndexIndices timestamp(@javax.annotation.Nullable OffsetDateTime timestamp) {
    this.timestamp = timestamp;
    return this;
  }

  /**
   * Get timestamp
   * @return timestamp
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getTimestamp() {
    return timestamp;
  }


  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimestamp(@javax.annotation.Nullable OffsetDateTime timestamp) {
    this.timestamp = timestamp;
  }


  /**
   * Return true if this MarketIndexIndices object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MarketIndexIndices marketIndexIndices = (MarketIndexIndices) o;
    return Objects.equals(this.key, marketIndexIndices.key) &&
        Objects.equals(this.index, marketIndexIndices.index) &&
        Objects.equals(this.indexSymbol, marketIndexIndices.indexSymbol) &&
        Objects.equals(this.marketData, marketIndexIndices.marketData) &&
        Objects.equals(this.fundamentalRatios, marketIndexIndices.fundamentalRatios) &&
        Objects.equals(this.marketBreadth, marketIndexIndices.marketBreadth) &&
        Objects.equals(this.historicalComparison, marketIndexIndices.historicalComparison) &&
        Objects.equals(this.chartPaths, marketIndexIndices.chartPaths) &&
        Objects.equals(this.timestamp, marketIndexIndices.timestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(key, index, indexSymbol, marketData, fundamentalRatios, marketBreadth, historicalComparison, chartPaths, timestamp);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MarketIndexIndices {\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("    indexSymbol: ").append(toIndentedString(indexSymbol)).append("\n");
    sb.append("    marketData: ").append(toIndentedString(marketData)).append("\n");
    sb.append("    fundamentalRatios: ").append(toIndentedString(fundamentalRatios)).append("\n");
    sb.append("    marketBreadth: ").append(toIndentedString(marketBreadth)).append("\n");
    sb.append("    historicalComparison: ").append(toIndentedString(historicalComparison)).append("\n");
    sb.append("    chartPaths: ").append(toIndentedString(chartPaths)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `key` to the URL query string
    if (getKey() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%skey%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getKey()))));
    }

    // add `index` to the URL query string
    if (getIndex() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sindex%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIndex()))));
    }

    // add `indexSymbol` to the URL query string
    if (getIndexSymbol() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sindexSymbol%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIndexSymbol()))));
    }

    // add `marketData` to the URL query string
    if (getMarketData() != null) {
      joiner.add(getMarketData().toUrlQueryString(prefix + "marketData" + suffix));
    }

    // add `fundamentalRatios` to the URL query string
    if (getFundamentalRatios() != null) {
      joiner.add(getFundamentalRatios().toUrlQueryString(prefix + "fundamentalRatios" + suffix));
    }

    // add `marketBreadth` to the URL query string
    if (getMarketBreadth() != null) {
      joiner.add(getMarketBreadth().toUrlQueryString(prefix + "marketBreadth" + suffix));
    }

    // add `historicalComparison` to the URL query string
    if (getHistoricalComparison() != null) {
      joiner.add(getHistoricalComparison().toUrlQueryString(prefix + "historicalComparison" + suffix));
    }

    // add `chartPaths` to the URL query string
    if (getChartPaths() != null) {
      joiner.add(getChartPaths().toUrlQueryString(prefix + "chartPaths" + suffix));
    }

    // add `timestamp` to the URL query string
    if (getTimestamp() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stimestamp%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTimestamp()))));
    }

    return joiner.toString();
  }
}

