/*
 * Portfolio Management API
 * API documentation for the Asset Management Portfolio application
 *
 * The version of the OpenAPI document: v1.0
 * Contact: portfolio-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.am.portfolio.client.model.OHLCVModel;
import com.am.portfolio.client.model.TimeSeriesDataModel;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.portfolio.client.invoker.ApiClient;
/**
 * MarketDataModel
 */
@JsonPropertyOrder({
  MarketDataModel.JSON_PROPERTY_LATEST_O_H_L_C_V,
  MarketDataModel.JSON_PROPERTY_MARKET_PRICE,
  MarketDataModel.JSON_PROPERTY_DAY_HIGH,
  MarketDataModel.JSON_PROPERTY_DAY_LOW,
  MarketDataModel.JSON_PROPERTY_FIFTY_TWO_WEEK_HIGH,
  MarketDataModel.JSON_PROPERTY_FIFTY_TWO_WEEK_LOW,
  MarketDataModel.JSON_PROPERTY_PREVIOUS_CLOSE,
  MarketDataModel.JSON_PROPERTY_VOLUME,
  MarketDataModel.JSON_PROPERTY_MARKET_CAP,
  MarketDataModel.JSON_PROPERTY_MARKET_CAP_CATEGORY,
  MarketDataModel.JSON_PROPERTY_PRICE_IN_HOME_CURRENCY,
  MarketDataModel.JSON_PROPERTY_RELATIVE_STRENGTH_INDEX,
  MarketDataModel.JSON_PROPERTY_MOVING_AVERAGE50,
  MarketDataModel.JSON_PROPERTY_MOVING_AVERAGE200,
  MarketDataModel.JSON_PROPERTY_AVERAGE_VOLUME30_DAYS,
  MarketDataModel.JSON_PROPERTY_BETA,
  MarketDataModel.JSON_PROPERTY_VOLATILITY30_DAYS,
  MarketDataModel.JSON_PROPERTY_BID_PRICE,
  MarketDataModel.JSON_PROPERTY_ASK_PRICE,
  MarketDataModel.JSON_PROPERTY_BID_SIZE,
  MarketDataModel.JSON_PROPERTY_ASK_SIZE,
  MarketDataModel.JSON_PROPERTY_SPREAD_PERCENTAGE,
  MarketDataModel.JSON_PROPERTY_TIME_SERIES_DATA
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-26T23:23:15.876134200+05:30[Asia/Calcutta]", comments = "Generator version: 7.20.0")
public class MarketDataModel {
  public static final String JSON_PROPERTY_LATEST_O_H_L_C_V = "latestOHLCV";
  @javax.annotation.Nullable
  private OHLCVModel latestOHLCV;

  public static final String JSON_PROPERTY_MARKET_PRICE = "marketPrice";
  @javax.annotation.Nullable
  private Double marketPrice;

  public static final String JSON_PROPERTY_DAY_HIGH = "dayHigh";
  @javax.annotation.Nullable
  private Double dayHigh;

  public static final String JSON_PROPERTY_DAY_LOW = "dayLow";
  @javax.annotation.Nullable
  private Double dayLow;

  public static final String JSON_PROPERTY_FIFTY_TWO_WEEK_HIGH = "fiftyTwoWeekHigh";
  @javax.annotation.Nullable
  private Double fiftyTwoWeekHigh;

  public static final String JSON_PROPERTY_FIFTY_TWO_WEEK_LOW = "fiftyTwoWeekLow";
  @javax.annotation.Nullable
  private Double fiftyTwoWeekLow;

  public static final String JSON_PROPERTY_PREVIOUS_CLOSE = "previousClose";
  @javax.annotation.Nullable
  private Double previousClose;

  public static final String JSON_PROPERTY_VOLUME = "volume";
  @javax.annotation.Nullable
  private Long volume;

  public static final String JSON_PROPERTY_MARKET_CAP = "marketCap";
  @javax.annotation.Nullable
  private Double marketCap;

  public static final String JSON_PROPERTY_MARKET_CAP_CATEGORY = "marketCapCategory";
  @javax.annotation.Nullable
  private String marketCapCategory;

  public static final String JSON_PROPERTY_PRICE_IN_HOME_CURRENCY = "priceInHomeCurrency";
  @javax.annotation.Nullable
  private Double priceInHomeCurrency;

  public static final String JSON_PROPERTY_RELATIVE_STRENGTH_INDEX = "relativeStrengthIndex";
  @javax.annotation.Nullable
  private Double relativeStrengthIndex;

  public static final String JSON_PROPERTY_MOVING_AVERAGE50 = "movingAverage50";
  @javax.annotation.Nullable
  private Double movingAverage50;

  public static final String JSON_PROPERTY_MOVING_AVERAGE200 = "movingAverage200";
  @javax.annotation.Nullable
  private Double movingAverage200;

  public static final String JSON_PROPERTY_AVERAGE_VOLUME30_DAYS = "averageVolume30Days";
  @javax.annotation.Nullable
  private Double averageVolume30Days;

  public static final String JSON_PROPERTY_BETA = "beta";
  @javax.annotation.Nullable
  private Double beta;

  public static final String JSON_PROPERTY_VOLATILITY30_DAYS = "volatility30Days";
  @javax.annotation.Nullable
  private Double volatility30Days;

  public static final String JSON_PROPERTY_BID_PRICE = "bidPrice";
  @javax.annotation.Nullable
  private Double bidPrice;

  public static final String JSON_PROPERTY_ASK_PRICE = "askPrice";
  @javax.annotation.Nullable
  private Double askPrice;

  public static final String JSON_PROPERTY_BID_SIZE = "bidSize";
  @javax.annotation.Nullable
  private Long bidSize;

  public static final String JSON_PROPERTY_ASK_SIZE = "askSize";
  @javax.annotation.Nullable
  private Long askSize;

  public static final String JSON_PROPERTY_SPREAD_PERCENTAGE = "spreadPercentage";
  @javax.annotation.Nullable
  private Double spreadPercentage;

  public static final String JSON_PROPERTY_TIME_SERIES_DATA = "timeSeriesData";
  @javax.annotation.Nullable
  private List<TimeSeriesDataModel> timeSeriesData = new ArrayList<>();

  public MarketDataModel() { 
  }

  public MarketDataModel latestOHLCV(@javax.annotation.Nullable OHLCVModel latestOHLCV) {
    this.latestOHLCV = latestOHLCV;
    return this;
  }

  /**
   * Get latestOHLCV
   * @return latestOHLCV
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LATEST_O_H_L_C_V, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OHLCVModel getLatestOHLCV() {
    return latestOHLCV;
  }


  @JsonProperty(value = JSON_PROPERTY_LATEST_O_H_L_C_V, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLatestOHLCV(@javax.annotation.Nullable OHLCVModel latestOHLCV) {
    this.latestOHLCV = latestOHLCV;
  }


  public MarketDataModel marketPrice(@javax.annotation.Nullable Double marketPrice) {
    this.marketPrice = marketPrice;
    return this;
  }

  /**
   * Get marketPrice
   * @return marketPrice
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MARKET_PRICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getMarketPrice() {
    return marketPrice;
  }


  @JsonProperty(value = JSON_PROPERTY_MARKET_PRICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMarketPrice(@javax.annotation.Nullable Double marketPrice) {
    this.marketPrice = marketPrice;
  }


  public MarketDataModel dayHigh(@javax.annotation.Nullable Double dayHigh) {
    this.dayHigh = dayHigh;
    return this;
  }

  /**
   * Get dayHigh
   * @return dayHigh
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DAY_HIGH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getDayHigh() {
    return dayHigh;
  }


  @JsonProperty(value = JSON_PROPERTY_DAY_HIGH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDayHigh(@javax.annotation.Nullable Double dayHigh) {
    this.dayHigh = dayHigh;
  }


  public MarketDataModel dayLow(@javax.annotation.Nullable Double dayLow) {
    this.dayLow = dayLow;
    return this;
  }

  /**
   * Get dayLow
   * @return dayLow
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DAY_LOW, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getDayLow() {
    return dayLow;
  }


  @JsonProperty(value = JSON_PROPERTY_DAY_LOW, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDayLow(@javax.annotation.Nullable Double dayLow) {
    this.dayLow = dayLow;
  }


  public MarketDataModel fiftyTwoWeekHigh(@javax.annotation.Nullable Double fiftyTwoWeekHigh) {
    this.fiftyTwoWeekHigh = fiftyTwoWeekHigh;
    return this;
  }

  /**
   * Get fiftyTwoWeekHigh
   * @return fiftyTwoWeekHigh
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FIFTY_TWO_WEEK_HIGH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getFiftyTwoWeekHigh() {
    return fiftyTwoWeekHigh;
  }


  @JsonProperty(value = JSON_PROPERTY_FIFTY_TWO_WEEK_HIGH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFiftyTwoWeekHigh(@javax.annotation.Nullable Double fiftyTwoWeekHigh) {
    this.fiftyTwoWeekHigh = fiftyTwoWeekHigh;
  }


  public MarketDataModel fiftyTwoWeekLow(@javax.annotation.Nullable Double fiftyTwoWeekLow) {
    this.fiftyTwoWeekLow = fiftyTwoWeekLow;
    return this;
  }

  /**
   * Get fiftyTwoWeekLow
   * @return fiftyTwoWeekLow
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FIFTY_TWO_WEEK_LOW, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getFiftyTwoWeekLow() {
    return fiftyTwoWeekLow;
  }


  @JsonProperty(value = JSON_PROPERTY_FIFTY_TWO_WEEK_LOW, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFiftyTwoWeekLow(@javax.annotation.Nullable Double fiftyTwoWeekLow) {
    this.fiftyTwoWeekLow = fiftyTwoWeekLow;
  }


  public MarketDataModel previousClose(@javax.annotation.Nullable Double previousClose) {
    this.previousClose = previousClose;
    return this;
  }

  /**
   * Get previousClose
   * @return previousClose
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PREVIOUS_CLOSE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getPreviousClose() {
    return previousClose;
  }


  @JsonProperty(value = JSON_PROPERTY_PREVIOUS_CLOSE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPreviousClose(@javax.annotation.Nullable Double previousClose) {
    this.previousClose = previousClose;
  }


  public MarketDataModel volume(@javax.annotation.Nullable Long volume) {
    this.volume = volume;
    return this;
  }

  /**
   * Get volume
   * @return volume
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VOLUME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getVolume() {
    return volume;
  }


  @JsonProperty(value = JSON_PROPERTY_VOLUME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVolume(@javax.annotation.Nullable Long volume) {
    this.volume = volume;
  }


  public MarketDataModel marketCap(@javax.annotation.Nullable Double marketCap) {
    this.marketCap = marketCap;
    return this;
  }

  /**
   * Get marketCap
   * @return marketCap
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MARKET_CAP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getMarketCap() {
    return marketCap;
  }


  @JsonProperty(value = JSON_PROPERTY_MARKET_CAP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMarketCap(@javax.annotation.Nullable Double marketCap) {
    this.marketCap = marketCap;
  }


  public MarketDataModel marketCapCategory(@javax.annotation.Nullable String marketCapCategory) {
    this.marketCapCategory = marketCapCategory;
    return this;
  }

  /**
   * Get marketCapCategory
   * @return marketCapCategory
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MARKET_CAP_CATEGORY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getMarketCapCategory() {
    return marketCapCategory;
  }


  @JsonProperty(value = JSON_PROPERTY_MARKET_CAP_CATEGORY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMarketCapCategory(@javax.annotation.Nullable String marketCapCategory) {
    this.marketCapCategory = marketCapCategory;
  }


  public MarketDataModel priceInHomeCurrency(@javax.annotation.Nullable Double priceInHomeCurrency) {
    this.priceInHomeCurrency = priceInHomeCurrency;
    return this;
  }

  /**
   * Get priceInHomeCurrency
   * @return priceInHomeCurrency
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PRICE_IN_HOME_CURRENCY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getPriceInHomeCurrency() {
    return priceInHomeCurrency;
  }


  @JsonProperty(value = JSON_PROPERTY_PRICE_IN_HOME_CURRENCY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPriceInHomeCurrency(@javax.annotation.Nullable Double priceInHomeCurrency) {
    this.priceInHomeCurrency = priceInHomeCurrency;
  }


  public MarketDataModel relativeStrengthIndex(@javax.annotation.Nullable Double relativeStrengthIndex) {
    this.relativeStrengthIndex = relativeStrengthIndex;
    return this;
  }

  /**
   * Get relativeStrengthIndex
   * @return relativeStrengthIndex
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RELATIVE_STRENGTH_INDEX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getRelativeStrengthIndex() {
    return relativeStrengthIndex;
  }


  @JsonProperty(value = JSON_PROPERTY_RELATIVE_STRENGTH_INDEX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRelativeStrengthIndex(@javax.annotation.Nullable Double relativeStrengthIndex) {
    this.relativeStrengthIndex = relativeStrengthIndex;
  }


  public MarketDataModel movingAverage50(@javax.annotation.Nullable Double movingAverage50) {
    this.movingAverage50 = movingAverage50;
    return this;
  }

  /**
   * Get movingAverage50
   * @return movingAverage50
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MOVING_AVERAGE50, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getMovingAverage50() {
    return movingAverage50;
  }


  @JsonProperty(value = JSON_PROPERTY_MOVING_AVERAGE50, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMovingAverage50(@javax.annotation.Nullable Double movingAverage50) {
    this.movingAverage50 = movingAverage50;
  }


  public MarketDataModel movingAverage200(@javax.annotation.Nullable Double movingAverage200) {
    this.movingAverage200 = movingAverage200;
    return this;
  }

  /**
   * Get movingAverage200
   * @return movingAverage200
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MOVING_AVERAGE200, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getMovingAverage200() {
    return movingAverage200;
  }


  @JsonProperty(value = JSON_PROPERTY_MOVING_AVERAGE200, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMovingAverage200(@javax.annotation.Nullable Double movingAverage200) {
    this.movingAverage200 = movingAverage200;
  }


  public MarketDataModel averageVolume30Days(@javax.annotation.Nullable Double averageVolume30Days) {
    this.averageVolume30Days = averageVolume30Days;
    return this;
  }

  /**
   * Get averageVolume30Days
   * @return averageVolume30Days
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AVERAGE_VOLUME30_DAYS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getAverageVolume30Days() {
    return averageVolume30Days;
  }


  @JsonProperty(value = JSON_PROPERTY_AVERAGE_VOLUME30_DAYS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAverageVolume30Days(@javax.annotation.Nullable Double averageVolume30Days) {
    this.averageVolume30Days = averageVolume30Days;
  }


  public MarketDataModel beta(@javax.annotation.Nullable Double beta) {
    this.beta = beta;
    return this;
  }

  /**
   * Get beta
   * @return beta
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BETA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getBeta() {
    return beta;
  }


  @JsonProperty(value = JSON_PROPERTY_BETA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBeta(@javax.annotation.Nullable Double beta) {
    this.beta = beta;
  }


  public MarketDataModel volatility30Days(@javax.annotation.Nullable Double volatility30Days) {
    this.volatility30Days = volatility30Days;
    return this;
  }

  /**
   * Get volatility30Days
   * @return volatility30Days
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VOLATILITY30_DAYS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getVolatility30Days() {
    return volatility30Days;
  }


  @JsonProperty(value = JSON_PROPERTY_VOLATILITY30_DAYS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVolatility30Days(@javax.annotation.Nullable Double volatility30Days) {
    this.volatility30Days = volatility30Days;
  }


  public MarketDataModel bidPrice(@javax.annotation.Nullable Double bidPrice) {
    this.bidPrice = bidPrice;
    return this;
  }

  /**
   * Get bidPrice
   * @return bidPrice
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BID_PRICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getBidPrice() {
    return bidPrice;
  }


  @JsonProperty(value = JSON_PROPERTY_BID_PRICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBidPrice(@javax.annotation.Nullable Double bidPrice) {
    this.bidPrice = bidPrice;
  }


  public MarketDataModel askPrice(@javax.annotation.Nullable Double askPrice) {
    this.askPrice = askPrice;
    return this;
  }

  /**
   * Get askPrice
   * @return askPrice
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ASK_PRICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getAskPrice() {
    return askPrice;
  }


  @JsonProperty(value = JSON_PROPERTY_ASK_PRICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAskPrice(@javax.annotation.Nullable Double askPrice) {
    this.askPrice = askPrice;
  }


  public MarketDataModel bidSize(@javax.annotation.Nullable Long bidSize) {
    this.bidSize = bidSize;
    return this;
  }

  /**
   * Get bidSize
   * @return bidSize
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BID_SIZE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getBidSize() {
    return bidSize;
  }


  @JsonProperty(value = JSON_PROPERTY_BID_SIZE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBidSize(@javax.annotation.Nullable Long bidSize) {
    this.bidSize = bidSize;
  }


  public MarketDataModel askSize(@javax.annotation.Nullable Long askSize) {
    this.askSize = askSize;
    return this;
  }

  /**
   * Get askSize
   * @return askSize
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ASK_SIZE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getAskSize() {
    return askSize;
  }


  @JsonProperty(value = JSON_PROPERTY_ASK_SIZE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAskSize(@javax.annotation.Nullable Long askSize) {
    this.askSize = askSize;
  }


  public MarketDataModel spreadPercentage(@javax.annotation.Nullable Double spreadPercentage) {
    this.spreadPercentage = spreadPercentage;
    return this;
  }

  /**
   * Get spreadPercentage
   * @return spreadPercentage
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SPREAD_PERCENTAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getSpreadPercentage() {
    return spreadPercentage;
  }


  @JsonProperty(value = JSON_PROPERTY_SPREAD_PERCENTAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSpreadPercentage(@javax.annotation.Nullable Double spreadPercentage) {
    this.spreadPercentage = spreadPercentage;
  }


  public MarketDataModel timeSeriesData(@javax.annotation.Nullable List<TimeSeriesDataModel> timeSeriesData) {
    this.timeSeriesData = timeSeriesData;
    return this;
  }

  public MarketDataModel addTimeSeriesDataItem(TimeSeriesDataModel timeSeriesDataItem) {
    if (this.timeSeriesData == null) {
      this.timeSeriesData = new ArrayList<>();
    }
    this.timeSeriesData.add(timeSeriesDataItem);
    return this;
  }

  /**
   * Get timeSeriesData
   * @return timeSeriesData
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIME_SERIES_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<TimeSeriesDataModel> getTimeSeriesData() {
    return timeSeriesData;
  }


  @JsonProperty(value = JSON_PROPERTY_TIME_SERIES_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimeSeriesData(@javax.annotation.Nullable List<TimeSeriesDataModel> timeSeriesData) {
    this.timeSeriesData = timeSeriesData;
  }


  /**
   * Return true if this MarketDataModel object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MarketDataModel marketDataModel = (MarketDataModel) o;
    return Objects.equals(this.latestOHLCV, marketDataModel.latestOHLCV) &&
        Objects.equals(this.marketPrice, marketDataModel.marketPrice) &&
        Objects.equals(this.dayHigh, marketDataModel.dayHigh) &&
        Objects.equals(this.dayLow, marketDataModel.dayLow) &&
        Objects.equals(this.fiftyTwoWeekHigh, marketDataModel.fiftyTwoWeekHigh) &&
        Objects.equals(this.fiftyTwoWeekLow, marketDataModel.fiftyTwoWeekLow) &&
        Objects.equals(this.previousClose, marketDataModel.previousClose) &&
        Objects.equals(this.volume, marketDataModel.volume) &&
        Objects.equals(this.marketCap, marketDataModel.marketCap) &&
        Objects.equals(this.marketCapCategory, marketDataModel.marketCapCategory) &&
        Objects.equals(this.priceInHomeCurrency, marketDataModel.priceInHomeCurrency) &&
        Objects.equals(this.relativeStrengthIndex, marketDataModel.relativeStrengthIndex) &&
        Objects.equals(this.movingAverage50, marketDataModel.movingAverage50) &&
        Objects.equals(this.movingAverage200, marketDataModel.movingAverage200) &&
        Objects.equals(this.averageVolume30Days, marketDataModel.averageVolume30Days) &&
        Objects.equals(this.beta, marketDataModel.beta) &&
        Objects.equals(this.volatility30Days, marketDataModel.volatility30Days) &&
        Objects.equals(this.bidPrice, marketDataModel.bidPrice) &&
        Objects.equals(this.askPrice, marketDataModel.askPrice) &&
        Objects.equals(this.bidSize, marketDataModel.bidSize) &&
        Objects.equals(this.askSize, marketDataModel.askSize) &&
        Objects.equals(this.spreadPercentage, marketDataModel.spreadPercentage) &&
        Objects.equals(this.timeSeriesData, marketDataModel.timeSeriesData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(latestOHLCV, marketPrice, dayHigh, dayLow, fiftyTwoWeekHigh, fiftyTwoWeekLow, previousClose, volume, marketCap, marketCapCategory, priceInHomeCurrency, relativeStrengthIndex, movingAverage50, movingAverage200, averageVolume30Days, beta, volatility30Days, bidPrice, askPrice, bidSize, askSize, spreadPercentage, timeSeriesData);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MarketDataModel {\n");
    sb.append("    latestOHLCV: ").append(toIndentedString(latestOHLCV)).append("\n");
    sb.append("    marketPrice: ").append(toIndentedString(marketPrice)).append("\n");
    sb.append("    dayHigh: ").append(toIndentedString(dayHigh)).append("\n");
    sb.append("    dayLow: ").append(toIndentedString(dayLow)).append("\n");
    sb.append("    fiftyTwoWeekHigh: ").append(toIndentedString(fiftyTwoWeekHigh)).append("\n");
    sb.append("    fiftyTwoWeekLow: ").append(toIndentedString(fiftyTwoWeekLow)).append("\n");
    sb.append("    previousClose: ").append(toIndentedString(previousClose)).append("\n");
    sb.append("    volume: ").append(toIndentedString(volume)).append("\n");
    sb.append("    marketCap: ").append(toIndentedString(marketCap)).append("\n");
    sb.append("    marketCapCategory: ").append(toIndentedString(marketCapCategory)).append("\n");
    sb.append("    priceInHomeCurrency: ").append(toIndentedString(priceInHomeCurrency)).append("\n");
    sb.append("    relativeStrengthIndex: ").append(toIndentedString(relativeStrengthIndex)).append("\n");
    sb.append("    movingAverage50: ").append(toIndentedString(movingAverage50)).append("\n");
    sb.append("    movingAverage200: ").append(toIndentedString(movingAverage200)).append("\n");
    sb.append("    averageVolume30Days: ").append(toIndentedString(averageVolume30Days)).append("\n");
    sb.append("    beta: ").append(toIndentedString(beta)).append("\n");
    sb.append("    volatility30Days: ").append(toIndentedString(volatility30Days)).append("\n");
    sb.append("    bidPrice: ").append(toIndentedString(bidPrice)).append("\n");
    sb.append("    askPrice: ").append(toIndentedString(askPrice)).append("\n");
    sb.append("    bidSize: ").append(toIndentedString(bidSize)).append("\n");
    sb.append("    askSize: ").append(toIndentedString(askSize)).append("\n");
    sb.append("    spreadPercentage: ").append(toIndentedString(spreadPercentage)).append("\n");
    sb.append("    timeSeriesData: ").append(toIndentedString(timeSeriesData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `latestOHLCV` to the URL query string
    if (getLatestOHLCV() != null) {
      joiner.add(getLatestOHLCV().toUrlQueryString(prefix + "latestOHLCV" + suffix));
    }

    // add `marketPrice` to the URL query string
    if (getMarketPrice() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smarketPrice%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMarketPrice()))));
    }

    // add `dayHigh` to the URL query string
    if (getDayHigh() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdayHigh%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDayHigh()))));
    }

    // add `dayLow` to the URL query string
    if (getDayLow() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdayLow%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDayLow()))));
    }

    // add `fiftyTwoWeekHigh` to the URL query string
    if (getFiftyTwoWeekHigh() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfiftyTwoWeekHigh%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFiftyTwoWeekHigh()))));
    }

    // add `fiftyTwoWeekLow` to the URL query string
    if (getFiftyTwoWeekLow() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfiftyTwoWeekLow%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFiftyTwoWeekLow()))));
    }

    // add `previousClose` to the URL query string
    if (getPreviousClose() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spreviousClose%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPreviousClose()))));
    }

    // add `volume` to the URL query string
    if (getVolume() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%svolume%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getVolume()))));
    }

    // add `marketCap` to the URL query string
    if (getMarketCap() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smarketCap%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMarketCap()))));
    }

    // add `marketCapCategory` to the URL query string
    if (getMarketCapCategory() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smarketCapCategory%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMarketCapCategory()))));
    }

    // add `priceInHomeCurrency` to the URL query string
    if (getPriceInHomeCurrency() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spriceInHomeCurrency%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPriceInHomeCurrency()))));
    }

    // add `relativeStrengthIndex` to the URL query string
    if (getRelativeStrengthIndex() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%srelativeStrengthIndex%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRelativeStrengthIndex()))));
    }

    // add `movingAverage50` to the URL query string
    if (getMovingAverage50() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smovingAverage50%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMovingAverage50()))));
    }

    // add `movingAverage200` to the URL query string
    if (getMovingAverage200() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smovingAverage200%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMovingAverage200()))));
    }

    // add `averageVolume30Days` to the URL query string
    if (getAverageVolume30Days() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%saverageVolume30Days%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAverageVolume30Days()))));
    }

    // add `beta` to the URL query string
    if (getBeta() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbeta%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBeta()))));
    }

    // add `volatility30Days` to the URL query string
    if (getVolatility30Days() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%svolatility30Days%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getVolatility30Days()))));
    }

    // add `bidPrice` to the URL query string
    if (getBidPrice() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbidPrice%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBidPrice()))));
    }

    // add `askPrice` to the URL query string
    if (getAskPrice() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%saskPrice%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAskPrice()))));
    }

    // add `bidSize` to the URL query string
    if (getBidSize() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbidSize%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBidSize()))));
    }

    // add `askSize` to the URL query string
    if (getAskSize() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%saskSize%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAskSize()))));
    }

    // add `spreadPercentage` to the URL query string
    if (getSpreadPercentage() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sspreadPercentage%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSpreadPercentage()))));
    }

    // add `timeSeriesData` to the URL query string
    if (getTimeSeriesData() != null) {
      for (int i = 0; i < getTimeSeriesData().size(); i++) {
        if (getTimeSeriesData().get(i) != null) {
          joiner.add(getTimeSeriesData().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%stimeSeriesData%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

