/*
 * Portfolio Management API
 * API documentation for the Asset Management Portfolio application
 *
 * The version of the OpenAPI document: v1.0
 * Contact: portfolio-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.am.portfolio.client.model.EquityModel;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.portfolio.client.invoker.ApiClient;
/**
 * PortfolioModelV1
 */
@JsonPropertyOrder({
  PortfolioModelV1.JSON_PROPERTY_ID,
  PortfolioModelV1.JSON_PROPERTY_NAME,
  PortfolioModelV1.JSON_PROPERTY_DESCRIPTION,
  PortfolioModelV1.JSON_PROPERTY_OWNER,
  PortfolioModelV1.JSON_PROPERTY_CURRENCY,
  PortfolioModelV1.JSON_PROPERTY_FUND_TYPE,
  PortfolioModelV1.JSON_PROPERTY_STATUS,
  PortfolioModelV1.JSON_PROPERTY_TAGS,
  PortfolioModelV1.JSON_PROPERTY_NOTES,
  PortfolioModelV1.JSON_PROPERTY_EQUITY_MODELS,
  PortfolioModelV1.JSON_PROPERTY_TOTAL_VALUE,
  PortfolioModelV1.JSON_PROPERTY_BROKER_TYPE,
  PortfolioModelV1.JSON_PROPERTY_ASSET_COUNT,
  PortfolioModelV1.JSON_PROPERTY_CREATED_AT,
  PortfolioModelV1.JSON_PROPERTY_UPDATED_AT,
  PortfolioModelV1.JSON_PROPERTY_CREATED_BY,
  PortfolioModelV1.JSON_PROPERTY_UPDATED_BY,
  PortfolioModelV1.JSON_PROPERTY_VERSION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-26T23:23:15.876134200+05:30[Asia/Calcutta]", comments = "Generator version: 7.20.0")
public class PortfolioModelV1 {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private UUID id;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_OWNER = "owner";
  @javax.annotation.Nullable
  private String owner;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  @javax.annotation.Nullable
  private String currency;

  /**
   * Gets or Sets fundType
   */
  public enum FundTypeEnum {
    LARGE_CAP_EQUITY_FUND(String.valueOf("Large Cap Equity Fund")),
    
    MID_CAP_EQUITY_FUND(String.valueOf("Mid Cap Equity Fund")),
    
    SMALL_CAP_EQUITY_FUND(String.valueOf("Small Cap Equity Fund")),
    
    MULTI_CAP_EQUITY_FUND(String.valueOf("Multi Cap Equity Fund")),
    
    LARGE_MID_CAP_EQUITY_FUND(String.valueOf("Large & Mid Cap Equity Fund")),
    
    DIVIDEND_YIELD_FUND(String.valueOf("Dividend Yield Fund")),
    
    FOCUSED_EQUITY_FUND(String.valueOf("Focused Equity Fund")),
    
    CONTRA_FUND(String.valueOf("Contra Fund")),
    
    VALUE_FUND(String.valueOf("Value Fund")),
    
    ULTRA_SHORT_DURATION_FUND(String.valueOf("Ultra Short Duration Fund")),
    
    LOW_DURATION_FUND(String.valueOf("Low Duration Fund")),
    
    SHORT_DURATION_FUND(String.valueOf("Short Duration Fund")),
    
    MEDIUM_DURATION_FUND(String.valueOf("Medium Duration Fund")),
    
    LONG_DURATION_FUND(String.valueOf("Long Duration Fund")),
    
    DYNAMIC_BOND_FUND(String.valueOf("Dynamic Bond Fund")),
    
    CORPORATE_BOND_FUND(String.valueOf("Corporate Bond Fund")),
    
    CREDIT_RISK_FUND(String.valueOf("Credit Risk Fund")),
    
    BANKING_AND_PSU_FUND(String.valueOf("Banking and PSU Fund")),
    
    FLOATER_FUND(String.valueOf("Floater Fund")),
    
    AGGRESSIVE_HYBRID_FUND(String.valueOf("Aggressive Hybrid Fund")),
    
    BALANCED_HYBRID_FUND(String.valueOf("Balanced Hybrid Fund")),
    
    CONSERVATIVE_HYBRID_FUND(String.valueOf("Conservative Hybrid Fund")),
    
    EQUITY_SAVINGS_FUND(String.valueOf("Equity Savings Fund")),
    
    MULTI_ASSET_ALLOCATION_FUND(String.valueOf("Multi Asset Allocation Fund")),
    
    NIFTY_50_INDEX_FUND(String.valueOf("Nifty 50 Index Fund")),
    
    SENSEX_INDEX_FUND(String.valueOf("Sensex Index Fund")),
    
    NIFTY_NEXT_50_INDEX_FUND(String.valueOf("Nifty Next 50 Index Fund")),
    
    MIDCAP_INDEX_FUND(String.valueOf("Midcap Index Fund")),
    
    SMALLCAP_INDEX_FUND(String.valueOf("Smallcap Index Fund")),
    
    SECTORAL_INDEX_FUND(String.valueOf("Sectoral Index Fund")),
    
    BANKING_SECTOR_FUND(String.valueOf("Banking Sector Fund")),
    
    IT_SECTOR_FUND(String.valueOf("IT Sector Fund")),
    
    PHARMA_SECTOR_FUND(String.valueOf("Pharma Sector Fund")),
    
    FMCG_SECTOR_FUND(String.valueOf("FMCG Sector Fund")),
    
    INFRASTRUCTURE_FUND(String.valueOf("Infrastructure Fund")),
    
    AUTO_SECTOR_FUND(String.valueOf("Auto Sector Fund")),
    
    POWER_SECTOR_FUND(String.valueOf("Power Sector Fund")),
    
    METAL_SECTOR_FUND(String.valueOf("Metal Sector Fund")),
    
    CONSUMPTION_SECTOR_FUND(String.valueOf("Consumption Sector Fund")),
    
    ESG_FUND(String.valueOf("ESG Fund")),
    
    MNC_FUND(String.valueOf("MNC Fund")),
    
    GLOBAL_ADVANTAGE_FUND(String.valueOf("Global Advantage Fund")),
    
    RETIREMENT_FUND(String.valueOf("Retirement Fund")),
    
    CHILDREN_S_FUND(String.valueOf("Children's Fund")),
    
    PENSION_FUND(String.valueOf("Pension Fund")),
    
    US_EQUITY_FUND(String.valueOf("US Equity Fund")),
    
    EMERGING_MARKETS_FUND(String.valueOf("Emerging Markets Fund")),
    
    GLOBAL_EQUITY_FUND(String.valueOf("Global Equity Fund")),
    
    EUROPEAN_MARKETS_FUND(String.valueOf("European Markets Fund")),
    
    JAPANESE_MARKETS_FUND(String.valueOf("Japanese Markets Fund")),
    
    CHINA_MARKETS_FUND(String.valueOf("China Markets Fund")),
    
    LIQUID_FUND(String.valueOf("Liquid Fund")),
    
    OVERNIGHT_FUND(String.valueOf("Overnight Fund")),
    
    ARBITRAGE_FUND(String.valueOf("Arbitrage Fund")),
    
    GILT_FUND(String.valueOf("Gilt Fund")),
    
    GILT_WITH_CONSTANT_MATURITY(String.valueOf("Gilt with Constant Maturity")),
    
    ELSS_TAX_SAVER(String.valueOf("ELSS Tax Saver")),
    
    FUND_OF_FUNDS_DOMESTIC(String.valueOf("Fund of Funds - Domestic")),
    
    FUND_OF_FUNDS_OVERSEAS(String.valueOf("Fund of Funds - Overseas")),
    
    DEFAULT(String.valueOf("Default"));

    private String value;

    FundTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static FundTypeEnum fromValue(String value) {
      for (FundTypeEnum b : FundTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_FUND_TYPE = "fundType";
  @javax.annotation.Nullable
  private FundTypeEnum fundType;

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nullable
  private String status;

  public static final String JSON_PROPERTY_TAGS = "tags";
  @javax.annotation.Nullable
  private String tags;

  public static final String JSON_PROPERTY_NOTES = "notes";
  @javax.annotation.Nullable
  private String notes;

  public static final String JSON_PROPERTY_EQUITY_MODELS = "equityModels";
  @javax.annotation.Nullable
  private List<EquityModel> equityModels = new ArrayList<>();

  public static final String JSON_PROPERTY_TOTAL_VALUE = "totalValue";
  @javax.annotation.Nullable
  private Double totalValue;

  /**
   * Gets or Sets brokerType
   */
  public enum BrokerTypeEnum {
    DHAN(String.valueOf("DHAN")),
    
    ZERODHA(String.valueOf("ZERODHA")),
    
    MSTOCK(String.valueOf("MSTOCK")),
    
    GROW(String.valueOf("GROW")),
    
    KOTAK(String.valueOf("KOTAK"));

    private String value;

    BrokerTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static BrokerTypeEnum fromValue(String value) {
      for (BrokerTypeEnum b : BrokerTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_BROKER_TYPE = "brokerType";
  @javax.annotation.Nullable
  private BrokerTypeEnum brokerType;

  public static final String JSON_PROPERTY_ASSET_COUNT = "assetCount";
  @javax.annotation.Nullable
  private Integer assetCount;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @javax.annotation.Nullable
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  @javax.annotation.Nullable
  private OffsetDateTime updatedAt;

  public static final String JSON_PROPERTY_CREATED_BY = "createdBy";
  @javax.annotation.Nullable
  private String createdBy;

  public static final String JSON_PROPERTY_UPDATED_BY = "updatedBy";
  @javax.annotation.Nullable
  private String updatedBy;

  public static final String JSON_PROPERTY_VERSION = "version";
  @javax.annotation.Nullable
  private Long version;

  public PortfolioModelV1() { 
  }

  public PortfolioModelV1 id(@javax.annotation.Nullable UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable UUID id) {
    this.id = id;
  }


  public PortfolioModelV1 name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public PortfolioModelV1 description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public PortfolioModelV1 owner(@javax.annotation.Nullable String owner) {
    this.owner = owner;
    return this;
  }

  /**
   * Get owner
   * @return owner
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OWNER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getOwner() {
    return owner;
  }


  @JsonProperty(value = JSON_PROPERTY_OWNER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOwner(@javax.annotation.Nullable String owner) {
    this.owner = owner;
  }


  public PortfolioModelV1 currency(@javax.annotation.Nullable String currency) {
    this.currency = currency;
    return this;
  }

  /**
   * Get currency
   * @return currency
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCurrency() {
    return currency;
  }


  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCurrency(@javax.annotation.Nullable String currency) {
    this.currency = currency;
  }


  public PortfolioModelV1 fundType(@javax.annotation.Nullable FundTypeEnum fundType) {
    this.fundType = fundType;
    return this;
  }

  /**
   * Get fundType
   * @return fundType
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FUND_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public FundTypeEnum getFundType() {
    return fundType;
  }


  @JsonProperty(value = JSON_PROPERTY_FUND_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFundType(@javax.annotation.Nullable FundTypeEnum fundType) {
    this.fundType = fundType;
  }


  public PortfolioModelV1 status(@javax.annotation.Nullable String status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@javax.annotation.Nullable String status) {
    this.status = status;
  }


  public PortfolioModelV1 tags(@javax.annotation.Nullable String tags) {
    this.tags = tags;
    return this;
  }

  /**
   * Get tags
   * @return tags
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TAGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTags() {
    return tags;
  }


  @JsonProperty(value = JSON_PROPERTY_TAGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTags(@javax.annotation.Nullable String tags) {
    this.tags = tags;
  }


  public PortfolioModelV1 notes(@javax.annotation.Nullable String notes) {
    this.notes = notes;
    return this;
  }

  /**
   * Get notes
   * @return notes
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NOTES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getNotes() {
    return notes;
  }


  @JsonProperty(value = JSON_PROPERTY_NOTES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNotes(@javax.annotation.Nullable String notes) {
    this.notes = notes;
  }


  public PortfolioModelV1 equityModels(@javax.annotation.Nullable List<EquityModel> equityModels) {
    this.equityModels = equityModels;
    return this;
  }

  public PortfolioModelV1 addEquityModelsItem(EquityModel equityModelsItem) {
    if (this.equityModels == null) {
      this.equityModels = new ArrayList<>();
    }
    this.equityModels.add(equityModelsItem);
    return this;
  }

  /**
   * Get equityModels
   * @return equityModels
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EQUITY_MODELS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<EquityModel> getEquityModels() {
    return equityModels;
  }


  @JsonProperty(value = JSON_PROPERTY_EQUITY_MODELS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEquityModels(@javax.annotation.Nullable List<EquityModel> equityModels) {
    this.equityModels = equityModels;
  }


  public PortfolioModelV1 totalValue(@javax.annotation.Nullable Double totalValue) {
    this.totalValue = totalValue;
    return this;
  }

  /**
   * Get totalValue
   * @return totalValue
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOTAL_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getTotalValue() {
    return totalValue;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalValue(@javax.annotation.Nullable Double totalValue) {
    this.totalValue = totalValue;
  }


  public PortfolioModelV1 brokerType(@javax.annotation.Nullable BrokerTypeEnum brokerType) {
    this.brokerType = brokerType;
    return this;
  }

  /**
   * Get brokerType
   * @return brokerType
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BROKER_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BrokerTypeEnum getBrokerType() {
    return brokerType;
  }


  @JsonProperty(value = JSON_PROPERTY_BROKER_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBrokerType(@javax.annotation.Nullable BrokerTypeEnum brokerType) {
    this.brokerType = brokerType;
  }


  public PortfolioModelV1 assetCount(@javax.annotation.Nullable Integer assetCount) {
    this.assetCount = assetCount;
    return this;
  }

  /**
   * Get assetCount
   * @return assetCount
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ASSET_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getAssetCount() {
    return assetCount;
  }


  @JsonProperty(value = JSON_PROPERTY_ASSET_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAssetCount(@javax.annotation.Nullable Integer assetCount) {
    this.assetCount = assetCount;
  }


  public PortfolioModelV1 createdAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public PortfolioModelV1 updatedAt(@javax.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(@javax.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public PortfolioModelV1 createdBy(@javax.annotation.Nullable String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

  /**
   * Get createdBy
   * @return createdBy
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_BY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCreatedBy() {
    return createdBy;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_BY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedBy(@javax.annotation.Nullable String createdBy) {
    this.createdBy = createdBy;
  }


  public PortfolioModelV1 updatedBy(@javax.annotation.Nullable String updatedBy) {
    this.updatedBy = updatedBy;
    return this;
  }

  /**
   * Get updatedBy
   * @return updatedBy
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UPDATED_BY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getUpdatedBy() {
    return updatedBy;
  }


  @JsonProperty(value = JSON_PROPERTY_UPDATED_BY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedBy(@javax.annotation.Nullable String updatedBy) {
    this.updatedBy = updatedBy;
  }


  public PortfolioModelV1 version(@javax.annotation.Nullable Long version) {
    this.version = version;
    return this;
  }

  /**
   * Get version
   * @return version
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getVersion() {
    return version;
  }


  @JsonProperty(value = JSON_PROPERTY_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVersion(@javax.annotation.Nullable Long version) {
    this.version = version;
  }


  /**
   * Return true if this PortfolioModelV1 object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PortfolioModelV1 portfolioModelV1 = (PortfolioModelV1) o;
    return Objects.equals(this.id, portfolioModelV1.id) &&
        Objects.equals(this.name, portfolioModelV1.name) &&
        Objects.equals(this.description, portfolioModelV1.description) &&
        Objects.equals(this.owner, portfolioModelV1.owner) &&
        Objects.equals(this.currency, portfolioModelV1.currency) &&
        Objects.equals(this.fundType, portfolioModelV1.fundType) &&
        Objects.equals(this.status, portfolioModelV1.status) &&
        Objects.equals(this.tags, portfolioModelV1.tags) &&
        Objects.equals(this.notes, portfolioModelV1.notes) &&
        Objects.equals(this.equityModels, portfolioModelV1.equityModels) &&
        Objects.equals(this.totalValue, portfolioModelV1.totalValue) &&
        Objects.equals(this.brokerType, portfolioModelV1.brokerType) &&
        Objects.equals(this.assetCount, portfolioModelV1.assetCount) &&
        Objects.equals(this.createdAt, portfolioModelV1.createdAt) &&
        Objects.equals(this.updatedAt, portfolioModelV1.updatedAt) &&
        Objects.equals(this.createdBy, portfolioModelV1.createdBy) &&
        Objects.equals(this.updatedBy, portfolioModelV1.updatedBy) &&
        Objects.equals(this.version, portfolioModelV1.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, owner, currency, fundType, status, tags, notes, equityModels, totalValue, brokerType, assetCount, createdAt, updatedAt, createdBy, updatedBy, version);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PortfolioModelV1 {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    fundType: ").append(toIndentedString(fundType)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    notes: ").append(toIndentedString(notes)).append("\n");
    sb.append("    equityModels: ").append(toIndentedString(equityModels)).append("\n");
    sb.append("    totalValue: ").append(toIndentedString(totalValue)).append("\n");
    sb.append("    brokerType: ").append(toIndentedString(brokerType)).append("\n");
    sb.append("    assetCount: ").append(toIndentedString(assetCount)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    updatedBy: ").append(toIndentedString(updatedBy)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `description` to the URL query string
    if (getDescription() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdescription%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDescription()))));
    }

    // add `owner` to the URL query string
    if (getOwner() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sowner%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOwner()))));
    }

    // add `currency` to the URL query string
    if (getCurrency() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scurrency%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCurrency()))));
    }

    // add `fundType` to the URL query string
    if (getFundType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfundType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFundType()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `tags` to the URL query string
    if (getTags() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stags%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTags()))));
    }

    // add `notes` to the URL query string
    if (getNotes() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%snotes%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getNotes()))));
    }

    // add `equityModels` to the URL query string
    if (getEquityModels() != null) {
      for (int i = 0; i < getEquityModels().size(); i++) {
        if (getEquityModels().get(i) != null) {
          joiner.add(getEquityModels().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sequityModels%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `totalValue` to the URL query string
    if (getTotalValue() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stotalValue%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTotalValue()))));
    }

    // add `brokerType` to the URL query string
    if (getBrokerType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbrokerType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBrokerType()))));
    }

    // add `assetCount` to the URL query string
    if (getAssetCount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sassetCount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAssetCount()))));
    }

    // add `createdAt` to the URL query string
    if (getCreatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%screatedAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedAt()))));
    }

    // add `updatedAt` to the URL query string
    if (getUpdatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%supdatedAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUpdatedAt()))));
    }

    // add `createdBy` to the URL query string
    if (getCreatedBy() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%screatedBy%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedBy()))));
    }

    // add `updatedBy` to the URL query string
    if (getUpdatedBy() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%supdatedBy%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUpdatedBy()))));
    }

    // add `version` to the URL query string
    if (getVersion() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sversion%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getVersion()))));
    }

    return joiner.toString();
  }
}

