/*
 * Portfolio Management API
 * API documentation for the Asset Management Portfolio application
 *
 * The version of the OpenAPI document: v1.0
 * Contact: portfolio-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.portfolio.client.invoker.ApiClient;
/**
 * SectorWeight
 */
@JsonPropertyOrder({
  SectorWeight.JSON_PROPERTY_SECTOR_NAME,
  SectorWeight.JSON_PROPERTY_WEIGHT_PERCENTAGE,
  SectorWeight.JSON_PROPERTY_MARKET_CAP,
  SectorWeight.JSON_PROPERTY_TOP_STOCKS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-26T23:23:15.876134200+05:30[Asia/Calcutta]", comments = "Generator version: 7.20.0")
public class SectorWeight {
  public static final String JSON_PROPERTY_SECTOR_NAME = "sectorName";
  @javax.annotation.Nullable
  private String sectorName;

  public static final String JSON_PROPERTY_WEIGHT_PERCENTAGE = "weightPercentage";
  @javax.annotation.Nullable
  private Double weightPercentage;

  public static final String JSON_PROPERTY_MARKET_CAP = "marketCap";
  @javax.annotation.Nullable
  private Double marketCap;

  public static final String JSON_PROPERTY_TOP_STOCKS = "topStocks";
  @javax.annotation.Nullable
  private List<String> topStocks = new ArrayList<>();

  public SectorWeight() { 
  }

  public SectorWeight sectorName(@javax.annotation.Nullable String sectorName) {
    this.sectorName = sectorName;
    return this;
  }

  /**
   * Get sectorName
   * @return sectorName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SECTOR_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSectorName() {
    return sectorName;
  }


  @JsonProperty(value = JSON_PROPERTY_SECTOR_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSectorName(@javax.annotation.Nullable String sectorName) {
    this.sectorName = sectorName;
  }


  public SectorWeight weightPercentage(@javax.annotation.Nullable Double weightPercentage) {
    this.weightPercentage = weightPercentage;
    return this;
  }

  /**
   * Get weightPercentage
   * @return weightPercentage
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WEIGHT_PERCENTAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getWeightPercentage() {
    return weightPercentage;
  }


  @JsonProperty(value = JSON_PROPERTY_WEIGHT_PERCENTAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWeightPercentage(@javax.annotation.Nullable Double weightPercentage) {
    this.weightPercentage = weightPercentage;
  }


  public SectorWeight marketCap(@javax.annotation.Nullable Double marketCap) {
    this.marketCap = marketCap;
    return this;
  }

  /**
   * Get marketCap
   * @return marketCap
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MARKET_CAP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getMarketCap() {
    return marketCap;
  }


  @JsonProperty(value = JSON_PROPERTY_MARKET_CAP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMarketCap(@javax.annotation.Nullable Double marketCap) {
    this.marketCap = marketCap;
  }


  public SectorWeight topStocks(@javax.annotation.Nullable List<String> topStocks) {
    this.topStocks = topStocks;
    return this;
  }

  public SectorWeight addTopStocksItem(String topStocksItem) {
    if (this.topStocks == null) {
      this.topStocks = new ArrayList<>();
    }
    this.topStocks.add(topStocksItem);
    return this;
  }

  /**
   * Get topStocks
   * @return topStocks
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOP_STOCKS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getTopStocks() {
    return topStocks;
  }


  @JsonProperty(value = JSON_PROPERTY_TOP_STOCKS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTopStocks(@javax.annotation.Nullable List<String> topStocks) {
    this.topStocks = topStocks;
  }


  /**
   * Return true if this SectorWeight object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SectorWeight sectorWeight = (SectorWeight) o;
    return Objects.equals(this.sectorName, sectorWeight.sectorName) &&
        Objects.equals(this.weightPercentage, sectorWeight.weightPercentage) &&
        Objects.equals(this.marketCap, sectorWeight.marketCap) &&
        Objects.equals(this.topStocks, sectorWeight.topStocks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sectorName, weightPercentage, marketCap, topStocks);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SectorWeight {\n");
    sb.append("    sectorName: ").append(toIndentedString(sectorName)).append("\n");
    sb.append("    weightPercentage: ").append(toIndentedString(weightPercentage)).append("\n");
    sb.append("    marketCap: ").append(toIndentedString(marketCap)).append("\n");
    sb.append("    topStocks: ").append(toIndentedString(topStocks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `sectorName` to the URL query string
    if (getSectorName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssectorName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSectorName()))));
    }

    // add `weightPercentage` to the URL query string
    if (getWeightPercentage() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sweightPercentage%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getWeightPercentage()))));
    }

    // add `marketCap` to the URL query string
    if (getMarketCap() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smarketCap%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMarketCap()))));
    }

    // add `topStocks` to the URL query string
    if (getTopStocks() != null) {
      for (int i = 0; i < getTopStocks().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%stopStocks%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getTopStocks().get(i)))));
      }
    }

    return joiner.toString();
  }
}

