/*
 * Portfolio Management API
 * API documentation for the Asset Management Portfolio application
 *
 * The version of the OpenAPI document: v1.0
 * Contact: portfolio-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.am.portfolio.client.model.IndustryWeight;
import com.am.portfolio.client.model.SectorWeight;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.portfolio.client.invoker.ApiClient;
/**
 * SectorAllocation
 */
@JsonPropertyOrder({
  SectorAllocation.JSON_PROPERTY_SECTOR_WEIGHTS,
  SectorAllocation.JSON_PROPERTY_INDUSTRY_WEIGHTS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-26T23:23:15.876134200+05:30[Asia/Calcutta]", comments = "Generator version: 7.20.0")
public class SectorAllocation {
  public static final String JSON_PROPERTY_SECTOR_WEIGHTS = "sectorWeights";
  @javax.annotation.Nullable
  private List<SectorWeight> sectorWeights = new ArrayList<>();

  public static final String JSON_PROPERTY_INDUSTRY_WEIGHTS = "industryWeights";
  @javax.annotation.Nullable
  private List<IndustryWeight> industryWeights = new ArrayList<>();

  public SectorAllocation() { 
  }

  public SectorAllocation sectorWeights(@javax.annotation.Nullable List<SectorWeight> sectorWeights) {
    this.sectorWeights = sectorWeights;
    return this;
  }

  public SectorAllocation addSectorWeightsItem(SectorWeight sectorWeightsItem) {
    if (this.sectorWeights == null) {
      this.sectorWeights = new ArrayList<>();
    }
    this.sectorWeights.add(sectorWeightsItem);
    return this;
  }

  /**
   * Get sectorWeights
   * @return sectorWeights
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SECTOR_WEIGHTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<SectorWeight> getSectorWeights() {
    return sectorWeights;
  }


  @JsonProperty(value = JSON_PROPERTY_SECTOR_WEIGHTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSectorWeights(@javax.annotation.Nullable List<SectorWeight> sectorWeights) {
    this.sectorWeights = sectorWeights;
  }


  public SectorAllocation industryWeights(@javax.annotation.Nullable List<IndustryWeight> industryWeights) {
    this.industryWeights = industryWeights;
    return this;
  }

  public SectorAllocation addIndustryWeightsItem(IndustryWeight industryWeightsItem) {
    if (this.industryWeights == null) {
      this.industryWeights = new ArrayList<>();
    }
    this.industryWeights.add(industryWeightsItem);
    return this;
  }

  /**
   * Get industryWeights
   * @return industryWeights
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INDUSTRY_WEIGHTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<IndustryWeight> getIndustryWeights() {
    return industryWeights;
  }


  @JsonProperty(value = JSON_PROPERTY_INDUSTRY_WEIGHTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIndustryWeights(@javax.annotation.Nullable List<IndustryWeight> industryWeights) {
    this.industryWeights = industryWeights;
  }


  /**
   * Return true if this SectorAllocation object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SectorAllocation sectorAllocation = (SectorAllocation) o;
    return Objects.equals(this.sectorWeights, sectorAllocation.sectorWeights) &&
        Objects.equals(this.industryWeights, sectorAllocation.industryWeights);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sectorWeights, industryWeights);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SectorAllocation {\n");
    sb.append("    sectorWeights: ").append(toIndentedString(sectorWeights)).append("\n");
    sb.append("    industryWeights: ").append(toIndentedString(industryWeights)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `sectorWeights` to the URL query string
    if (getSectorWeights() != null) {
      for (int i = 0; i < getSectorWeights().size(); i++) {
        if (getSectorWeights().get(i) != null) {
          joiner.add(getSectorWeights().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%ssectorWeights%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `industryWeights` to the URL query string
    if (getIndustryWeights() != null) {
      for (int i = 0; i < getIndustryWeights().size(); i++) {
        if (getIndustryWeights().get(i) != null) {
          joiner.add(getIndustryWeights().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sindustryWeights%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

