/*
 * Portfolio Management API
 * API documentation for the Asset Management Portfolio application
 *
 * The version of the OpenAPI document: v1.0
 * Contact: portfolio-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.am.portfolio.client.api;

import com.am.portfolio.client.invoker.ApiClient;
import com.am.portfolio.client.invoker.ApiException;
import com.am.portfolio.client.invoker.ApiResponse;
import com.am.portfolio.client.invoker.Configuration;
import com.am.portfolio.client.invoker.Pair;

import com.am.portfolio.client.model.PortfolioBasicInfo;
import com.am.portfolio.client.model.PortfolioHoldings;
import com.am.portfolio.client.model.PortfolioModelV1;
import com.am.portfolio.client.model.PortfolioSummaryV1;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-26T23:23:15.876134200+05:30[Asia/Calcutta]", comments = "Generator version: 7.20.0")
public class PortfolioManagementApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public PortfolioManagementApi() {
    this(Configuration.getDefaultApiClient());
  }

  public PortfolioManagementApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Get portfolio IDs and names
   * Retrieves a lightweight list of portfolio IDs and names for all user portfolios
   * @return List&lt;PortfolioBasicInfo&gt;
   * @throws ApiException if fails to make API call
   */
  public List<PortfolioBasicInfo> getPortfolioBasicDetails() throws ApiException {
    return getPortfolioBasicDetails(null);
  }

  /**
   * Get portfolio IDs and names
   * Retrieves a lightweight list of portfolio IDs and names for all user portfolios
   * @param headers Optional headers to include in the request
   * @return List&lt;PortfolioBasicInfo&gt;
   * @throws ApiException if fails to make API call
   */
  public List<PortfolioBasicInfo> getPortfolioBasicDetails(Map<String, String> headers) throws ApiException {
    ApiResponse<List<PortfolioBasicInfo>> localVarResponse = getPortfolioBasicDetailsWithHttpInfo(headers);
    return localVarResponse.getData();
  }

  /**
   * Get portfolio IDs and names
   * Retrieves a lightweight list of portfolio IDs and names for all user portfolios
   * @return ApiResponse&lt;List&lt;PortfolioBasicInfo&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<PortfolioBasicInfo>> getPortfolioBasicDetailsWithHttpInfo() throws ApiException {
    return getPortfolioBasicDetailsWithHttpInfo(null);
  }

  /**
   * Get portfolio IDs and names
   * Retrieves a lightweight list of portfolio IDs and names for all user portfolios
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;List&lt;PortfolioBasicInfo&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<PortfolioBasicInfo>> getPortfolioBasicDetailsWithHttpInfo(Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getPortfolioBasicDetailsRequestBuilder(headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getPortfolioBasicDetails", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<List<PortfolioBasicInfo>>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        List<PortfolioBasicInfo> responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<List<PortfolioBasicInfo>>() {});
        

        return new ApiResponse<List<PortfolioBasicInfo>>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getPortfolioBasicDetailsRequestBuilder(Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/portfolios/list";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "*/*");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get portfolio by ID
   * Retrieves detailed portfolio information for a specific portfolio ID
   * @param portfolioId Portfolio ID (UUID format) (required)
   * @return PortfolioModelV1
   * @throws ApiException if fails to make API call
   */
  public PortfolioModelV1 getPortfolioById(@javax.annotation.Nonnull String portfolioId) throws ApiException {
    return getPortfolioById(portfolioId, null);
  }

  /**
   * Get portfolio by ID
   * Retrieves detailed portfolio information for a specific portfolio ID
   * @param portfolioId Portfolio ID (UUID format) (required)
   * @param headers Optional headers to include in the request
   * @return PortfolioModelV1
   * @throws ApiException if fails to make API call
   */
  public PortfolioModelV1 getPortfolioById(@javax.annotation.Nonnull String portfolioId, Map<String, String> headers) throws ApiException {
    ApiResponse<PortfolioModelV1> localVarResponse = getPortfolioByIdWithHttpInfo(portfolioId, headers);
    return localVarResponse.getData();
  }

  /**
   * Get portfolio by ID
   * Retrieves detailed portfolio information for a specific portfolio ID
   * @param portfolioId Portfolio ID (UUID format) (required)
   * @return ApiResponse&lt;PortfolioModelV1&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PortfolioModelV1> getPortfolioByIdWithHttpInfo(@javax.annotation.Nonnull String portfolioId) throws ApiException {
    return getPortfolioByIdWithHttpInfo(portfolioId, null);
  }

  /**
   * Get portfolio by ID
   * Retrieves detailed portfolio information for a specific portfolio ID
   * @param portfolioId Portfolio ID (UUID format) (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;PortfolioModelV1&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PortfolioModelV1> getPortfolioByIdWithHttpInfo(@javax.annotation.Nonnull String portfolioId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getPortfolioByIdRequestBuilder(portfolioId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getPortfolioById", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<PortfolioModelV1>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        PortfolioModelV1 responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<PortfolioModelV1>() {});
        

        return new ApiResponse<PortfolioModelV1>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getPortfolioByIdRequestBuilder(@javax.annotation.Nonnull String portfolioId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'portfolioId' is set
    if (portfolioId == null) {
      throw new ApiException(400, "Missing the required parameter 'portfolioId' when calling getPortfolioById");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/portfolios/{portfolioId}"
        .replace("{portfolioId}", ApiClient.urlEncode(portfolioId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "*/*, application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get portfolio holdings
   * Retrieves all holdings across portfolios for a user with current values. Optionally filter by specific portfolio ID.
   * @param portfolioId Optional portfolio ID to filter results for specific portfolio (optional)
   * @param page  (optional)
   * @param size  (optional)
   * @param interval  (optional)
   * @return PortfolioHoldings
   * @throws ApiException if fails to make API call
   */
  public PortfolioHoldings getPortfolioHoldings(@javax.annotation.Nullable String portfolioId, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer size, @javax.annotation.Nullable String interval) throws ApiException {
    return getPortfolioHoldings(portfolioId, page, size, interval, null);
  }

  /**
   * Get portfolio holdings
   * Retrieves all holdings across portfolios for a user with current values. Optionally filter by specific portfolio ID.
   * @param portfolioId Optional portfolio ID to filter results for specific portfolio (optional)
   * @param page  (optional)
   * @param size  (optional)
   * @param interval  (optional)
   * @param headers Optional headers to include in the request
   * @return PortfolioHoldings
   * @throws ApiException if fails to make API call
   */
  public PortfolioHoldings getPortfolioHoldings(@javax.annotation.Nullable String portfolioId, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer size, @javax.annotation.Nullable String interval, Map<String, String> headers) throws ApiException {
    ApiResponse<PortfolioHoldings> localVarResponse = getPortfolioHoldingsWithHttpInfo(portfolioId, page, size, interval, headers);
    return localVarResponse.getData();
  }

  /**
   * Get portfolio holdings
   * Retrieves all holdings across portfolios for a user with current values. Optionally filter by specific portfolio ID.
   * @param portfolioId Optional portfolio ID to filter results for specific portfolio (optional)
   * @param page  (optional)
   * @param size  (optional)
   * @param interval  (optional)
   * @return ApiResponse&lt;PortfolioHoldings&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PortfolioHoldings> getPortfolioHoldingsWithHttpInfo(@javax.annotation.Nullable String portfolioId, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer size, @javax.annotation.Nullable String interval) throws ApiException {
    return getPortfolioHoldingsWithHttpInfo(portfolioId, page, size, interval, null);
  }

  /**
   * Get portfolio holdings
   * Retrieves all holdings across portfolios for a user with current values. Optionally filter by specific portfolio ID.
   * @param portfolioId Optional portfolio ID to filter results for specific portfolio (optional)
   * @param page  (optional)
   * @param size  (optional)
   * @param interval  (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;PortfolioHoldings&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PortfolioHoldings> getPortfolioHoldingsWithHttpInfo(@javax.annotation.Nullable String portfolioId, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer size, @javax.annotation.Nullable String interval, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getPortfolioHoldingsRequestBuilder(portfolioId, page, size, interval, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getPortfolioHoldings", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<PortfolioHoldings>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        PortfolioHoldings responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<PortfolioHoldings>() {});
        

        return new ApiResponse<PortfolioHoldings>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getPortfolioHoldingsRequestBuilder(@javax.annotation.Nullable String portfolioId, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer size, @javax.annotation.Nullable String interval, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/portfolios/holdings";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "portfolioId";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("portfolioId", portfolioId));
    localVarQueryParameterBaseName = "page";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("page", page));
    localVarQueryParameterBaseName = "size";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("size", size));
    localVarQueryParameterBaseName = "interval";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("interval", interval));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "*/*");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get portfolio summary
   * Retrieves a summary of all portfolios for a user with performance metrics. Optionally filter by specific portfolio ID.
   * @param portfolioId Optional portfolio ID to filter results for specific portfolio (optional)
   * @param page  (optional)
   * @param size  (optional)
   * @param interval  (optional)
   * @return PortfolioSummaryV1
   * @throws ApiException if fails to make API call
   */
  public PortfolioSummaryV1 getPortfolioSummary(@javax.annotation.Nullable String portfolioId, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer size, @javax.annotation.Nullable String interval) throws ApiException {
    return getPortfolioSummary(portfolioId, page, size, interval, null);
  }

  /**
   * Get portfolio summary
   * Retrieves a summary of all portfolios for a user with performance metrics. Optionally filter by specific portfolio ID.
   * @param portfolioId Optional portfolio ID to filter results for specific portfolio (optional)
   * @param page  (optional)
   * @param size  (optional)
   * @param interval  (optional)
   * @param headers Optional headers to include in the request
   * @return PortfolioSummaryV1
   * @throws ApiException if fails to make API call
   */
  public PortfolioSummaryV1 getPortfolioSummary(@javax.annotation.Nullable String portfolioId, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer size, @javax.annotation.Nullable String interval, Map<String, String> headers) throws ApiException {
    ApiResponse<PortfolioSummaryV1> localVarResponse = getPortfolioSummaryWithHttpInfo(portfolioId, page, size, interval, headers);
    return localVarResponse.getData();
  }

  /**
   * Get portfolio summary
   * Retrieves a summary of all portfolios for a user with performance metrics. Optionally filter by specific portfolio ID.
   * @param portfolioId Optional portfolio ID to filter results for specific portfolio (optional)
   * @param page  (optional)
   * @param size  (optional)
   * @param interval  (optional)
   * @return ApiResponse&lt;PortfolioSummaryV1&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PortfolioSummaryV1> getPortfolioSummaryWithHttpInfo(@javax.annotation.Nullable String portfolioId, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer size, @javax.annotation.Nullable String interval) throws ApiException {
    return getPortfolioSummaryWithHttpInfo(portfolioId, page, size, interval, null);
  }

  /**
   * Get portfolio summary
   * Retrieves a summary of all portfolios for a user with performance metrics. Optionally filter by specific portfolio ID.
   * @param portfolioId Optional portfolio ID to filter results for specific portfolio (optional)
   * @param page  (optional)
   * @param size  (optional)
   * @param interval  (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;PortfolioSummaryV1&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PortfolioSummaryV1> getPortfolioSummaryWithHttpInfo(@javax.annotation.Nullable String portfolioId, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer size, @javax.annotation.Nullable String interval, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getPortfolioSummaryRequestBuilder(portfolioId, page, size, interval, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getPortfolioSummary", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<PortfolioSummaryV1>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        PortfolioSummaryV1 responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<PortfolioSummaryV1>() {});
        

        return new ApiResponse<PortfolioSummaryV1>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getPortfolioSummaryRequestBuilder(@javax.annotation.Nullable String portfolioId, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer size, @javax.annotation.Nullable String interval, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/portfolios/summary";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "portfolioId";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("portfolioId", portfolioId));
    localVarQueryParameterBaseName = "page";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("page", page));
    localVarQueryParameterBaseName = "size";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("size", size));
    localVarQueryParameterBaseName = "interval";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("interval", interval));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "*/*");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get all portfolios for user
   * Retrieves all portfolios associated with a specific user ID
   * @return List&lt;PortfolioModelV1&gt;
   * @throws ApiException if fails to make API call
   */
  public List<PortfolioModelV1> getPortfolios() throws ApiException {
    return getPortfolios(null);
  }

  /**
   * Get all portfolios for user
   * Retrieves all portfolios associated with a specific user ID
   * @param headers Optional headers to include in the request
   * @return List&lt;PortfolioModelV1&gt;
   * @throws ApiException if fails to make API call
   */
  public List<PortfolioModelV1> getPortfolios(Map<String, String> headers) throws ApiException {
    ApiResponse<List<PortfolioModelV1>> localVarResponse = getPortfoliosWithHttpInfo(headers);
    return localVarResponse.getData();
  }

  /**
   * Get all portfolios for user
   * Retrieves all portfolios associated with a specific user ID
   * @return ApiResponse&lt;List&lt;PortfolioModelV1&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<PortfolioModelV1>> getPortfoliosWithHttpInfo() throws ApiException {
    return getPortfoliosWithHttpInfo(null);
  }

  /**
   * Get all portfolios for user
   * Retrieves all portfolios associated with a specific user ID
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;List&lt;PortfolioModelV1&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<PortfolioModelV1>> getPortfoliosWithHttpInfo(Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getPortfoliosRequestBuilder(headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getPortfolios", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<List<PortfolioModelV1>>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        List<PortfolioModelV1> responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<List<PortfolioModelV1>>() {});
        

        return new ApiResponse<List<PortfolioModelV1>>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getPortfoliosRequestBuilder(Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/portfolios";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "*/*");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
