/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.analysis.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MoverItem
 */
class MoverItemTest {
    private final MoverItem model = new MoverItem();

    /**
     * Model tests for MoverItem
     */
    @Test
    void testMoverItem() {
        // TODO: test MoverItem
    }

    /**
     * Test the property 'symbol'
     */
    @Test
    void symbolTest() {
        // TODO: test symbol
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'price'
     */
    @Test
    void priceTest() {
        // TODO: test price
    }

    /**
     * Test the property 'changePercentage'
     */
    @Test
    void changePercentageTest() {
        // TODO: test changePercentage
    }

    /**
     * Test the property 'changeAmount'
     */
    @Test
    void changeAmountTest() {
        // TODO: test changeAmount
    }

    /**
     * Test the property 'sector'
     */
    @Test
    void sectorTest() {
        // TODO: test sector
    }

    /**
     * Test the property 'assetClass'
     */
    @Test
    void assetClassTest() {
        // TODO: test assetClass
    }

    /**
     * Test the property 'marketCapType'
     */
    @Test
    void marketCapTypeTest() {
        // TODO: test marketCapType
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    void quantityTest() {
        // TODO: test quantity
    }

    /**
     * Test the property 'currentValue'
     */
    @Test
    void currentValueTest() {
        // TODO: test currentValue
    }

    /**
     * Test the property 'investedValue'
     */
    @Test
    void investedValueTest() {
        // TODO: test investedValue
    }

    /**
     * Test the property 'allocationPercentage'
     */
    @Test
    void allocationPercentageTest() {
        // TODO: test allocationPercentage
    }

    /**
     * Test the property 'pnlPercentage'
     */
    @Test
    void pnlPercentageTest() {
        // TODO: test pnlPercentage
    }

}
