/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.analysis.model;

import com.am.portfolio.client.analysis.model.DataPoint;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PerformanceResponse
 */
class PerformanceResponseTest {
    private final PerformanceResponse model = new PerformanceResponse();

    /**
     * Model tests for PerformanceResponse
     */
    @Test
    void testPerformanceResponse() {
        // TODO: test PerformanceResponse
    }

    /**
     * Test the property 'portfolioId'
     */
    @Test
    void portfolioIdTest() {
        // TODO: test portfolioId
    }

    /**
     * Test the property 'timeFrame'
     */
    @Test
    void timeFrameTest() {
        // TODO: test timeFrame
    }

    /**
     * Test the property 'totalReturnPercentage'
     */
    @Test
    void totalReturnPercentageTest() {
        // TODO: test totalReturnPercentage
    }

    /**
     * Test the property 'totalReturnValue'
     */
    @Test
    void totalReturnValueTest() {
        // TODO: test totalReturnValue
    }

    /**
     * Test the property 'chartData'
     */
    @Test
    void chartDataTest() {
        // TODO: test chartData
    }

    /**
     * Test the property 'errorMessage'
     */
    @Test
    void errorMessageTest() {
        // TODO: test errorMessage
    }

}
