/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.analysis.model;

import com.am.portfolio.client.analysis.model.MoverItem;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TopMoversResponse
 */
class TopMoversResponseTest {
    private final TopMoversResponse model = new TopMoversResponse();

    /**
     * Model tests for TopMoversResponse
     */
    @Test
    void testTopMoversResponse() {
        // TODO: test TopMoversResponse
    }

    /**
     * Test the property 'gainers'
     */
    @Test
    void gainersTest() {
        // TODO: test gainers
    }

    /**
     * Test the property 'losers'
     */
    @Test
    void losersTest() {
        // TODO: test losers
    }

}
