spring:
  config:
    activate:
      on-profile: local
  elasticsearch:
    uris: http://localhost:9200

management:
  tracing:
    enabled: false
  otlp:
    tracing:
      endpoint: ""

am:
  observability:
    enabled: true
  security:
    local-mock:
      enabled: true
      user-id: "local-dev-user"
      username: "Local Developer"
      email: "local-dev@am.com"
      roles:
        - "ROLE_USER"
        - "ROLE_ADMIN"
