/*
 * Portfolio Management API
 * API documentation for the Asset Management Portfolio application
 *
 * The version of the OpenAPI document: v1.0
 * Contact: portfolio-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.api;

import com.am.portfolio.client.invoker.ApiException;
import com.am.portfolio.client.model.IndexIndices;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for MarketIndicesApi
 */
@Disabled
public class MarketIndicesApiTest {

    private final MarketIndicesApi api = new MarketIndicesApi();

    
    /**
     * Get all market indices
     *
     * Retrieves all market indices with optional filtering by interval and type
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllMarketIndicesTest() throws ApiException {
        String interval = null;
        String type = null;
        IndexIndices response = 
        api.getAllMarketIndices(interval, type);
        
        // TODO: test validations
    }
    
}
