/*
 * Portfolio Management API
 * API documentation for the Asset Management Portfolio application
 *
 * The version of the OpenAPI document: v1.0
 * Contact: portfolio-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.api;

import com.am.portfolio.client.invoker.ApiException;
import com.am.portfolio.client.model.AdvancedAnalyticsRequest;
import com.am.portfolio.client.model.AdvancedAnalyticsResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for PortfolioAnalyticsApi
 */
@Disabled
public class PortfolioAnalyticsApiTest {

    private final PortfolioAnalyticsApi api = new PortfolioAnalyticsApi();

    
    /**
     * Get advanced portfolio analytics
     *
     * Retrieves comprehensive analytics for a portfolio with customizable components and timeframes
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAdvancedAnalyticsTest() throws ApiException {
        String portfolioId = null;
        AdvancedAnalyticsRequest advancedAnalyticsRequest = null;
        AdvancedAnalyticsResponse response = 
        api.getAdvancedAnalytics(portfolioId, advancedAnalyticsRequest);
        
        // TODO: test validations
    }
    
}
