/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.analysis.api;

import com.am.portfolio.client.analysis.invoker.ApiException;
import com.am.portfolio.client.analysis.model.AllocationResponse;
import com.am.portfolio.client.analysis.model.PerformanceResponse;
import com.am.portfolio.client.analysis.model.TopMoversResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for AnalysisControllerApi
 */
@Disabled
public class AnalysisControllerApiTest {

    private final AnalysisControllerApi api = new AnalysisControllerApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllocationTest() throws ApiException {
        String authorization = null;
        String type = null;
        String id = null;
        String groupBy = null;
        String groupBy2 = null;
        AllocationResponse response = 
        api.getAllocation(authorization, type, id, groupBy, groupBy2);
        
        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPerformanceTest() throws ApiException {
        String authorization = null;
        String type = null;
        String id = null;
        String timeFrame = null;
        PerformanceResponse response = 
        api.getPerformance(authorization, type, id, timeFrame);
        
        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTopMoversByCategoryTest() throws ApiException {
        String authorization = null;
        String type = null;
        String timeFrame = null;
        String groupBy = null;
        String groupBy2 = null;
        TopMoversResponse response = 
        api.getTopMoversByCategory(authorization, type, timeFrame, groupBy, groupBy2);
        
        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTopMoversByEntityTest() throws ApiException {
        String authorization = null;
        String type = null;
        String id = null;
        String timeFrame = null;
        String groupBy = null;
        String groupBy2 = null;
        TopMoversResponse response = 
        api.getTopMoversByEntity(authorization, type, id, timeFrame, groupBy, groupBy2);
        
        // TODO: test validations
    }
    
}
