/*
 * Portfolio Management API
 * API documentation for the Asset Management Portfolio application
 *
 * The version of the OpenAPI document: v1.0
 * Contact: portfolio-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.model;

import com.am.portfolio.client.model.CoreIdentifiers;
import com.am.portfolio.client.model.FeatureConfiguration;
import com.am.portfolio.client.model.FeatureToggles;
import com.am.portfolio.client.model.PaginationRequest;
import com.am.portfolio.client.model.TimeFrameRequest;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AdvancedAnalyticsRequest
 */
class AdvancedAnalyticsRequestTest {
    private final AdvancedAnalyticsRequest model = new AdvancedAnalyticsRequest();

    /**
     * Model tests for AdvancedAnalyticsRequest
     */
    @Test
    void testAdvancedAnalyticsRequest() {
        // TODO: test AdvancedAnalyticsRequest
    }

    /**
     * Test the property 'fromDate'
     */
    @Test
    void fromDateTest() {
        // TODO: test fromDate
    }

    /**
     * Test the property 'toDate'
     */
    @Test
    void toDateTest() {
        // TODO: test toDate
    }

    /**
     * Test the property 'timeFrame'
     */
    @Test
    void timeFrameTest() {
        // TODO: test timeFrame
    }

    /**
     * Test the property 'coreIdentifiers'
     */
    @Test
    void coreIdentifiersTest() {
        // TODO: test coreIdentifiers
    }

    /**
     * Test the property 'pagination'
     */
    @Test
    void paginationTest() {
        // TODO: test pagination
    }

    /**
     * Test the property 'featureToggles'
     */
    @Test
    void featureTogglesTest() {
        // TODO: test featureToggles
    }

    /**
     * Test the property 'featureConfiguration'
     */
    @Test
    void featureConfigurationTest() {
        // TODO: test featureConfiguration
    }

    /**
     * Test the property 'timeFrameRequest'
     */
    @Test
    void timeFrameRequestTest() {
        // TODO: test timeFrameRequest
    }

}
