/*
 * Portfolio Management API
 * API documentation for the Asset Management Portfolio application
 *
 * The version of the OpenAPI document: v1.0
 * Contact: portfolio-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BrokerPortfolioSummary
 */
class BrokerPortfolioSummaryTest {
    private final BrokerPortfolioSummary model = new BrokerPortfolioSummary();

    /**
     * Model tests for BrokerPortfolioSummary
     */
    @Test
    void testBrokerPortfolioSummary() {
        // TODO: test BrokerPortfolioSummary
    }

    /**
     * Test the property 'investmentValue'
     */
    @Test
    void investmentValueTest() {
        // TODO: test investmentValue
    }

    /**
     * Test the property 'currentValue'
     */
    @Test
    void currentValueTest() {
        // TODO: test currentValue
    }

    /**
     * Test the property 'totalGainLoss'
     */
    @Test
    void totalGainLossTest() {
        // TODO: test totalGainLoss
    }

    /**
     * Test the property 'totalGainLossPercentage'
     */
    @Test
    void totalGainLossPercentageTest() {
        // TODO: test totalGainLossPercentage
    }

    /**
     * Test the property 'todayGainLoss'
     */
    @Test
    void todayGainLossTest() {
        // TODO: test todayGainLoss
    }

    /**
     * Test the property 'todayGainLossPercentage'
     */
    @Test
    void todayGainLossPercentageTest() {
        // TODO: test todayGainLossPercentage
    }

    /**
     * Test the property 'totalAssets'
     */
    @Test
    void totalAssetsTest() {
        // TODO: test totalAssets
    }

    /**
     * Test the property 'gainersCount'
     */
    @Test
    void gainersCountTest() {
        // TODO: test gainersCount
    }

    /**
     * Test the property 'losersCount'
     */
    @Test
    void losersCountTest() {
        // TODO: test losersCount
    }

    /**
     * Test the property 'todayGainersCount'
     */
    @Test
    void todayGainersCountTest() {
        // TODO: test todayGainersCount
    }

    /**
     * Test the property 'todayLosersCount'
     */
    @Test
    void todayLosersCountTest() {
        // TODO: test todayLosersCount
    }

    /**
     * Test the property 'lastUpdated'
     */
    @Test
    void lastUpdatedTest() {
        // TODO: test lastUpdated
    }

    /**
     * Test the property 'brokerType'
     */
    @Test
    void brokerTypeTest() {
        // TODO: test brokerType
    }

}
