/*
 * Portfolio Management API
 * API documentation for the Asset Management Portfolio application
 *
 * The version of the OpenAPI document: v1.0
 * Contact: portfolio-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CapSegment
 */
class CapSegmentTest {
    private final CapSegment model = new CapSegment();

    /**
     * Model tests for CapSegment
     */
    @Test
    void testCapSegment() {
        // TODO: test CapSegment
    }

    /**
     * Test the property 'segmentName'
     */
    @Test
    void segmentNameTest() {
        // TODO: test segmentName
    }

    /**
     * Test the property 'weightPercentage'
     */
    @Test
    void weightPercentageTest() {
        // TODO: test weightPercentage
    }

    /**
     * Test the property 'segmentValue'
     */
    @Test
    void segmentValueTest() {
        // TODO: test segmentValue
    }

    /**
     * Test the property 'numberOfStocks'
     */
    @Test
    void numberOfStocksTest() {
        // TODO: test numberOfStocks
    }

    /**
     * Test the property 'topStocks'
     */
    @Test
    void topStocksTest() {
        // TODO: test topStocks
    }

}
