/*
 * Portfolio Management API
 * API documentation for the Asset Management Portfolio application
 *
 * The version of the OpenAPI document: v1.0
 * Contact: portfolio-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ChartPaths
 */
class ChartPathsTest {
    private final ChartPaths model = new ChartPaths();

    /**
     * Model tests for ChartPaths
     */
    @Test
    void testChartPaths() {
        // TODO: test ChartPaths
    }

    /**
     * Test the property 'chart365dPath'
     */
    @Test
    void chart365dPathTest() {
        // TODO: test chart365dPath
    }

    /**
     * Test the property 'chart30dPath'
     */
    @Test
    void chart30dPathTest() {
        // TODO: test chart30dPath
    }

    /**
     * Test the property 'chartTodayPath'
     */
    @Test
    void chartTodayPathTest() {
        // TODO: test chartTodayPath
    }

}
