/*
 * Portfolio Management API
 * API documentation for the Asset Management Portfolio application
 *
 * The version of the OpenAPI document: v1.0
 * Contact: portfolio-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.model;

import com.am.portfolio.client.model.MarketDataModel;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EquityModel
 */
class EquityModelTest {
    private final EquityModel model = new EquityModel();

    /**
     * Model tests for EquityModel
     */
    @Test
    void testEquityModel() {
        // TODO: test EquityModel
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'symbol'
     */
    @Test
    void symbolTest() {
        // TODO: test symbol
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'description'
     */
    @Test
    void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'assetType'
     */
    @Test
    void assetTypeTest() {
        // TODO: test assetType
    }

    /**
     * Test the property 'marketData'
     */
    @Test
    void marketDataTest() {
        // TODO: test marketData
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    void quantityTest() {
        // TODO: test quantity
    }

    /**
     * Test the property 'avgBuyingPrice'
     */
    @Test
    void avgBuyingPriceTest() {
        // TODO: test avgBuyingPrice
    }

    /**
     * Test the property 'currentValue'
     */
    @Test
    void currentValueTest() {
        // TODO: test currentValue
    }

    /**
     * Test the property 'investmentValue'
     */
    @Test
    void investmentValueTest() {
        // TODO: test investmentValue
    }

    /**
     * Test the property 'brokerType'
     */
    @Test
    void brokerTypeTest() {
        // TODO: test brokerType
    }

    /**
     * Test the property 'profitLoss'
     */
    @Test
    void profitLossTest() {
        // TODO: test profitLoss
    }

    /**
     * Test the property 'profitLossPercentage'
     */
    @Test
    void profitLossPercentageTest() {
        // TODO: test profitLossPercentage
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'isActive'
     */
    @Test
    void isActiveTest() {
        // TODO: test isActive
    }

    /**
     * Test the property 'isin'
     */
    @Test
    void isinTest() {
        // TODO: test isin
    }

    /**
     * Test the property 'companyName'
     */
    @Test
    void companyNameTest() {
        // TODO: test companyName
    }

    /**
     * Test the property 'sector'
     */
    @Test
    void sectorTest() {
        // TODO: test sector
    }

    /**
     * Test the property 'industry'
     */
    @Test
    void industryTest() {
        // TODO: test industry
    }

    /**
     * Test the property 'marketCap'
     */
    @Test
    void marketCapTest() {
        // TODO: test marketCap
    }

    /**
     * Test the property 'exchange'
     */
    @Test
    void exchangeTest() {
        // TODO: test exchange
    }

    /**
     * Test the property 'peRatio'
     */
    @Test
    void peRatioTest() {
        // TODO: test peRatio
    }

    /**
     * Test the property 'pbRatio'
     */
    @Test
    void pbRatioTest() {
        // TODO: test pbRatio
    }

    /**
     * Test the property 'dividendYield'
     */
    @Test
    void dividendYieldTest() {
        // TODO: test dividendYield
    }

    /**
     * Test the property 'eps'
     */
    @Test
    void epsTest() {
        // TODO: test eps
    }

    /**
     * Test the property 'sharesOutstanding'
     */
    @Test
    void sharesOutstandingTest() {
        // TODO: test sharesOutstanding
    }

    /**
     * Test the property 'stockType'
     */
    @Test
    void stockTypeTest() {
        // TODO: test stockType
    }

    /**
     * Test the property 'countryOfIncorporation'
     */
    @Test
    void countryOfIncorporationTest() {
        // TODO: test countryOfIncorporation
    }

}
