/*
 * Portfolio Management API
 * API documentation for the Asset Management Portfolio application
 *
 * The version of the OpenAPI document: v1.0
 * Contact: portfolio-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FeatureToggles
 */
class FeatureTogglesTest {
    private final FeatureToggles model = new FeatureToggles();

    /**
     * Model tests for FeatureToggles
     */
    @Test
    void testFeatureToggles() {
        // TODO: test FeatureToggles
    }

    /**
     * Test the property 'includeHeatmap'
     */
    @Test
    void includeHeatmapTest() {
        // TODO: test includeHeatmap
    }

    /**
     * Test the property 'includeMovers'
     */
    @Test
    void includeMoversTest() {
        // TODO: test includeMovers
    }

    /**
     * Test the property 'includeSectorAllocation'
     */
    @Test
    void includeSectorAllocationTest() {
        // TODO: test includeSectorAllocation
    }

    /**
     * Test the property 'includeMarketCapAllocation'
     */
    @Test
    void includeMarketCapAllocationTest() {
        // TODO: test includeMarketCapAllocation
    }

}
