/*
 * Portfolio Management API
 * API documentation for the Asset Management Portfolio application
 *
 * The version of the OpenAPI document: v1.0
 * Contact: portfolio-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FundamentalRatios
 */
class FundamentalRatiosTest {
    private final FundamentalRatios model = new FundamentalRatios();

    /**
     * Model tests for FundamentalRatios
     */
    @Test
    void testFundamentalRatios() {
        // TODO: test FundamentalRatios
    }

    /**
     * Test the property 'priceToEarningRation'
     */
    @Test
    void priceToEarningRationTest() {
        // TODO: test priceToEarningRation
    }

    /**
     * Test the property 'priceToBookRation'
     */
    @Test
    void priceToBookRationTest() {
        // TODO: test priceToBookRation
    }

    /**
     * Test the property 'dividenYield'
     */
    @Test
    void dividenYieldTest() {
        // TODO: test dividenYield
    }

}
