/*
 * Portfolio Management API
 * API documentation for the Asset Management Portfolio application
 *
 * The version of the OpenAPI document: v1.0
 * Contact: portfolio-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for HistoricalComparison
 */
class HistoricalComparisonTest {
    private final HistoricalComparison model = new HistoricalComparison();

    /**
     * Model tests for HistoricalComparison
     */
    @Test
    void testHistoricalComparison() {
        // TODO: test HistoricalComparison
    }

    /**
     * Test the property 'value'
     */
    @Test
    void valueTest() {
        // TODO: test value
    }

    /**
     * Test the property 'perChange365d'
     */
    @Test
    void perChange365dTest() {
        // TODO: test perChange365d
    }

    /**
     * Test the property 'date365dAgo'
     */
    @Test
    void date365dAgoTest() {
        // TODO: test date365dAgo
    }

    /**
     * Test the property 'perChange30d'
     */
    @Test
    void perChange30dTest() {
        // TODO: test perChange30d
    }

    /**
     * Test the property 'date30dAgo'
     */
    @Test
    void date30dAgoTest() {
        // TODO: test date30dAgo
    }

    /**
     * Test the property 'previousDay'
     */
    @Test
    void previousDayTest() {
        // TODO: test previousDay
    }

    /**
     * Test the property 'oneWeekAgo'
     */
    @Test
    void oneWeekAgoTest() {
        // TODO: test oneWeekAgo
    }

    /**
     * Test the property 'oneMonthAgo'
     */
    @Test
    void oneMonthAgoTest() {
        // TODO: test oneMonthAgo
    }

    /**
     * Test the property 'oneYearAgo'
     */
    @Test
    void oneYearAgoTest() {
        // TODO: test oneYearAgo
    }

}
