/*
 * Portfolio Management API
 * API documentation for the Asset Management Portfolio application
 *
 * The version of the OpenAPI document: v1.0
 * Contact: portfolio-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MarketData
 */
class MarketDataTest {
    private final MarketData model = new MarketData();

    /**
     * Model tests for MarketData
     */
    @Test
    void testMarketData() {
        // TODO: test MarketData
    }

    /**
     * Test the property 'last'
     */
    @Test
    void lastTest() {
        // TODO: test last
    }

    /**
     * Test the property 'variation'
     */
    @Test
    void variationTest() {
        // TODO: test variation
    }

    /**
     * Test the property 'percentChange'
     */
    @Test
    void percentChangeTest() {
        // TODO: test percentChange
    }

    /**
     * Test the property 'open'
     */
    @Test
    void openTest() {
        // TODO: test open
    }

    /**
     * Test the property 'high'
     */
    @Test
    void highTest() {
        // TODO: test high
    }

    /**
     * Test the property 'low'
     */
    @Test
    void lowTest() {
        // TODO: test low
    }

    /**
     * Test the property 'previousClose'
     */
    @Test
    void previousCloseTest() {
        // TODO: test previousClose
    }

    /**
     * Test the property 'yearHigh'
     */
    @Test
    void yearHighTest() {
        // TODO: test yearHigh
    }

    /**
     * Test the property 'yearLow'
     */
    @Test
    void yearLowTest() {
        // TODO: test yearLow
    }

    /**
     * Test the property 'indicativeClose'
     */
    @Test
    void indicativeCloseTest() {
        // TODO: test indicativeClose
    }

}
