/*
 * Portfolio Management API
 * API documentation for the Asset Management Portfolio application
 *
 * The version of the OpenAPI document: v1.0
 * Contact: portfolio-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.model;

import com.am.portfolio.client.model.OHLCVModel;
import com.am.portfolio.client.model.TimeSeriesDataModel;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MarketDataModel
 */
class MarketDataModelTest {
    private final MarketDataModel model = new MarketDataModel();

    /**
     * Model tests for MarketDataModel
     */
    @Test
    void testMarketDataModel() {
        // TODO: test MarketDataModel
    }

    /**
     * Test the property 'latestOHLCV'
     */
    @Test
    void latestOHLCVTest() {
        // TODO: test latestOHLCV
    }

    /**
     * Test the property 'marketPrice'
     */
    @Test
    void marketPriceTest() {
        // TODO: test marketPrice
    }

    /**
     * Test the property 'dayHigh'
     */
    @Test
    void dayHighTest() {
        // TODO: test dayHigh
    }

    /**
     * Test the property 'dayLow'
     */
    @Test
    void dayLowTest() {
        // TODO: test dayLow
    }

    /**
     * Test the property 'fiftyTwoWeekHigh'
     */
    @Test
    void fiftyTwoWeekHighTest() {
        // TODO: test fiftyTwoWeekHigh
    }

    /**
     * Test the property 'fiftyTwoWeekLow'
     */
    @Test
    void fiftyTwoWeekLowTest() {
        // TODO: test fiftyTwoWeekLow
    }

    /**
     * Test the property 'previousClose'
     */
    @Test
    void previousCloseTest() {
        // TODO: test previousClose
    }

    /**
     * Test the property 'volume'
     */
    @Test
    void volumeTest() {
        // TODO: test volume
    }

    /**
     * Test the property 'marketCap'
     */
    @Test
    void marketCapTest() {
        // TODO: test marketCap
    }

    /**
     * Test the property 'marketCapCategory'
     */
    @Test
    void marketCapCategoryTest() {
        // TODO: test marketCapCategory
    }

    /**
     * Test the property 'priceInHomeCurrency'
     */
    @Test
    void priceInHomeCurrencyTest() {
        // TODO: test priceInHomeCurrency
    }

    /**
     * Test the property 'relativeStrengthIndex'
     */
    @Test
    void relativeStrengthIndexTest() {
        // TODO: test relativeStrengthIndex
    }

    /**
     * Test the property 'movingAverage50'
     */
    @Test
    void movingAverage50Test() {
        // TODO: test movingAverage50
    }

    /**
     * Test the property 'movingAverage200'
     */
    @Test
    void movingAverage200Test() {
        // TODO: test movingAverage200
    }

    /**
     * Test the property 'averageVolume30Days'
     */
    @Test
    void averageVolume30DaysTest() {
        // TODO: test averageVolume30Days
    }

    /**
     * Test the property 'beta'
     */
    @Test
    void betaTest() {
        // TODO: test beta
    }

    /**
     * Test the property 'volatility30Days'
     */
    @Test
    void volatility30DaysTest() {
        // TODO: test volatility30Days
    }

    /**
     * Test the property 'bidPrice'
     */
    @Test
    void bidPriceTest() {
        // TODO: test bidPrice
    }

    /**
     * Test the property 'askPrice'
     */
    @Test
    void askPriceTest() {
        // TODO: test askPrice
    }

    /**
     * Test the property 'bidSize'
     */
    @Test
    void bidSizeTest() {
        // TODO: test bidSize
    }

    /**
     * Test the property 'askSize'
     */
    @Test
    void askSizeTest() {
        // TODO: test askSize
    }

    /**
     * Test the property 'spreadPercentage'
     */
    @Test
    void spreadPercentageTest() {
        // TODO: test spreadPercentage
    }

    /**
     * Test the property 'timeSeriesData'
     */
    @Test
    void timeSeriesDataTest() {
        // TODO: test timeSeriesData
    }

}
