/*
 * Portfolio Management API
 * API documentation for the Asset Management Portfolio application
 *
 * The version of the OpenAPI document: v1.0
 * Contact: portfolio-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.model;

import com.am.portfolio.client.model.ChartPaths;
import com.am.portfolio.client.model.FundamentalRatios;
import com.am.portfolio.client.model.HistoricalComparison;
import com.am.portfolio.client.model.MarketBreadth;
import com.am.portfolio.client.model.MarketData;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MarketIndexIndices
 */
class MarketIndexIndicesTest {
    private final MarketIndexIndices model = new MarketIndexIndices();

    /**
     * Model tests for MarketIndexIndices
     */
    @Test
    void testMarketIndexIndices() {
        // TODO: test MarketIndexIndices
    }

    /**
     * Test the property 'key'
     */
    @Test
    void keyTest() {
        // TODO: test key
    }

    /**
     * Test the property 'index'
     */
    @Test
    void indexTest() {
        // TODO: test index
    }

    /**
     * Test the property 'indexSymbol'
     */
    @Test
    void indexSymbolTest() {
        // TODO: test indexSymbol
    }

    /**
     * Test the property 'marketData'
     */
    @Test
    void marketDataTest() {
        // TODO: test marketData
    }

    /**
     * Test the property 'fundamentalRatios'
     */
    @Test
    void fundamentalRatiosTest() {
        // TODO: test fundamentalRatios
    }

    /**
     * Test the property 'marketBreadth'
     */
    @Test
    void marketBreadthTest() {
        // TODO: test marketBreadth
    }

    /**
     * Test the property 'historicalComparison'
     */
    @Test
    void historicalComparisonTest() {
        // TODO: test historicalComparison
    }

    /**
     * Test the property 'chartPaths'
     */
    @Test
    void chartPathsTest() {
        // TODO: test chartPaths
    }

    /**
     * Test the property 'timestamp'
     */
    @Test
    void timestampTest() {
        // TODO: test timestamp
    }

}
