/*
 * Portfolio Management API
 * API documentation for the Asset Management Portfolio application
 *
 * The version of the OpenAPI document: v1.0
 * Contact: portfolio-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.model;

import com.am.portfolio.client.model.CapSegment;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MarketCapAllocation
 */
class MarketCapAllocationTest {
    private final MarketCapAllocation model = new MarketCapAllocation();

    /**
     * Model tests for MarketCapAllocation
     */
    @Test
    void testMarketCapAllocation() {
        // TODO: test MarketCapAllocation
    }

    /**
     * Test the property 'segments'
     */
    @Test
    void segmentsTest() {
        // TODO: test segments
    }

}
