/*
 * Portfolio Management API
 * API documentation for the Asset Management Portfolio application
 *
 * The version of the OpenAPI document: v1.0
 * Contact: portfolio-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MarketBreadth
 */
class MarketBreadthTest {
    private final MarketBreadth model = new MarketBreadth();

    /**
     * Model tests for MarketBreadth
     */
    @Test
    void testMarketBreadth() {
        // TODO: test MarketBreadth
    }

    /**
     * Test the property 'declines'
     */
    @Test
    void declinesTest() {
        // TODO: test declines
    }

    /**
     * Test the property 'advances'
     */
    @Test
    void advancesTest() {
        // TODO: test advances
    }

    /**
     * Test the property 'unchanged'
     */
    @Test
    void unchangedTest() {
        // TODO: test unchanged
    }

}
