/*
 * Portfolio Management API
 * API documentation for the Asset Management Portfolio application
 *
 * The version of the OpenAPI document: v1.0
 * Contact: portfolio-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PaginationRequest
 */
class PaginationRequestTest {
    private final PaginationRequest model = new PaginationRequest();

    /**
     * Model tests for PaginationRequest
     */
    @Test
    void testPaginationRequest() {
        // TODO: test PaginationRequest
    }

    /**
     * Test the property 'page'
     */
    @Test
    void pageTest() {
        // TODO: test page
    }

    /**
     * Test the property 'size'
     */
    @Test
    void sizeTest() {
        // TODO: test size
    }

    /**
     * Test the property 'sortBy'
     */
    @Test
    void sortByTest() {
        // TODO: test sortBy
    }

    /**
     * Test the property 'sortDirection'
     */
    @Test
    void sortDirectionTest() {
        // TODO: test sortDirection
    }

    /**
     * Test the property 'returnAllData'
     */
    @Test
    void returnAllDataTest() {
        // TODO: test returnAllData
    }

}
