/*
 * Portfolio Management API
 * API documentation for the Asset Management Portfolio application
 *
 * The version of the OpenAPI document: v1.0
 * Contact: portfolio-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PerformanceMetrics
 */
class PerformanceMetricsTest {
    private final PerformanceMetrics model = new PerformanceMetrics();

    /**
     * Model tests for PerformanceMetrics
     */
    @Test
    void testPerformanceMetrics() {
        // TODO: test PerformanceMetrics
    }

    /**
     * Test the property 'indexPerformancePercent'
     */
    @Test
    void indexPerformancePercentTest() {
        // TODO: test indexPerformancePercent
    }

    /**
     * Test the property 'comparisonIndexPerformancePercent'
     */
    @Test
    void comparisonIndexPerformancePercentTest() {
        // TODO: test comparisonIndexPerformancePercent
    }

    /**
     * Test the property 'relativePerformancePercent'
     */
    @Test
    void relativePerformancePercentTest() {
        // TODO: test relativePerformancePercent
    }

    /**
     * Test the property 'volatility'
     */
    @Test
    void volatilityTest() {
        // TODO: test volatility
    }

    /**
     * Test the property 'maxDrawdownPercent'
     */
    @Test
    void maxDrawdownPercentTest() {
        // TODO: test maxDrawdownPercent
    }

    /**
     * Test the property 'bestPerformingSector'
     */
    @Test
    void bestPerformingSectorTest() {
        // TODO: test bestPerformingSector
    }

    /**
     * Test the property 'worstPerformingSector'
     */
    @Test
    void worstPerformingSectorTest() {
        // TODO: test worstPerformingSector
    }

}
