/*
 * Portfolio Management API
 * API documentation for the Asset Management Portfolio application
 *
 * The version of the OpenAPI document: v1.0
 * Contact: portfolio-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.model;

import com.am.portfolio.client.model.IndustryWeight;
import com.am.portfolio.client.model.SectorWeight;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SectorAllocation
 */
class SectorAllocationTest {
    private final SectorAllocation model = new SectorAllocation();

    /**
     * Model tests for SectorAllocation
     */
    @Test
    void testSectorAllocation() {
        // TODO: test SectorAllocation
    }

    /**
     * Test the property 'sectorWeights'
     */
    @Test
    void sectorWeightsTest() {
        // TODO: test sectorWeights
    }

    /**
     * Test the property 'industryWeights'
     */
    @Test
    void industryWeightsTest() {
        // TODO: test industryWeights
    }

}
