/*
 * Portfolio Management API
 * API documentation for the Asset Management Portfolio application
 *
 * The version of the OpenAPI document: v1.0
 * Contact: portfolio-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for StockMovement
 */
class StockMovementTest {
    private final StockMovement model = new StockMovement();

    /**
     * Model tests for StockMovement
     */
    @Test
    void testStockMovement() {
        // TODO: test StockMovement
    }

    /**
     * Test the property 'symbol'
     */
    @Test
    void symbolTest() {
        // TODO: test symbol
    }

    /**
     * Test the property 'companyName'
     */
    @Test
    void companyNameTest() {
        // TODO: test companyName
    }

    /**
     * Test the property 'lastPrice'
     */
    @Test
    void lastPriceTest() {
        // TODO: test lastPrice
    }

    /**
     * Test the property 'changeAmount'
     */
    @Test
    void changeAmountTest() {
        // TODO: test changeAmount
    }

    /**
     * Test the property 'changePercent'
     */
    @Test
    void changePercentTest() {
        // TODO: test changePercent
    }

    /**
     * Test the property 'sector'
     */
    @Test
    void sectorTest() {
        // TODO: test sector
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    void quantityTest() {
        // TODO: test quantity
    }

    /**
     * Test the property 'marketValue'
     */
    @Test
    void marketValueTest() {
        // TODO: test marketValue
    }

    /**
     * Test the property 'weightPercentage'
     */
    @Test
    void weightPercentageTest() {
        // TODO: test weightPercentage
    }

}
