/*
 * Portfolio Management API
 * API documentation for the Asset Management Portfolio application
 *
 * The version of the OpenAPI document: v1.0
 * Contact: portfolio-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.model;

import com.am.portfolio.client.model.OHLCVModel;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TimeSeriesDataModel
 */
class TimeSeriesDataModelTest {
    private final TimeSeriesDataModel model = new TimeSeriesDataModel();

    /**
     * Model tests for TimeSeriesDataModel
     */
    @Test
    void testTimeSeriesDataModel() {
        // TODO: test TimeSeriesDataModel
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'timestamp'
     */
    @Test
    void timestampTest() {
        // TODO: test timestamp
    }

    /**
     * Test the property 'timeframe'
     */
    @Test
    void timeframeTest() {
        // TODO: test timeframe
    }

    /**
     * Test the property 'ohlcv'
     */
    @Test
    void ohlcvTest() {
        // TODO: test ohlcv
    }

    /**
     * Test the property 'latestFiveMin'
     */
    @Test
    void latestFiveMinTest() {
        // TODO: test latestFiveMin
    }

    /**
     * Test the property 'latestFifteenMin'
     */
    @Test
    void latestFifteenMinTest() {
        // TODO: test latestFifteenMin
    }

    /**
     * Test the property 'latestHourly'
     */
    @Test
    void latestHourlyTest() {
        // TODO: test latestHourly
    }

    /**
     * Test the property 'latestDaily'
     */
    @Test
    void latestDailyTest() {
        // TODO: test latestDaily
    }

    /**
     * Test the property 'latestWeekly'
     */
    @Test
    void latestWeeklyTest() {
        // TODO: test latestWeekly
    }

    /**
     * Test the property 'latestMonthly'
     */
    @Test
    void latestMonthlyTest() {
        // TODO: test latestMonthly
    }

    /**
     * Test the property 'latestYearly'
     */
    @Test
    void latestYearlyTest() {
        // TODO: test latestYearly
    }

    /**
     * Test the property 'volume'
     */
    @Test
    void volumeTest() {
        // TODO: test volume
    }

    /**
     * Test the property 'openInterest'
     */
    @Test
    void openInterestTest() {
        // TODO: test openInterest
    }

    /**
     * Test the property 'volatility'
     */
    @Test
    void volatilityTest() {
        // TODO: test volatility
    }

    /**
     * Test the property 'relativeStrengthIndex'
     */
    @Test
    void relativeStrengthIndexTest() {
        // TODO: test relativeStrengthIndex
    }

    /**
     * Test the property 'movingAverage50'
     */
    @Test
    void movingAverage50Test() {
        // TODO: test movingAverage50
    }

    /**
     * Test the property 'movingAverage200'
     */
    @Test
    void movingAverage200Test() {
        // TODO: test movingAverage200
    }

    /**
     * Test the property 'bollingerUpperBand'
     */
    @Test
    void bollingerUpperBandTest() {
        // TODO: test bollingerUpperBand
    }

    /**
     * Test the property 'bollingerLowerBand'
     */
    @Test
    void bollingerLowerBandTest() {
        // TODO: test bollingerLowerBand
    }

    /**
     * Test the property 'macdLine'
     */
    @Test
    void macdLineTest() {
        // TODO: test macdLine
    }

    /**
     * Test the property 'macdSignalLine'
     */
    @Test
    void macdSignalLineTest() {
        // TODO: test macdSignalLine
    }

    /**
     * Test the property 'macdHistogram'
     */
    @Test
    void macdHistogramTest() {
        // TODO: test macdHistogram
    }

}
