/*
 * Portfolio Management API
 * API documentation for the Asset Management Portfolio application
 *
 * The version of the OpenAPI document: v1.0
 * Contact: portfolio-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.am.portfolio.client.model.AnalyticsComponent;
import com.am.portfolio.client.model.PerformanceMetrics;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.portfolio.client.invoker.ApiClient;
/**
 * AdvancedAnalyticsResponse
 */
@JsonPropertyOrder({
  AdvancedAnalyticsResponse.JSON_PROPERTY_PORTFOLIO_ID,
  AdvancedAnalyticsResponse.JSON_PROPERTY_INDEX_SYMBOL,
  AdvancedAnalyticsResponse.JSON_PROPERTY_COMPARISON_INDEX_SYMBOL,
  AdvancedAnalyticsResponse.JSON_PROPERTY_START_DATE,
  AdvancedAnalyticsResponse.JSON_PROPERTY_END_DATE,
  AdvancedAnalyticsResponse.JSON_PROPERTY_TIMESTAMP,
  AdvancedAnalyticsResponse.JSON_PROPERTY_ANALYTICS,
  AdvancedAnalyticsResponse.JSON_PROPERTY_PERFORMANCE_METRICS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-26T23:23:15.876134200+05:30[Asia/Calcutta]", comments = "Generator version: 7.20.0")
public class AdvancedAnalyticsResponse {
  public static final String JSON_PROPERTY_PORTFOLIO_ID = "portfolioId";
  @javax.annotation.Nullable
  private String portfolioId;

  public static final String JSON_PROPERTY_INDEX_SYMBOL = "indexSymbol";
  @javax.annotation.Nullable
  private String indexSymbol;

  public static final String JSON_PROPERTY_COMPARISON_INDEX_SYMBOL = "comparisonIndexSymbol";
  @javax.annotation.Nullable
  private String comparisonIndexSymbol;

  public static final String JSON_PROPERTY_START_DATE = "startDate";
  @javax.annotation.Nullable
  private LocalDate startDate;

  public static final String JSON_PROPERTY_END_DATE = "endDate";
  @javax.annotation.Nullable
  private LocalDate endDate;

  public static final String JSON_PROPERTY_TIMESTAMP = "timestamp";
  @javax.annotation.Nullable
  private OffsetDateTime timestamp;

  public static final String JSON_PROPERTY_ANALYTICS = "analytics";
  @javax.annotation.Nullable
  private AnalyticsComponent analytics;

  public static final String JSON_PROPERTY_PERFORMANCE_METRICS = "performanceMetrics";
  @javax.annotation.Nullable
  private PerformanceMetrics performanceMetrics;

  public AdvancedAnalyticsResponse() { 
  }

  public AdvancedAnalyticsResponse portfolioId(@javax.annotation.Nullable String portfolioId) {
    this.portfolioId = portfolioId;
    return this;
  }

  /**
   * Get portfolioId
   * @return portfolioId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PORTFOLIO_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPortfolioId() {
    return portfolioId;
  }


  @JsonProperty(value = JSON_PROPERTY_PORTFOLIO_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPortfolioId(@javax.annotation.Nullable String portfolioId) {
    this.portfolioId = portfolioId;
  }


  public AdvancedAnalyticsResponse indexSymbol(@javax.annotation.Nullable String indexSymbol) {
    this.indexSymbol = indexSymbol;
    return this;
  }

  /**
   * Get indexSymbol
   * @return indexSymbol
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INDEX_SYMBOL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getIndexSymbol() {
    return indexSymbol;
  }


  @JsonProperty(value = JSON_PROPERTY_INDEX_SYMBOL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIndexSymbol(@javax.annotation.Nullable String indexSymbol) {
    this.indexSymbol = indexSymbol;
  }


  public AdvancedAnalyticsResponse comparisonIndexSymbol(@javax.annotation.Nullable String comparisonIndexSymbol) {
    this.comparisonIndexSymbol = comparisonIndexSymbol;
    return this;
  }

  /**
   * Get comparisonIndexSymbol
   * @return comparisonIndexSymbol
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COMPARISON_INDEX_SYMBOL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getComparisonIndexSymbol() {
    return comparisonIndexSymbol;
  }


  @JsonProperty(value = JSON_PROPERTY_COMPARISON_INDEX_SYMBOL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComparisonIndexSymbol(@javax.annotation.Nullable String comparisonIndexSymbol) {
    this.comparisonIndexSymbol = comparisonIndexSymbol;
  }


  public AdvancedAnalyticsResponse startDate(@javax.annotation.Nullable LocalDate startDate) {
    this.startDate = startDate;
    return this;
  }

  /**
   * Get startDate
   * @return startDate
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_START_DATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public LocalDate getStartDate() {
    return startDate;
  }


  @JsonProperty(value = JSON_PROPERTY_START_DATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartDate(@javax.annotation.Nullable LocalDate startDate) {
    this.startDate = startDate;
  }


  public AdvancedAnalyticsResponse endDate(@javax.annotation.Nullable LocalDate endDate) {
    this.endDate = endDate;
    return this;
  }

  /**
   * Get endDate
   * @return endDate
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_END_DATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public LocalDate getEndDate() {
    return endDate;
  }


  @JsonProperty(value = JSON_PROPERTY_END_DATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndDate(@javax.annotation.Nullable LocalDate endDate) {
    this.endDate = endDate;
  }


  public AdvancedAnalyticsResponse timestamp(@javax.annotation.Nullable OffsetDateTime timestamp) {
    this.timestamp = timestamp;
    return this;
  }

  /**
   * Get timestamp
   * @return timestamp
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getTimestamp() {
    return timestamp;
  }


  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimestamp(@javax.annotation.Nullable OffsetDateTime timestamp) {
    this.timestamp = timestamp;
  }


  public AdvancedAnalyticsResponse analytics(@javax.annotation.Nullable AnalyticsComponent analytics) {
    this.analytics = analytics;
    return this;
  }

  /**
   * Get analytics
   * @return analytics
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ANALYTICS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public AnalyticsComponent getAnalytics() {
    return analytics;
  }


  @JsonProperty(value = JSON_PROPERTY_ANALYTICS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAnalytics(@javax.annotation.Nullable AnalyticsComponent analytics) {
    this.analytics = analytics;
  }


  public AdvancedAnalyticsResponse performanceMetrics(@javax.annotation.Nullable PerformanceMetrics performanceMetrics) {
    this.performanceMetrics = performanceMetrics;
    return this;
  }

  /**
   * Get performanceMetrics
   * @return performanceMetrics
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PERFORMANCE_METRICS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public PerformanceMetrics getPerformanceMetrics() {
    return performanceMetrics;
  }


  @JsonProperty(value = JSON_PROPERTY_PERFORMANCE_METRICS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPerformanceMetrics(@javax.annotation.Nullable PerformanceMetrics performanceMetrics) {
    this.performanceMetrics = performanceMetrics;
  }


  /**
   * Return true if this AdvancedAnalyticsResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdvancedAnalyticsResponse advancedAnalyticsResponse = (AdvancedAnalyticsResponse) o;
    return Objects.equals(this.portfolioId, advancedAnalyticsResponse.portfolioId) &&
        Objects.equals(this.indexSymbol, advancedAnalyticsResponse.indexSymbol) &&
        Objects.equals(this.comparisonIndexSymbol, advancedAnalyticsResponse.comparisonIndexSymbol) &&
        Objects.equals(this.startDate, advancedAnalyticsResponse.startDate) &&
        Objects.equals(this.endDate, advancedAnalyticsResponse.endDate) &&
        Objects.equals(this.timestamp, advancedAnalyticsResponse.timestamp) &&
        Objects.equals(this.analytics, advancedAnalyticsResponse.analytics) &&
        Objects.equals(this.performanceMetrics, advancedAnalyticsResponse.performanceMetrics);
  }

  @Override
  public int hashCode() {
    return Objects.hash(portfolioId, indexSymbol, comparisonIndexSymbol, startDate, endDate, timestamp, analytics, performanceMetrics);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdvancedAnalyticsResponse {\n");
    sb.append("    portfolioId: ").append(toIndentedString(portfolioId)).append("\n");
    sb.append("    indexSymbol: ").append(toIndentedString(indexSymbol)).append("\n");
    sb.append("    comparisonIndexSymbol: ").append(toIndentedString(comparisonIndexSymbol)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    analytics: ").append(toIndentedString(analytics)).append("\n");
    sb.append("    performanceMetrics: ").append(toIndentedString(performanceMetrics)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `portfolioId` to the URL query string
    if (getPortfolioId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sportfolioId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPortfolioId()))));
    }

    // add `indexSymbol` to the URL query string
    if (getIndexSymbol() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sindexSymbol%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIndexSymbol()))));
    }

    // add `comparisonIndexSymbol` to the URL query string
    if (getComparisonIndexSymbol() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scomparisonIndexSymbol%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getComparisonIndexSymbol()))));
    }

    // add `startDate` to the URL query string
    if (getStartDate() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstartDate%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStartDate()))));
    }

    // add `endDate` to the URL query string
    if (getEndDate() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sendDate%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEndDate()))));
    }

    // add `timestamp` to the URL query string
    if (getTimestamp() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stimestamp%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTimestamp()))));
    }

    // add `analytics` to the URL query string
    if (getAnalytics() != null) {
      joiner.add(getAnalytics().toUrlQueryString(prefix + "analytics" + suffix));
    }

    // add `performanceMetrics` to the URL query string
    if (getPerformanceMetrics() != null) {
      joiner.add(getPerformanceMetrics().toUrlQueryString(prefix + "performanceMetrics" + suffix));
    }

    return joiner.toString();
  }
}

