/*
 * Portfolio Management API
 * API documentation for the Asset Management Portfolio application
 *
 * The version of the OpenAPI document: v1.0
 * Contact: portfolio-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.am.portfolio.client.model.GainerLoser;
import com.am.portfolio.client.model.Heatmap;
import com.am.portfolio.client.model.MarketCapAllocation;
import com.am.portfolio.client.model.SectorAllocation;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.portfolio.client.invoker.ApiClient;
/**
 * AnalyticsComponent
 */
@JsonPropertyOrder({
  AnalyticsComponent.JSON_PROPERTY_HEATMAP,
  AnalyticsComponent.JSON_PROPERTY_MOVERS,
  AnalyticsComponent.JSON_PROPERTY_SECTOR_ALLOCATION,
  AnalyticsComponent.JSON_PROPERTY_MARKET_CAP_ALLOCATION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-26T23:23:15.876134200+05:30[Asia/Calcutta]", comments = "Generator version: 7.20.0")
public class AnalyticsComponent {
  public static final String JSON_PROPERTY_HEATMAP = "heatmap";
  @javax.annotation.Nullable
  private Heatmap heatmap;

  public static final String JSON_PROPERTY_MOVERS = "movers";
  @javax.annotation.Nullable
  private GainerLoser movers;

  public static final String JSON_PROPERTY_SECTOR_ALLOCATION = "sectorAllocation";
  @javax.annotation.Nullable
  private SectorAllocation sectorAllocation;

  public static final String JSON_PROPERTY_MARKET_CAP_ALLOCATION = "marketCapAllocation";
  @javax.annotation.Nullable
  private MarketCapAllocation marketCapAllocation;

  public AnalyticsComponent() { 
  }

  public AnalyticsComponent heatmap(@javax.annotation.Nullable Heatmap heatmap) {
    this.heatmap = heatmap;
    return this;
  }

  /**
   * Get heatmap
   * @return heatmap
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HEATMAP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Heatmap getHeatmap() {
    return heatmap;
  }


  @JsonProperty(value = JSON_PROPERTY_HEATMAP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHeatmap(@javax.annotation.Nullable Heatmap heatmap) {
    this.heatmap = heatmap;
  }


  public AnalyticsComponent movers(@javax.annotation.Nullable GainerLoser movers) {
    this.movers = movers;
    return this;
  }

  /**
   * Get movers
   * @return movers
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MOVERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public GainerLoser getMovers() {
    return movers;
  }


  @JsonProperty(value = JSON_PROPERTY_MOVERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMovers(@javax.annotation.Nullable GainerLoser movers) {
    this.movers = movers;
  }


  public AnalyticsComponent sectorAllocation(@javax.annotation.Nullable SectorAllocation sectorAllocation) {
    this.sectorAllocation = sectorAllocation;
    return this;
  }

  /**
   * Get sectorAllocation
   * @return sectorAllocation
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SECTOR_ALLOCATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public SectorAllocation getSectorAllocation() {
    return sectorAllocation;
  }


  @JsonProperty(value = JSON_PROPERTY_SECTOR_ALLOCATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSectorAllocation(@javax.annotation.Nullable SectorAllocation sectorAllocation) {
    this.sectorAllocation = sectorAllocation;
  }


  public AnalyticsComponent marketCapAllocation(@javax.annotation.Nullable MarketCapAllocation marketCapAllocation) {
    this.marketCapAllocation = marketCapAllocation;
    return this;
  }

  /**
   * Get marketCapAllocation
   * @return marketCapAllocation
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MARKET_CAP_ALLOCATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public MarketCapAllocation getMarketCapAllocation() {
    return marketCapAllocation;
  }


  @JsonProperty(value = JSON_PROPERTY_MARKET_CAP_ALLOCATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMarketCapAllocation(@javax.annotation.Nullable MarketCapAllocation marketCapAllocation) {
    this.marketCapAllocation = marketCapAllocation;
  }


  /**
   * Return true if this AnalyticsComponent object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AnalyticsComponent analyticsComponent = (AnalyticsComponent) o;
    return Objects.equals(this.heatmap, analyticsComponent.heatmap) &&
        Objects.equals(this.movers, analyticsComponent.movers) &&
        Objects.equals(this.sectorAllocation, analyticsComponent.sectorAllocation) &&
        Objects.equals(this.marketCapAllocation, analyticsComponent.marketCapAllocation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(heatmap, movers, sectorAllocation, marketCapAllocation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AnalyticsComponent {\n");
    sb.append("    heatmap: ").append(toIndentedString(heatmap)).append("\n");
    sb.append("    movers: ").append(toIndentedString(movers)).append("\n");
    sb.append("    sectorAllocation: ").append(toIndentedString(sectorAllocation)).append("\n");
    sb.append("    marketCapAllocation: ").append(toIndentedString(marketCapAllocation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `heatmap` to the URL query string
    if (getHeatmap() != null) {
      joiner.add(getHeatmap().toUrlQueryString(prefix + "heatmap" + suffix));
    }

    // add `movers` to the URL query string
    if (getMovers() != null) {
      joiner.add(getMovers().toUrlQueryString(prefix + "movers" + suffix));
    }

    // add `sectorAllocation` to the URL query string
    if (getSectorAllocation() != null) {
      joiner.add(getSectorAllocation().toUrlQueryString(prefix + "sectorAllocation" + suffix));
    }

    // add `marketCapAllocation` to the URL query string
    if (getMarketCapAllocation() != null) {
      joiner.add(getMarketCapAllocation().toUrlQueryString(prefix + "marketCapAllocation" + suffix));
    }

    return joiner.toString();
  }
}

