/*
 * Portfolio Management API
 * API documentation for the Asset Management Portfolio application
 *
 * The version of the OpenAPI document: v1.0
 * Contact: portfolio-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.portfolio.client.invoker.ApiClient;
/**
 * ChartPaths
 */
@JsonPropertyOrder({
  ChartPaths.JSON_PROPERTY_CHART365D_PATH,
  ChartPaths.JSON_PROPERTY_CHART30D_PATH,
  ChartPaths.JSON_PROPERTY_CHART_TODAY_PATH
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-26T23:23:15.876134200+05:30[Asia/Calcutta]", comments = "Generator version: 7.20.0")
public class ChartPaths {
  public static final String JSON_PROPERTY_CHART365D_PATH = "chart365dPath";
  @javax.annotation.Nullable
  private String chart365dPath;

  public static final String JSON_PROPERTY_CHART30D_PATH = "chart30dPath";
  @javax.annotation.Nullable
  private String chart30dPath;

  public static final String JSON_PROPERTY_CHART_TODAY_PATH = "chartTodayPath";
  @javax.annotation.Nullable
  private String chartTodayPath;

  public ChartPaths() { 
  }

  public ChartPaths chart365dPath(@javax.annotation.Nullable String chart365dPath) {
    this.chart365dPath = chart365dPath;
    return this;
  }

  /**
   * Get chart365dPath
   * @return chart365dPath
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CHART365D_PATH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getChart365dPath() {
    return chart365dPath;
  }


  @JsonProperty(value = JSON_PROPERTY_CHART365D_PATH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChart365dPath(@javax.annotation.Nullable String chart365dPath) {
    this.chart365dPath = chart365dPath;
  }


  public ChartPaths chart30dPath(@javax.annotation.Nullable String chart30dPath) {
    this.chart30dPath = chart30dPath;
    return this;
  }

  /**
   * Get chart30dPath
   * @return chart30dPath
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CHART30D_PATH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getChart30dPath() {
    return chart30dPath;
  }


  @JsonProperty(value = JSON_PROPERTY_CHART30D_PATH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChart30dPath(@javax.annotation.Nullable String chart30dPath) {
    this.chart30dPath = chart30dPath;
  }


  public ChartPaths chartTodayPath(@javax.annotation.Nullable String chartTodayPath) {
    this.chartTodayPath = chartTodayPath;
    return this;
  }

  /**
   * Get chartTodayPath
   * @return chartTodayPath
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CHART_TODAY_PATH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getChartTodayPath() {
    return chartTodayPath;
  }


  @JsonProperty(value = JSON_PROPERTY_CHART_TODAY_PATH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChartTodayPath(@javax.annotation.Nullable String chartTodayPath) {
    this.chartTodayPath = chartTodayPath;
  }


  /**
   * Return true if this ChartPaths object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChartPaths chartPaths = (ChartPaths) o;
    return Objects.equals(this.chart365dPath, chartPaths.chart365dPath) &&
        Objects.equals(this.chart30dPath, chartPaths.chart30dPath) &&
        Objects.equals(this.chartTodayPath, chartPaths.chartTodayPath);
  }

  @Override
  public int hashCode() {
    return Objects.hash(chart365dPath, chart30dPath, chartTodayPath);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChartPaths {\n");
    sb.append("    chart365dPath: ").append(toIndentedString(chart365dPath)).append("\n");
    sb.append("    chart30dPath: ").append(toIndentedString(chart30dPath)).append("\n");
    sb.append("    chartTodayPath: ").append(toIndentedString(chartTodayPath)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `chart365dPath` to the URL query string
    if (getChart365dPath() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%schart365dPath%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getChart365dPath()))));
    }

    // add `chart30dPath` to the URL query string
    if (getChart30dPath() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%schart30dPath%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getChart30dPath()))));
    }

    // add `chartTodayPath` to the URL query string
    if (getChartTodayPath() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%schartTodayPath%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getChartTodayPath()))));
    }

    return joiner.toString();
  }
}

