/*
 * Portfolio Management API
 * API documentation for the Asset Management Portfolio application
 *
 * The version of the OpenAPI document: v1.0
 * Contact: portfolio-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.portfolio.client.invoker.ApiClient;
/**
 * FeatureConfiguration
 */
@JsonPropertyOrder({
  FeatureConfiguration.JSON_PROPERTY_MOVERS_LIMIT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-26T23:23:15.876134200+05:30[Asia/Calcutta]", comments = "Generator version: 7.20.0")
public class FeatureConfiguration {
  public static final String JSON_PROPERTY_MOVERS_LIMIT = "moversLimit";
  @javax.annotation.Nullable
  private Integer moversLimit;

  public FeatureConfiguration() { 
  }

  public FeatureConfiguration moversLimit(@javax.annotation.Nullable Integer moversLimit) {
    this.moversLimit = moversLimit;
    return this;
  }

  /**
   * Get moversLimit
   * minimum: 1
   * @return moversLimit
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MOVERS_LIMIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getMoversLimit() {
    return moversLimit;
  }


  @JsonProperty(value = JSON_PROPERTY_MOVERS_LIMIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMoversLimit(@javax.annotation.Nullable Integer moversLimit) {
    this.moversLimit = moversLimit;
  }


  /**
   * Return true if this FeatureConfiguration object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FeatureConfiguration featureConfiguration = (FeatureConfiguration) o;
    return Objects.equals(this.moversLimit, featureConfiguration.moversLimit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(moversLimit);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FeatureConfiguration {\n");
    sb.append("    moversLimit: ").append(toIndentedString(moversLimit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `moversLimit` to the URL query string
    if (getMoversLimit() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smoversLimit%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMoversLimit()))));
    }

    return joiner.toString();
  }
}

