/*
 * Portfolio Management API
 * API documentation for the Asset Management Portfolio application
 *
 * The version of the OpenAPI document: v1.0
 * Contact: portfolio-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.portfolio.client.invoker.ApiClient;
/**
 * FeatureToggles
 */
@JsonPropertyOrder({
  FeatureToggles.JSON_PROPERTY_INCLUDE_HEATMAP,
  FeatureToggles.JSON_PROPERTY_INCLUDE_MOVERS,
  FeatureToggles.JSON_PROPERTY_INCLUDE_SECTOR_ALLOCATION,
  FeatureToggles.JSON_PROPERTY_INCLUDE_MARKET_CAP_ALLOCATION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-26T23:23:15.876134200+05:30[Asia/Calcutta]", comments = "Generator version: 7.20.0")
public class FeatureToggles {
  public static final String JSON_PROPERTY_INCLUDE_HEATMAP = "includeHeatmap";
  @javax.annotation.Nullable
  private Boolean includeHeatmap;

  public static final String JSON_PROPERTY_INCLUDE_MOVERS = "includeMovers";
  @javax.annotation.Nullable
  private Boolean includeMovers;

  public static final String JSON_PROPERTY_INCLUDE_SECTOR_ALLOCATION = "includeSectorAllocation";
  @javax.annotation.Nullable
  private Boolean includeSectorAllocation;

  public static final String JSON_PROPERTY_INCLUDE_MARKET_CAP_ALLOCATION = "includeMarketCapAllocation";
  @javax.annotation.Nullable
  private Boolean includeMarketCapAllocation;

  public FeatureToggles() { 
  }

  public FeatureToggles includeHeatmap(@javax.annotation.Nullable Boolean includeHeatmap) {
    this.includeHeatmap = includeHeatmap;
    return this;
  }

  /**
   * Get includeHeatmap
   * @return includeHeatmap
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INCLUDE_HEATMAP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIncludeHeatmap() {
    return includeHeatmap;
  }


  @JsonProperty(value = JSON_PROPERTY_INCLUDE_HEATMAP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIncludeHeatmap(@javax.annotation.Nullable Boolean includeHeatmap) {
    this.includeHeatmap = includeHeatmap;
  }


  public FeatureToggles includeMovers(@javax.annotation.Nullable Boolean includeMovers) {
    this.includeMovers = includeMovers;
    return this;
  }

  /**
   * Get includeMovers
   * @return includeMovers
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INCLUDE_MOVERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIncludeMovers() {
    return includeMovers;
  }


  @JsonProperty(value = JSON_PROPERTY_INCLUDE_MOVERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIncludeMovers(@javax.annotation.Nullable Boolean includeMovers) {
    this.includeMovers = includeMovers;
  }


  public FeatureToggles includeSectorAllocation(@javax.annotation.Nullable Boolean includeSectorAllocation) {
    this.includeSectorAllocation = includeSectorAllocation;
    return this;
  }

  /**
   * Get includeSectorAllocation
   * @return includeSectorAllocation
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INCLUDE_SECTOR_ALLOCATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIncludeSectorAllocation() {
    return includeSectorAllocation;
  }


  @JsonProperty(value = JSON_PROPERTY_INCLUDE_SECTOR_ALLOCATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIncludeSectorAllocation(@javax.annotation.Nullable Boolean includeSectorAllocation) {
    this.includeSectorAllocation = includeSectorAllocation;
  }


  public FeatureToggles includeMarketCapAllocation(@javax.annotation.Nullable Boolean includeMarketCapAllocation) {
    this.includeMarketCapAllocation = includeMarketCapAllocation;
    return this;
  }

  /**
   * Get includeMarketCapAllocation
   * @return includeMarketCapAllocation
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INCLUDE_MARKET_CAP_ALLOCATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIncludeMarketCapAllocation() {
    return includeMarketCapAllocation;
  }


  @JsonProperty(value = JSON_PROPERTY_INCLUDE_MARKET_CAP_ALLOCATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIncludeMarketCapAllocation(@javax.annotation.Nullable Boolean includeMarketCapAllocation) {
    this.includeMarketCapAllocation = includeMarketCapAllocation;
  }


  /**
   * Return true if this FeatureToggles object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FeatureToggles featureToggles = (FeatureToggles) o;
    return Objects.equals(this.includeHeatmap, featureToggles.includeHeatmap) &&
        Objects.equals(this.includeMovers, featureToggles.includeMovers) &&
        Objects.equals(this.includeSectorAllocation, featureToggles.includeSectorAllocation) &&
        Objects.equals(this.includeMarketCapAllocation, featureToggles.includeMarketCapAllocation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(includeHeatmap, includeMovers, includeSectorAllocation, includeMarketCapAllocation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FeatureToggles {\n");
    sb.append("    includeHeatmap: ").append(toIndentedString(includeHeatmap)).append("\n");
    sb.append("    includeMovers: ").append(toIndentedString(includeMovers)).append("\n");
    sb.append("    includeSectorAllocation: ").append(toIndentedString(includeSectorAllocation)).append("\n");
    sb.append("    includeMarketCapAllocation: ").append(toIndentedString(includeMarketCapAllocation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `includeHeatmap` to the URL query string
    if (getIncludeHeatmap() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sincludeHeatmap%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIncludeHeatmap()))));
    }

    // add `includeMovers` to the URL query string
    if (getIncludeMovers() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sincludeMovers%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIncludeMovers()))));
    }

    // add `includeSectorAllocation` to the URL query string
    if (getIncludeSectorAllocation() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sincludeSectorAllocation%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIncludeSectorAllocation()))));
    }

    // add `includeMarketCapAllocation` to the URL query string
    if (getIncludeMarketCapAllocation() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sincludeMarketCapAllocation%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIncludeMarketCapAllocation()))));
    }

    return joiner.toString();
  }
}

