/*
 * Portfolio Management API
 * API documentation for the Asset Management Portfolio application
 *
 * The version of the OpenAPI document: v1.0
 * Contact: portfolio-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.portfolio.client.invoker.ApiClient;
/**
 * FundamentalRatios
 */
@JsonPropertyOrder({
  FundamentalRatios.JSON_PROPERTY_PRICE_TO_EARNING_RATION,
  FundamentalRatios.JSON_PROPERTY_PRICE_TO_BOOK_RATION,
  FundamentalRatios.JSON_PROPERTY_DIVIDEN_YIELD
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-26T23:23:15.876134200+05:30[Asia/Calcutta]", comments = "Generator version: 7.20.0")
public class FundamentalRatios {
  public static final String JSON_PROPERTY_PRICE_TO_EARNING_RATION = "priceToEarningRation";
  @javax.annotation.Nullable
  private Double priceToEarningRation;

  public static final String JSON_PROPERTY_PRICE_TO_BOOK_RATION = "priceToBookRation";
  @javax.annotation.Nullable
  private Double priceToBookRation;

  public static final String JSON_PROPERTY_DIVIDEN_YIELD = "dividenYield";
  @javax.annotation.Nullable
  private Double dividenYield;

  public FundamentalRatios() { 
  }

  public FundamentalRatios priceToEarningRation(@javax.annotation.Nullable Double priceToEarningRation) {
    this.priceToEarningRation = priceToEarningRation;
    return this;
  }

  /**
   * Get priceToEarningRation
   * @return priceToEarningRation
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PRICE_TO_EARNING_RATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getPriceToEarningRation() {
    return priceToEarningRation;
  }


  @JsonProperty(value = JSON_PROPERTY_PRICE_TO_EARNING_RATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPriceToEarningRation(@javax.annotation.Nullable Double priceToEarningRation) {
    this.priceToEarningRation = priceToEarningRation;
  }


  public FundamentalRatios priceToBookRation(@javax.annotation.Nullable Double priceToBookRation) {
    this.priceToBookRation = priceToBookRation;
    return this;
  }

  /**
   * Get priceToBookRation
   * @return priceToBookRation
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PRICE_TO_BOOK_RATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getPriceToBookRation() {
    return priceToBookRation;
  }


  @JsonProperty(value = JSON_PROPERTY_PRICE_TO_BOOK_RATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPriceToBookRation(@javax.annotation.Nullable Double priceToBookRation) {
    this.priceToBookRation = priceToBookRation;
  }


  public FundamentalRatios dividenYield(@javax.annotation.Nullable Double dividenYield) {
    this.dividenYield = dividenYield;
    return this;
  }

  /**
   * Get dividenYield
   * @return dividenYield
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DIVIDEN_YIELD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getDividenYield() {
    return dividenYield;
  }


  @JsonProperty(value = JSON_PROPERTY_DIVIDEN_YIELD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDividenYield(@javax.annotation.Nullable Double dividenYield) {
    this.dividenYield = dividenYield;
  }


  /**
   * Return true if this FundamentalRatios object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FundamentalRatios fundamentalRatios = (FundamentalRatios) o;
    return Objects.equals(this.priceToEarningRation, fundamentalRatios.priceToEarningRation) &&
        Objects.equals(this.priceToBookRation, fundamentalRatios.priceToBookRation) &&
        Objects.equals(this.dividenYield, fundamentalRatios.dividenYield);
  }

  @Override
  public int hashCode() {
    return Objects.hash(priceToEarningRation, priceToBookRation, dividenYield);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FundamentalRatios {\n");
    sb.append("    priceToEarningRation: ").append(toIndentedString(priceToEarningRation)).append("\n");
    sb.append("    priceToBookRation: ").append(toIndentedString(priceToBookRation)).append("\n");
    sb.append("    dividenYield: ").append(toIndentedString(dividenYield)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `priceToEarningRation` to the URL query string
    if (getPriceToEarningRation() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spriceToEarningRation%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPriceToEarningRation()))));
    }

    // add `priceToBookRation` to the URL query string
    if (getPriceToBookRation() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spriceToBookRation%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPriceToBookRation()))));
    }

    // add `dividenYield` to the URL query string
    if (getDividenYield() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdividenYield%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDividenYield()))));
    }

    return joiner.toString();
  }
}

