/*
 * Portfolio Management API
 * API documentation for the Asset Management Portfolio application
 *
 * The version of the OpenAPI document: v1.0
 * Contact: portfolio-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.portfolio.client.invoker.ApiClient;
/**
 * HistoricalComparison
 */
@JsonPropertyOrder({
  HistoricalComparison.JSON_PROPERTY_VALUE,
  HistoricalComparison.JSON_PROPERTY_PER_CHANGE365D,
  HistoricalComparison.JSON_PROPERTY_DATE365D_AGO,
  HistoricalComparison.JSON_PROPERTY_PER_CHANGE30D,
  HistoricalComparison.JSON_PROPERTY_DATE30D_AGO,
  HistoricalComparison.JSON_PROPERTY_PREVIOUS_DAY,
  HistoricalComparison.JSON_PROPERTY_ONE_WEEK_AGO,
  HistoricalComparison.JSON_PROPERTY_ONE_MONTH_AGO,
  HistoricalComparison.JSON_PROPERTY_ONE_YEAR_AGO
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-26T23:23:15.876134200+05:30[Asia/Calcutta]", comments = "Generator version: 7.20.0")
public class HistoricalComparison {
  public static final String JSON_PROPERTY_VALUE = "value";
  @javax.annotation.Nullable
  private Double value;

  public static final String JSON_PROPERTY_PER_CHANGE365D = "perChange365d";
  @javax.annotation.Nullable
  private Double perChange365d;

  public static final String JSON_PROPERTY_DATE365D_AGO = "date365dAgo";
  @javax.annotation.Nullable
  private OffsetDateTime date365dAgo;

  public static final String JSON_PROPERTY_PER_CHANGE30D = "perChange30d";
  @javax.annotation.Nullable
  private Double perChange30d;

  public static final String JSON_PROPERTY_DATE30D_AGO = "date30dAgo";
  @javax.annotation.Nullable
  private OffsetDateTime date30dAgo;

  public static final String JSON_PROPERTY_PREVIOUS_DAY = "previousDay";
  @javax.annotation.Nullable
  private Double previousDay;

  public static final String JSON_PROPERTY_ONE_WEEK_AGO = "oneWeekAgo";
  @javax.annotation.Nullable
  private Double oneWeekAgo;

  public static final String JSON_PROPERTY_ONE_MONTH_AGO = "oneMonthAgo";
  @javax.annotation.Nullable
  private Double oneMonthAgo;

  public static final String JSON_PROPERTY_ONE_YEAR_AGO = "oneYearAgo";
  @javax.annotation.Nullable
  private Double oneYearAgo;

  public HistoricalComparison() { 
  }

  public HistoricalComparison value(@javax.annotation.Nullable Double value) {
    this.value = value;
    return this;
  }

  /**
   * Get value
   * @return value
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getValue() {
    return value;
  }


  @JsonProperty(value = JSON_PROPERTY_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValue(@javax.annotation.Nullable Double value) {
    this.value = value;
  }


  public HistoricalComparison perChange365d(@javax.annotation.Nullable Double perChange365d) {
    this.perChange365d = perChange365d;
    return this;
  }

  /**
   * Get perChange365d
   * @return perChange365d
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PER_CHANGE365D, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getPerChange365d() {
    return perChange365d;
  }


  @JsonProperty(value = JSON_PROPERTY_PER_CHANGE365D, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPerChange365d(@javax.annotation.Nullable Double perChange365d) {
    this.perChange365d = perChange365d;
  }


  public HistoricalComparison date365dAgo(@javax.annotation.Nullable OffsetDateTime date365dAgo) {
    this.date365dAgo = date365dAgo;
    return this;
  }

  /**
   * Get date365dAgo
   * @return date365dAgo
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DATE365D_AGO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getDate365dAgo() {
    return date365dAgo;
  }


  @JsonProperty(value = JSON_PROPERTY_DATE365D_AGO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDate365dAgo(@javax.annotation.Nullable OffsetDateTime date365dAgo) {
    this.date365dAgo = date365dAgo;
  }


  public HistoricalComparison perChange30d(@javax.annotation.Nullable Double perChange30d) {
    this.perChange30d = perChange30d;
    return this;
  }

  /**
   * Get perChange30d
   * @return perChange30d
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PER_CHANGE30D, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getPerChange30d() {
    return perChange30d;
  }


  @JsonProperty(value = JSON_PROPERTY_PER_CHANGE30D, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPerChange30d(@javax.annotation.Nullable Double perChange30d) {
    this.perChange30d = perChange30d;
  }


  public HistoricalComparison date30dAgo(@javax.annotation.Nullable OffsetDateTime date30dAgo) {
    this.date30dAgo = date30dAgo;
    return this;
  }

  /**
   * Get date30dAgo
   * @return date30dAgo
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DATE30D_AGO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getDate30dAgo() {
    return date30dAgo;
  }


  @JsonProperty(value = JSON_PROPERTY_DATE30D_AGO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDate30dAgo(@javax.annotation.Nullable OffsetDateTime date30dAgo) {
    this.date30dAgo = date30dAgo;
  }


  public HistoricalComparison previousDay(@javax.annotation.Nullable Double previousDay) {
    this.previousDay = previousDay;
    return this;
  }

  /**
   * Get previousDay
   * @return previousDay
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PREVIOUS_DAY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getPreviousDay() {
    return previousDay;
  }


  @JsonProperty(value = JSON_PROPERTY_PREVIOUS_DAY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPreviousDay(@javax.annotation.Nullable Double previousDay) {
    this.previousDay = previousDay;
  }


  public HistoricalComparison oneWeekAgo(@javax.annotation.Nullable Double oneWeekAgo) {
    this.oneWeekAgo = oneWeekAgo;
    return this;
  }

  /**
   * Get oneWeekAgo
   * @return oneWeekAgo
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ONE_WEEK_AGO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getOneWeekAgo() {
    return oneWeekAgo;
  }


  @JsonProperty(value = JSON_PROPERTY_ONE_WEEK_AGO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOneWeekAgo(@javax.annotation.Nullable Double oneWeekAgo) {
    this.oneWeekAgo = oneWeekAgo;
  }


  public HistoricalComparison oneMonthAgo(@javax.annotation.Nullable Double oneMonthAgo) {
    this.oneMonthAgo = oneMonthAgo;
    return this;
  }

  /**
   * Get oneMonthAgo
   * @return oneMonthAgo
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ONE_MONTH_AGO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getOneMonthAgo() {
    return oneMonthAgo;
  }


  @JsonProperty(value = JSON_PROPERTY_ONE_MONTH_AGO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOneMonthAgo(@javax.annotation.Nullable Double oneMonthAgo) {
    this.oneMonthAgo = oneMonthAgo;
  }


  public HistoricalComparison oneYearAgo(@javax.annotation.Nullable Double oneYearAgo) {
    this.oneYearAgo = oneYearAgo;
    return this;
  }

  /**
   * Get oneYearAgo
   * @return oneYearAgo
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ONE_YEAR_AGO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getOneYearAgo() {
    return oneYearAgo;
  }


  @JsonProperty(value = JSON_PROPERTY_ONE_YEAR_AGO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOneYearAgo(@javax.annotation.Nullable Double oneYearAgo) {
    this.oneYearAgo = oneYearAgo;
  }


  /**
   * Return true if this HistoricalComparison object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HistoricalComparison historicalComparison = (HistoricalComparison) o;
    return Objects.equals(this.value, historicalComparison.value) &&
        Objects.equals(this.perChange365d, historicalComparison.perChange365d) &&
        Objects.equals(this.date365dAgo, historicalComparison.date365dAgo) &&
        Objects.equals(this.perChange30d, historicalComparison.perChange30d) &&
        Objects.equals(this.date30dAgo, historicalComparison.date30dAgo) &&
        Objects.equals(this.previousDay, historicalComparison.previousDay) &&
        Objects.equals(this.oneWeekAgo, historicalComparison.oneWeekAgo) &&
        Objects.equals(this.oneMonthAgo, historicalComparison.oneMonthAgo) &&
        Objects.equals(this.oneYearAgo, historicalComparison.oneYearAgo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value, perChange365d, date365dAgo, perChange30d, date30dAgo, previousDay, oneWeekAgo, oneMonthAgo, oneYearAgo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HistoricalComparison {\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    perChange365d: ").append(toIndentedString(perChange365d)).append("\n");
    sb.append("    date365dAgo: ").append(toIndentedString(date365dAgo)).append("\n");
    sb.append("    perChange30d: ").append(toIndentedString(perChange30d)).append("\n");
    sb.append("    date30dAgo: ").append(toIndentedString(date30dAgo)).append("\n");
    sb.append("    previousDay: ").append(toIndentedString(previousDay)).append("\n");
    sb.append("    oneWeekAgo: ").append(toIndentedString(oneWeekAgo)).append("\n");
    sb.append("    oneMonthAgo: ").append(toIndentedString(oneMonthAgo)).append("\n");
    sb.append("    oneYearAgo: ").append(toIndentedString(oneYearAgo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `value` to the URL query string
    if (getValue() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%svalue%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getValue()))));
    }

    // add `perChange365d` to the URL query string
    if (getPerChange365d() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sperChange365d%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPerChange365d()))));
    }

    // add `date365dAgo` to the URL query string
    if (getDate365dAgo() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdate365dAgo%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDate365dAgo()))));
    }

    // add `perChange30d` to the URL query string
    if (getPerChange30d() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sperChange30d%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPerChange30d()))));
    }

    // add `date30dAgo` to the URL query string
    if (getDate30dAgo() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdate30dAgo%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDate30dAgo()))));
    }

    // add `previousDay` to the URL query string
    if (getPreviousDay() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spreviousDay%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPreviousDay()))));
    }

    // add `oneWeekAgo` to the URL query string
    if (getOneWeekAgo() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%soneWeekAgo%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOneWeekAgo()))));
    }

    // add `oneMonthAgo` to the URL query string
    if (getOneMonthAgo() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%soneMonthAgo%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOneMonthAgo()))));
    }

    // add `oneYearAgo` to the URL query string
    if (getOneYearAgo() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%soneYearAgo%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOneYearAgo()))));
    }

    return joiner.toString();
  }
}

