/*
 * Portfolio Management API
 * API documentation for the Asset Management Portfolio application
 *
 * The version of the OpenAPI document: v1.0
 * Contact: portfolio-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.portfolio.client.invoker.ApiClient;
/**
 * StockMovement
 */
@JsonPropertyOrder({
  StockMovement.JSON_PROPERTY_SYMBOL,
  StockMovement.JSON_PROPERTY_COMPANY_NAME,
  StockMovement.JSON_PROPERTY_LAST_PRICE,
  StockMovement.JSON_PROPERTY_CHANGE_AMOUNT,
  StockMovement.JSON_PROPERTY_CHANGE_PERCENT,
  StockMovement.JSON_PROPERTY_SECTOR,
  StockMovement.JSON_PROPERTY_QUANTITY,
  StockMovement.JSON_PROPERTY_MARKET_VALUE,
  StockMovement.JSON_PROPERTY_WEIGHT_PERCENTAGE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-26T23:23:15.876134200+05:30[Asia/Calcutta]", comments = "Generator version: 7.20.0")
public class StockMovement {
  public static final String JSON_PROPERTY_SYMBOL = "symbol";
  @javax.annotation.Nullable
  private String symbol;

  public static final String JSON_PROPERTY_COMPANY_NAME = "companyName";
  @javax.annotation.Nullable
  private String companyName;

  public static final String JSON_PROPERTY_LAST_PRICE = "lastPrice";
  @javax.annotation.Nullable
  private Double lastPrice;

  public static final String JSON_PROPERTY_CHANGE_AMOUNT = "changeAmount";
  @javax.annotation.Nullable
  private Double changeAmount;

  public static final String JSON_PROPERTY_CHANGE_PERCENT = "changePercent";
  @javax.annotation.Nullable
  private Double changePercent;

  public static final String JSON_PROPERTY_SECTOR = "sector";
  @javax.annotation.Nullable
  private String sector;

  public static final String JSON_PROPERTY_QUANTITY = "quantity";
  @javax.annotation.Nullable
  private Double quantity;

  public static final String JSON_PROPERTY_MARKET_VALUE = "marketValue";
  @javax.annotation.Nullable
  private Double marketValue;

  public static final String JSON_PROPERTY_WEIGHT_PERCENTAGE = "weightPercentage";
  @javax.annotation.Nullable
  private Double weightPercentage;

  public StockMovement() { 
  }

  public StockMovement symbol(@javax.annotation.Nullable String symbol) {
    this.symbol = symbol;
    return this;
  }

  /**
   * Get symbol
   * @return symbol
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SYMBOL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSymbol() {
    return symbol;
  }


  @JsonProperty(value = JSON_PROPERTY_SYMBOL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSymbol(@javax.annotation.Nullable String symbol) {
    this.symbol = symbol;
  }


  public StockMovement companyName(@javax.annotation.Nullable String companyName) {
    this.companyName = companyName;
    return this;
  }

  /**
   * Get companyName
   * @return companyName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COMPANY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCompanyName() {
    return companyName;
  }


  @JsonProperty(value = JSON_PROPERTY_COMPANY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCompanyName(@javax.annotation.Nullable String companyName) {
    this.companyName = companyName;
  }


  public StockMovement lastPrice(@javax.annotation.Nullable Double lastPrice) {
    this.lastPrice = lastPrice;
    return this;
  }

  /**
   * Get lastPrice
   * @return lastPrice
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LAST_PRICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getLastPrice() {
    return lastPrice;
  }


  @JsonProperty(value = JSON_PROPERTY_LAST_PRICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastPrice(@javax.annotation.Nullable Double lastPrice) {
    this.lastPrice = lastPrice;
  }


  public StockMovement changeAmount(@javax.annotation.Nullable Double changeAmount) {
    this.changeAmount = changeAmount;
    return this;
  }

  /**
   * Get changeAmount
   * @return changeAmount
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CHANGE_AMOUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getChangeAmount() {
    return changeAmount;
  }


  @JsonProperty(value = JSON_PROPERTY_CHANGE_AMOUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChangeAmount(@javax.annotation.Nullable Double changeAmount) {
    this.changeAmount = changeAmount;
  }


  public StockMovement changePercent(@javax.annotation.Nullable Double changePercent) {
    this.changePercent = changePercent;
    return this;
  }

  /**
   * Get changePercent
   * @return changePercent
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CHANGE_PERCENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getChangePercent() {
    return changePercent;
  }


  @JsonProperty(value = JSON_PROPERTY_CHANGE_PERCENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChangePercent(@javax.annotation.Nullable Double changePercent) {
    this.changePercent = changePercent;
  }


  public StockMovement sector(@javax.annotation.Nullable String sector) {
    this.sector = sector;
    return this;
  }

  /**
   * Get sector
   * @return sector
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SECTOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSector() {
    return sector;
  }


  @JsonProperty(value = JSON_PROPERTY_SECTOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSector(@javax.annotation.Nullable String sector) {
    this.sector = sector;
  }


  public StockMovement quantity(@javax.annotation.Nullable Double quantity) {
    this.quantity = quantity;
    return this;
  }

  /**
   * Get quantity
   * @return quantity
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_QUANTITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getQuantity() {
    return quantity;
  }


  @JsonProperty(value = JSON_PROPERTY_QUANTITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQuantity(@javax.annotation.Nullable Double quantity) {
    this.quantity = quantity;
  }


  public StockMovement marketValue(@javax.annotation.Nullable Double marketValue) {
    this.marketValue = marketValue;
    return this;
  }

  /**
   * Get marketValue
   * @return marketValue
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MARKET_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getMarketValue() {
    return marketValue;
  }


  @JsonProperty(value = JSON_PROPERTY_MARKET_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMarketValue(@javax.annotation.Nullable Double marketValue) {
    this.marketValue = marketValue;
  }


  public StockMovement weightPercentage(@javax.annotation.Nullable Double weightPercentage) {
    this.weightPercentage = weightPercentage;
    return this;
  }

  /**
   * Get weightPercentage
   * @return weightPercentage
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WEIGHT_PERCENTAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getWeightPercentage() {
    return weightPercentage;
  }


  @JsonProperty(value = JSON_PROPERTY_WEIGHT_PERCENTAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWeightPercentage(@javax.annotation.Nullable Double weightPercentage) {
    this.weightPercentage = weightPercentage;
  }


  /**
   * Return true if this StockMovement object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StockMovement stockMovement = (StockMovement) o;
    return Objects.equals(this.symbol, stockMovement.symbol) &&
        Objects.equals(this.companyName, stockMovement.companyName) &&
        Objects.equals(this.lastPrice, stockMovement.lastPrice) &&
        Objects.equals(this.changeAmount, stockMovement.changeAmount) &&
        Objects.equals(this.changePercent, stockMovement.changePercent) &&
        Objects.equals(this.sector, stockMovement.sector) &&
        Objects.equals(this.quantity, stockMovement.quantity) &&
        Objects.equals(this.marketValue, stockMovement.marketValue) &&
        Objects.equals(this.weightPercentage, stockMovement.weightPercentage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(symbol, companyName, lastPrice, changeAmount, changePercent, sector, quantity, marketValue, weightPercentage);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StockMovement {\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    companyName: ").append(toIndentedString(companyName)).append("\n");
    sb.append("    lastPrice: ").append(toIndentedString(lastPrice)).append("\n");
    sb.append("    changeAmount: ").append(toIndentedString(changeAmount)).append("\n");
    sb.append("    changePercent: ").append(toIndentedString(changePercent)).append("\n");
    sb.append("    sector: ").append(toIndentedString(sector)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    marketValue: ").append(toIndentedString(marketValue)).append("\n");
    sb.append("    weightPercentage: ").append(toIndentedString(weightPercentage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `symbol` to the URL query string
    if (getSymbol() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssymbol%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSymbol()))));
    }

    // add `companyName` to the URL query string
    if (getCompanyName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scompanyName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCompanyName()))));
    }

    // add `lastPrice` to the URL query string
    if (getLastPrice() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slastPrice%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLastPrice()))));
    }

    // add `changeAmount` to the URL query string
    if (getChangeAmount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%schangeAmount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getChangeAmount()))));
    }

    // add `changePercent` to the URL query string
    if (getChangePercent() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%schangePercent%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getChangePercent()))));
    }

    // add `sector` to the URL query string
    if (getSector() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssector%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSector()))));
    }

    // add `quantity` to the URL query string
    if (getQuantity() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%squantity%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getQuantity()))));
    }

    // add `marketValue` to the URL query string
    if (getMarketValue() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smarketValue%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMarketValue()))));
    }

    // add `weightPercentage` to the URL query string
    if (getWeightPercentage() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sweightPercentage%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getWeightPercentage()))));
    }

    return joiner.toString();
  }
}

