/*
 * Portfolio Management API
 * API documentation for the Asset Management Portfolio application
 *
 * The version of the OpenAPI document: v1.0
 * Contact: portfolio-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.am.portfolio.client.model.OHLCVModel;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.portfolio.client.invoker.ApiClient;
/**
 * TimeSeriesDataModel
 */
@JsonPropertyOrder({
  TimeSeriesDataModel.JSON_PROPERTY_ID,
  TimeSeriesDataModel.JSON_PROPERTY_TIMESTAMP,
  TimeSeriesDataModel.JSON_PROPERTY_TIMEFRAME,
  TimeSeriesDataModel.JSON_PROPERTY_OHLCV,
  TimeSeriesDataModel.JSON_PROPERTY_LATEST_FIVE_MIN,
  TimeSeriesDataModel.JSON_PROPERTY_LATEST_FIFTEEN_MIN,
  TimeSeriesDataModel.JSON_PROPERTY_LATEST_HOURLY,
  TimeSeriesDataModel.JSON_PROPERTY_LATEST_DAILY,
  TimeSeriesDataModel.JSON_PROPERTY_LATEST_WEEKLY,
  TimeSeriesDataModel.JSON_PROPERTY_LATEST_MONTHLY,
  TimeSeriesDataModel.JSON_PROPERTY_LATEST_YEARLY,
  TimeSeriesDataModel.JSON_PROPERTY_VOLUME,
  TimeSeriesDataModel.JSON_PROPERTY_OPEN_INTEREST,
  TimeSeriesDataModel.JSON_PROPERTY_VOLATILITY,
  TimeSeriesDataModel.JSON_PROPERTY_RELATIVE_STRENGTH_INDEX,
  TimeSeriesDataModel.JSON_PROPERTY_MOVING_AVERAGE50,
  TimeSeriesDataModel.JSON_PROPERTY_MOVING_AVERAGE200,
  TimeSeriesDataModel.JSON_PROPERTY_BOLLINGER_UPPER_BAND,
  TimeSeriesDataModel.JSON_PROPERTY_BOLLINGER_LOWER_BAND,
  TimeSeriesDataModel.JSON_PROPERTY_MACD_LINE,
  TimeSeriesDataModel.JSON_PROPERTY_MACD_SIGNAL_LINE,
  TimeSeriesDataModel.JSON_PROPERTY_MACD_HISTOGRAM
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-26T23:23:15.876134200+05:30[Asia/Calcutta]", comments = "Generator version: 7.20.0")
public class TimeSeriesDataModel {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private UUID id;

  public static final String JSON_PROPERTY_TIMESTAMP = "timestamp";
  @javax.annotation.Nullable
  private OffsetDateTime timestamp;

  public static final String JSON_PROPERTY_TIMEFRAME = "timeframe";
  @javax.annotation.Nullable
  private String timeframe;

  public static final String JSON_PROPERTY_OHLCV = "ohlcv";
  @javax.annotation.Nullable
  private OHLCVModel ohlcv;

  public static final String JSON_PROPERTY_LATEST_FIVE_MIN = "latestFiveMin";
  @javax.annotation.Nullable
  private OHLCVModel latestFiveMin;

  public static final String JSON_PROPERTY_LATEST_FIFTEEN_MIN = "latestFifteenMin";
  @javax.annotation.Nullable
  private OHLCVModel latestFifteenMin;

  public static final String JSON_PROPERTY_LATEST_HOURLY = "latestHourly";
  @javax.annotation.Nullable
  private OHLCVModel latestHourly;

  public static final String JSON_PROPERTY_LATEST_DAILY = "latestDaily";
  @javax.annotation.Nullable
  private OHLCVModel latestDaily;

  public static final String JSON_PROPERTY_LATEST_WEEKLY = "latestWeekly";
  @javax.annotation.Nullable
  private OHLCVModel latestWeekly;

  public static final String JSON_PROPERTY_LATEST_MONTHLY = "latestMonthly";
  @javax.annotation.Nullable
  private OHLCVModel latestMonthly;

  public static final String JSON_PROPERTY_LATEST_YEARLY = "latestYearly";
  @javax.annotation.Nullable
  private OHLCVModel latestYearly;

  public static final String JSON_PROPERTY_VOLUME = "volume";
  @javax.annotation.Nullable
  private Double volume;

  public static final String JSON_PROPERTY_OPEN_INTEREST = "openInterest";
  @javax.annotation.Nullable
  private Double openInterest;

  public static final String JSON_PROPERTY_VOLATILITY = "volatility";
  @javax.annotation.Nullable
  private Double volatility;

  public static final String JSON_PROPERTY_RELATIVE_STRENGTH_INDEX = "relativeStrengthIndex";
  @javax.annotation.Nullable
  private Double relativeStrengthIndex;

  public static final String JSON_PROPERTY_MOVING_AVERAGE50 = "movingAverage50";
  @javax.annotation.Nullable
  private Double movingAverage50;

  public static final String JSON_PROPERTY_MOVING_AVERAGE200 = "movingAverage200";
  @javax.annotation.Nullable
  private Double movingAverage200;

  public static final String JSON_PROPERTY_BOLLINGER_UPPER_BAND = "bollingerUpperBand";
  @javax.annotation.Nullable
  private Double bollingerUpperBand;

  public static final String JSON_PROPERTY_BOLLINGER_LOWER_BAND = "bollingerLowerBand";
  @javax.annotation.Nullable
  private Double bollingerLowerBand;

  public static final String JSON_PROPERTY_MACD_LINE = "macdLine";
  @javax.annotation.Nullable
  private Double macdLine;

  public static final String JSON_PROPERTY_MACD_SIGNAL_LINE = "macdSignalLine";
  @javax.annotation.Nullable
  private Double macdSignalLine;

  public static final String JSON_PROPERTY_MACD_HISTOGRAM = "macdHistogram";
  @javax.annotation.Nullable
  private Double macdHistogram;

  public TimeSeriesDataModel() { 
  }

  public TimeSeriesDataModel id(@javax.annotation.Nullable UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable UUID id) {
    this.id = id;
  }


  public TimeSeriesDataModel timestamp(@javax.annotation.Nullable OffsetDateTime timestamp) {
    this.timestamp = timestamp;
    return this;
  }

  /**
   * Get timestamp
   * @return timestamp
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getTimestamp() {
    return timestamp;
  }


  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimestamp(@javax.annotation.Nullable OffsetDateTime timestamp) {
    this.timestamp = timestamp;
  }


  public TimeSeriesDataModel timeframe(@javax.annotation.Nullable String timeframe) {
    this.timeframe = timeframe;
    return this;
  }

  /**
   * Get timeframe
   * @return timeframe
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIMEFRAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTimeframe() {
    return timeframe;
  }


  @JsonProperty(value = JSON_PROPERTY_TIMEFRAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimeframe(@javax.annotation.Nullable String timeframe) {
    this.timeframe = timeframe;
  }


  public TimeSeriesDataModel ohlcv(@javax.annotation.Nullable OHLCVModel ohlcv) {
    this.ohlcv = ohlcv;
    return this;
  }

  /**
   * Get ohlcv
   * @return ohlcv
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OHLCV, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OHLCVModel getOhlcv() {
    return ohlcv;
  }


  @JsonProperty(value = JSON_PROPERTY_OHLCV, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOhlcv(@javax.annotation.Nullable OHLCVModel ohlcv) {
    this.ohlcv = ohlcv;
  }


  public TimeSeriesDataModel latestFiveMin(@javax.annotation.Nullable OHLCVModel latestFiveMin) {
    this.latestFiveMin = latestFiveMin;
    return this;
  }

  /**
   * Get latestFiveMin
   * @return latestFiveMin
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LATEST_FIVE_MIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OHLCVModel getLatestFiveMin() {
    return latestFiveMin;
  }


  @JsonProperty(value = JSON_PROPERTY_LATEST_FIVE_MIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLatestFiveMin(@javax.annotation.Nullable OHLCVModel latestFiveMin) {
    this.latestFiveMin = latestFiveMin;
  }


  public TimeSeriesDataModel latestFifteenMin(@javax.annotation.Nullable OHLCVModel latestFifteenMin) {
    this.latestFifteenMin = latestFifteenMin;
    return this;
  }

  /**
   * Get latestFifteenMin
   * @return latestFifteenMin
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LATEST_FIFTEEN_MIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OHLCVModel getLatestFifteenMin() {
    return latestFifteenMin;
  }


  @JsonProperty(value = JSON_PROPERTY_LATEST_FIFTEEN_MIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLatestFifteenMin(@javax.annotation.Nullable OHLCVModel latestFifteenMin) {
    this.latestFifteenMin = latestFifteenMin;
  }


  public TimeSeriesDataModel latestHourly(@javax.annotation.Nullable OHLCVModel latestHourly) {
    this.latestHourly = latestHourly;
    return this;
  }

  /**
   * Get latestHourly
   * @return latestHourly
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LATEST_HOURLY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OHLCVModel getLatestHourly() {
    return latestHourly;
  }


  @JsonProperty(value = JSON_PROPERTY_LATEST_HOURLY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLatestHourly(@javax.annotation.Nullable OHLCVModel latestHourly) {
    this.latestHourly = latestHourly;
  }


  public TimeSeriesDataModel latestDaily(@javax.annotation.Nullable OHLCVModel latestDaily) {
    this.latestDaily = latestDaily;
    return this;
  }

  /**
   * Get latestDaily
   * @return latestDaily
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LATEST_DAILY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OHLCVModel getLatestDaily() {
    return latestDaily;
  }


  @JsonProperty(value = JSON_PROPERTY_LATEST_DAILY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLatestDaily(@javax.annotation.Nullable OHLCVModel latestDaily) {
    this.latestDaily = latestDaily;
  }


  public TimeSeriesDataModel latestWeekly(@javax.annotation.Nullable OHLCVModel latestWeekly) {
    this.latestWeekly = latestWeekly;
    return this;
  }

  /**
   * Get latestWeekly
   * @return latestWeekly
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LATEST_WEEKLY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OHLCVModel getLatestWeekly() {
    return latestWeekly;
  }


  @JsonProperty(value = JSON_PROPERTY_LATEST_WEEKLY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLatestWeekly(@javax.annotation.Nullable OHLCVModel latestWeekly) {
    this.latestWeekly = latestWeekly;
  }


  public TimeSeriesDataModel latestMonthly(@javax.annotation.Nullable OHLCVModel latestMonthly) {
    this.latestMonthly = latestMonthly;
    return this;
  }

  /**
   * Get latestMonthly
   * @return latestMonthly
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LATEST_MONTHLY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OHLCVModel getLatestMonthly() {
    return latestMonthly;
  }


  @JsonProperty(value = JSON_PROPERTY_LATEST_MONTHLY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLatestMonthly(@javax.annotation.Nullable OHLCVModel latestMonthly) {
    this.latestMonthly = latestMonthly;
  }


  public TimeSeriesDataModel latestYearly(@javax.annotation.Nullable OHLCVModel latestYearly) {
    this.latestYearly = latestYearly;
    return this;
  }

  /**
   * Get latestYearly
   * @return latestYearly
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LATEST_YEARLY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OHLCVModel getLatestYearly() {
    return latestYearly;
  }


  @JsonProperty(value = JSON_PROPERTY_LATEST_YEARLY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLatestYearly(@javax.annotation.Nullable OHLCVModel latestYearly) {
    this.latestYearly = latestYearly;
  }


  public TimeSeriesDataModel volume(@javax.annotation.Nullable Double volume) {
    this.volume = volume;
    return this;
  }

  /**
   * Get volume
   * @return volume
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VOLUME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getVolume() {
    return volume;
  }


  @JsonProperty(value = JSON_PROPERTY_VOLUME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVolume(@javax.annotation.Nullable Double volume) {
    this.volume = volume;
  }


  public TimeSeriesDataModel openInterest(@javax.annotation.Nullable Double openInterest) {
    this.openInterest = openInterest;
    return this;
  }

  /**
   * Get openInterest
   * @return openInterest
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OPEN_INTEREST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getOpenInterest() {
    return openInterest;
  }


  @JsonProperty(value = JSON_PROPERTY_OPEN_INTEREST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOpenInterest(@javax.annotation.Nullable Double openInterest) {
    this.openInterest = openInterest;
  }


  public TimeSeriesDataModel volatility(@javax.annotation.Nullable Double volatility) {
    this.volatility = volatility;
    return this;
  }

  /**
   * Get volatility
   * @return volatility
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VOLATILITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getVolatility() {
    return volatility;
  }


  @JsonProperty(value = JSON_PROPERTY_VOLATILITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVolatility(@javax.annotation.Nullable Double volatility) {
    this.volatility = volatility;
  }


  public TimeSeriesDataModel relativeStrengthIndex(@javax.annotation.Nullable Double relativeStrengthIndex) {
    this.relativeStrengthIndex = relativeStrengthIndex;
    return this;
  }

  /**
   * Get relativeStrengthIndex
   * @return relativeStrengthIndex
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RELATIVE_STRENGTH_INDEX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getRelativeStrengthIndex() {
    return relativeStrengthIndex;
  }


  @JsonProperty(value = JSON_PROPERTY_RELATIVE_STRENGTH_INDEX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRelativeStrengthIndex(@javax.annotation.Nullable Double relativeStrengthIndex) {
    this.relativeStrengthIndex = relativeStrengthIndex;
  }


  public TimeSeriesDataModel movingAverage50(@javax.annotation.Nullable Double movingAverage50) {
    this.movingAverage50 = movingAverage50;
    return this;
  }

  /**
   * Get movingAverage50
   * @return movingAverage50
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MOVING_AVERAGE50, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getMovingAverage50() {
    return movingAverage50;
  }


  @JsonProperty(value = JSON_PROPERTY_MOVING_AVERAGE50, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMovingAverage50(@javax.annotation.Nullable Double movingAverage50) {
    this.movingAverage50 = movingAverage50;
  }


  public TimeSeriesDataModel movingAverage200(@javax.annotation.Nullable Double movingAverage200) {
    this.movingAverage200 = movingAverage200;
    return this;
  }

  /**
   * Get movingAverage200
   * @return movingAverage200
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MOVING_AVERAGE200, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getMovingAverage200() {
    return movingAverage200;
  }


  @JsonProperty(value = JSON_PROPERTY_MOVING_AVERAGE200, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMovingAverage200(@javax.annotation.Nullable Double movingAverage200) {
    this.movingAverage200 = movingAverage200;
  }


  public TimeSeriesDataModel bollingerUpperBand(@javax.annotation.Nullable Double bollingerUpperBand) {
    this.bollingerUpperBand = bollingerUpperBand;
    return this;
  }

  /**
   * Get bollingerUpperBand
   * @return bollingerUpperBand
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BOLLINGER_UPPER_BAND, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getBollingerUpperBand() {
    return bollingerUpperBand;
  }


  @JsonProperty(value = JSON_PROPERTY_BOLLINGER_UPPER_BAND, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBollingerUpperBand(@javax.annotation.Nullable Double bollingerUpperBand) {
    this.bollingerUpperBand = bollingerUpperBand;
  }


  public TimeSeriesDataModel bollingerLowerBand(@javax.annotation.Nullable Double bollingerLowerBand) {
    this.bollingerLowerBand = bollingerLowerBand;
    return this;
  }

  /**
   * Get bollingerLowerBand
   * @return bollingerLowerBand
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BOLLINGER_LOWER_BAND, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getBollingerLowerBand() {
    return bollingerLowerBand;
  }


  @JsonProperty(value = JSON_PROPERTY_BOLLINGER_LOWER_BAND, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBollingerLowerBand(@javax.annotation.Nullable Double bollingerLowerBand) {
    this.bollingerLowerBand = bollingerLowerBand;
  }


  public TimeSeriesDataModel macdLine(@javax.annotation.Nullable Double macdLine) {
    this.macdLine = macdLine;
    return this;
  }

  /**
   * Get macdLine
   * @return macdLine
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MACD_LINE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getMacdLine() {
    return macdLine;
  }


  @JsonProperty(value = JSON_PROPERTY_MACD_LINE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMacdLine(@javax.annotation.Nullable Double macdLine) {
    this.macdLine = macdLine;
  }


  public TimeSeriesDataModel macdSignalLine(@javax.annotation.Nullable Double macdSignalLine) {
    this.macdSignalLine = macdSignalLine;
    return this;
  }

  /**
   * Get macdSignalLine
   * @return macdSignalLine
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MACD_SIGNAL_LINE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getMacdSignalLine() {
    return macdSignalLine;
  }


  @JsonProperty(value = JSON_PROPERTY_MACD_SIGNAL_LINE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMacdSignalLine(@javax.annotation.Nullable Double macdSignalLine) {
    this.macdSignalLine = macdSignalLine;
  }


  public TimeSeriesDataModel macdHistogram(@javax.annotation.Nullable Double macdHistogram) {
    this.macdHistogram = macdHistogram;
    return this;
  }

  /**
   * Get macdHistogram
   * @return macdHistogram
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MACD_HISTOGRAM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getMacdHistogram() {
    return macdHistogram;
  }


  @JsonProperty(value = JSON_PROPERTY_MACD_HISTOGRAM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMacdHistogram(@javax.annotation.Nullable Double macdHistogram) {
    this.macdHistogram = macdHistogram;
  }


  /**
   * Return true if this TimeSeriesDataModel object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TimeSeriesDataModel timeSeriesDataModel = (TimeSeriesDataModel) o;
    return Objects.equals(this.id, timeSeriesDataModel.id) &&
        Objects.equals(this.timestamp, timeSeriesDataModel.timestamp) &&
        Objects.equals(this.timeframe, timeSeriesDataModel.timeframe) &&
        Objects.equals(this.ohlcv, timeSeriesDataModel.ohlcv) &&
        Objects.equals(this.latestFiveMin, timeSeriesDataModel.latestFiveMin) &&
        Objects.equals(this.latestFifteenMin, timeSeriesDataModel.latestFifteenMin) &&
        Objects.equals(this.latestHourly, timeSeriesDataModel.latestHourly) &&
        Objects.equals(this.latestDaily, timeSeriesDataModel.latestDaily) &&
        Objects.equals(this.latestWeekly, timeSeriesDataModel.latestWeekly) &&
        Objects.equals(this.latestMonthly, timeSeriesDataModel.latestMonthly) &&
        Objects.equals(this.latestYearly, timeSeriesDataModel.latestYearly) &&
        Objects.equals(this.volume, timeSeriesDataModel.volume) &&
        Objects.equals(this.openInterest, timeSeriesDataModel.openInterest) &&
        Objects.equals(this.volatility, timeSeriesDataModel.volatility) &&
        Objects.equals(this.relativeStrengthIndex, timeSeriesDataModel.relativeStrengthIndex) &&
        Objects.equals(this.movingAverage50, timeSeriesDataModel.movingAverage50) &&
        Objects.equals(this.movingAverage200, timeSeriesDataModel.movingAverage200) &&
        Objects.equals(this.bollingerUpperBand, timeSeriesDataModel.bollingerUpperBand) &&
        Objects.equals(this.bollingerLowerBand, timeSeriesDataModel.bollingerLowerBand) &&
        Objects.equals(this.macdLine, timeSeriesDataModel.macdLine) &&
        Objects.equals(this.macdSignalLine, timeSeriesDataModel.macdSignalLine) &&
        Objects.equals(this.macdHistogram, timeSeriesDataModel.macdHistogram);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, timestamp, timeframe, ohlcv, latestFiveMin, latestFifteenMin, latestHourly, latestDaily, latestWeekly, latestMonthly, latestYearly, volume, openInterest, volatility, relativeStrengthIndex, movingAverage50, movingAverage200, bollingerUpperBand, bollingerLowerBand, macdLine, macdSignalLine, macdHistogram);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TimeSeriesDataModel {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    timeframe: ").append(toIndentedString(timeframe)).append("\n");
    sb.append("    ohlcv: ").append(toIndentedString(ohlcv)).append("\n");
    sb.append("    latestFiveMin: ").append(toIndentedString(latestFiveMin)).append("\n");
    sb.append("    latestFifteenMin: ").append(toIndentedString(latestFifteenMin)).append("\n");
    sb.append("    latestHourly: ").append(toIndentedString(latestHourly)).append("\n");
    sb.append("    latestDaily: ").append(toIndentedString(latestDaily)).append("\n");
    sb.append("    latestWeekly: ").append(toIndentedString(latestWeekly)).append("\n");
    sb.append("    latestMonthly: ").append(toIndentedString(latestMonthly)).append("\n");
    sb.append("    latestYearly: ").append(toIndentedString(latestYearly)).append("\n");
    sb.append("    volume: ").append(toIndentedString(volume)).append("\n");
    sb.append("    openInterest: ").append(toIndentedString(openInterest)).append("\n");
    sb.append("    volatility: ").append(toIndentedString(volatility)).append("\n");
    sb.append("    relativeStrengthIndex: ").append(toIndentedString(relativeStrengthIndex)).append("\n");
    sb.append("    movingAverage50: ").append(toIndentedString(movingAverage50)).append("\n");
    sb.append("    movingAverage200: ").append(toIndentedString(movingAverage200)).append("\n");
    sb.append("    bollingerUpperBand: ").append(toIndentedString(bollingerUpperBand)).append("\n");
    sb.append("    bollingerLowerBand: ").append(toIndentedString(bollingerLowerBand)).append("\n");
    sb.append("    macdLine: ").append(toIndentedString(macdLine)).append("\n");
    sb.append("    macdSignalLine: ").append(toIndentedString(macdSignalLine)).append("\n");
    sb.append("    macdHistogram: ").append(toIndentedString(macdHistogram)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `timestamp` to the URL query string
    if (getTimestamp() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stimestamp%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTimestamp()))));
    }

    // add `timeframe` to the URL query string
    if (getTimeframe() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stimeframe%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTimeframe()))));
    }

    // add `ohlcv` to the URL query string
    if (getOhlcv() != null) {
      joiner.add(getOhlcv().toUrlQueryString(prefix + "ohlcv" + suffix));
    }

    // add `latestFiveMin` to the URL query string
    if (getLatestFiveMin() != null) {
      joiner.add(getLatestFiveMin().toUrlQueryString(prefix + "latestFiveMin" + suffix));
    }

    // add `latestFifteenMin` to the URL query string
    if (getLatestFifteenMin() != null) {
      joiner.add(getLatestFifteenMin().toUrlQueryString(prefix + "latestFifteenMin" + suffix));
    }

    // add `latestHourly` to the URL query string
    if (getLatestHourly() != null) {
      joiner.add(getLatestHourly().toUrlQueryString(prefix + "latestHourly" + suffix));
    }

    // add `latestDaily` to the URL query string
    if (getLatestDaily() != null) {
      joiner.add(getLatestDaily().toUrlQueryString(prefix + "latestDaily" + suffix));
    }

    // add `latestWeekly` to the URL query string
    if (getLatestWeekly() != null) {
      joiner.add(getLatestWeekly().toUrlQueryString(prefix + "latestWeekly" + suffix));
    }

    // add `latestMonthly` to the URL query string
    if (getLatestMonthly() != null) {
      joiner.add(getLatestMonthly().toUrlQueryString(prefix + "latestMonthly" + suffix));
    }

    // add `latestYearly` to the URL query string
    if (getLatestYearly() != null) {
      joiner.add(getLatestYearly().toUrlQueryString(prefix + "latestYearly" + suffix));
    }

    // add `volume` to the URL query string
    if (getVolume() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%svolume%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getVolume()))));
    }

    // add `openInterest` to the URL query string
    if (getOpenInterest() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sopenInterest%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOpenInterest()))));
    }

    // add `volatility` to the URL query string
    if (getVolatility() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%svolatility%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getVolatility()))));
    }

    // add `relativeStrengthIndex` to the URL query string
    if (getRelativeStrengthIndex() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%srelativeStrengthIndex%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRelativeStrengthIndex()))));
    }

    // add `movingAverage50` to the URL query string
    if (getMovingAverage50() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smovingAverage50%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMovingAverage50()))));
    }

    // add `movingAverage200` to the URL query string
    if (getMovingAverage200() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smovingAverage200%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMovingAverage200()))));
    }

    // add `bollingerUpperBand` to the URL query string
    if (getBollingerUpperBand() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbollingerUpperBand%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBollingerUpperBand()))));
    }

    // add `bollingerLowerBand` to the URL query string
    if (getBollingerLowerBand() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbollingerLowerBand%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBollingerLowerBand()))));
    }

    // add `macdLine` to the URL query string
    if (getMacdLine() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smacdLine%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMacdLine()))));
    }

    // add `macdSignalLine` to the URL query string
    if (getMacdSignalLine() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smacdSignalLine%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMacdSignalLine()))));
    }

    // add `macdHistogram` to the URL query string
    if (getMacdHistogram() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smacdHistogram%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMacdHistogram()))));
    }

    return joiner.toString();
  }
}

