name: AM Analysis Service Publish

on:
  push:
    paths:
      - "services/am-analysis/**"
      - "libraries/**"
      - "domain/**"
      - "pom.xml"
  pull_request:
    paths:
      - "services/am-analysis/**"
      - "libraries/**"
      - "domain/**"
      - "pom.xml"

jobs:
  publish-analysis:
    name: Publish Analysis
    permissions:
      contents: read
      packages: write
    uses: AM-Portfolio/am-pipelines/.github/workflows/central-build-publish.yml@main
    with:
      language: "java"
      working_directory: "services/am-analysis"
      image_name: "am-analysis"
      build_context: "."
    secrets: inherit
