name: Gateway Publish

on:
  push:
    branches: ["main", "develop", "test/**", "feature/**", "hotfix/**", "fix/**"]
    paths:
      - 'services/am-gateway/**'
      - '.github/workflows/am-gateway.yml'
  pull_request:
    branches: ["main", "develop", "test/**", "feature/**", "hotfix/**", "fix/**"]
    paths:
      - 'services/am-gateway/**'
      - '.github/workflows/am-gateway.yml'
  workflow_dispatch:

jobs:
  publish:
    name: Publish Gateway
    permissions:
      contents: read
      packages: write
    uses: AM-Portfolio/am-pipelines/.github/workflows/central-build-publish.yml@main
    with:
      language: 'java'
      working_directory: 'services/am-gateway'
      image_name: 'am-gateway'
      build_context: '.'
      preprod_namespace: 'am-apps-preprod'
      prod_namespace: 'am-apps-prod'
      deploy_prod: false
    secrets: inherit
