/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.analysis.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.am.portfolio.client.analysis.model.AllocationItem;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.portfolio.client.analysis.invoker.ApiClient;
/**
 * AllocationResponse
 */
@JsonPropertyOrder({
  AllocationResponse.JSON_PROPERTY_PORTFOLIO_ID,
  AllocationResponse.JSON_PROPERTY_SECTORS,
  AllocationResponse.JSON_PROPERTY_ASSET_CLASSES,
  AllocationResponse.JSON_PROPERTY_MARKET_CAPS,
  AllocationResponse.JSON_PROPERTY_STOCKS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-15T18:03:19.826558600+05:30[Asia/Calcutta]", comments = "Generator version: 7.19.0")
public class AllocationResponse {
  public static final String JSON_PROPERTY_PORTFOLIO_ID = "portfolioId";
  @javax.annotation.Nullable
  private String portfolioId;

  public static final String JSON_PROPERTY_SECTORS = "sectors";
  @javax.annotation.Nullable
  private List<AllocationItem> sectors = new ArrayList<>();

  public static final String JSON_PROPERTY_ASSET_CLASSES = "assetClasses";
  @javax.annotation.Nullable
  private List<AllocationItem> assetClasses = new ArrayList<>();

  public static final String JSON_PROPERTY_MARKET_CAPS = "marketCaps";
  @javax.annotation.Nullable
  private List<AllocationItem> marketCaps = new ArrayList<>();

  public static final String JSON_PROPERTY_STOCKS = "stocks";
  @javax.annotation.Nullable
  private List<AllocationItem> stocks = new ArrayList<>();

  public AllocationResponse() { 
  }

  public AllocationResponse portfolioId(@javax.annotation.Nullable String portfolioId) {
    this.portfolioId = portfolioId;
    return this;
  }

  /**
   * Get portfolioId
   * @return portfolioId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PORTFOLIO_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPortfolioId() {
    return portfolioId;
  }


  @JsonProperty(value = JSON_PROPERTY_PORTFOLIO_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPortfolioId(@javax.annotation.Nullable String portfolioId) {
    this.portfolioId = portfolioId;
  }


  public AllocationResponse sectors(@javax.annotation.Nullable List<AllocationItem> sectors) {
    this.sectors = sectors;
    return this;
  }

  public AllocationResponse addSectorsItem(AllocationItem sectorsItem) {
    if (this.sectors == null) {
      this.sectors = new ArrayList<>();
    }
    this.sectors.add(sectorsItem);
    return this;
  }

  /**
   * Get sectors
   * @return sectors
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SECTORS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<AllocationItem> getSectors() {
    return sectors;
  }


  @JsonProperty(value = JSON_PROPERTY_SECTORS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSectors(@javax.annotation.Nullable List<AllocationItem> sectors) {
    this.sectors = sectors;
  }


  public AllocationResponse assetClasses(@javax.annotation.Nullable List<AllocationItem> assetClasses) {
    this.assetClasses = assetClasses;
    return this;
  }

  public AllocationResponse addAssetClassesItem(AllocationItem assetClassesItem) {
    if (this.assetClasses == null) {
      this.assetClasses = new ArrayList<>();
    }
    this.assetClasses.add(assetClassesItem);
    return this;
  }

  /**
   * Get assetClasses
   * @return assetClasses
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ASSET_CLASSES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<AllocationItem> getAssetClasses() {
    return assetClasses;
  }


  @JsonProperty(value = JSON_PROPERTY_ASSET_CLASSES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAssetClasses(@javax.annotation.Nullable List<AllocationItem> assetClasses) {
    this.assetClasses = assetClasses;
  }


  public AllocationResponse marketCaps(@javax.annotation.Nullable List<AllocationItem> marketCaps) {
    this.marketCaps = marketCaps;
    return this;
  }

  public AllocationResponse addMarketCapsItem(AllocationItem marketCapsItem) {
    if (this.marketCaps == null) {
      this.marketCaps = new ArrayList<>();
    }
    this.marketCaps.add(marketCapsItem);
    return this;
  }

  /**
   * Get marketCaps
   * @return marketCaps
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MARKET_CAPS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<AllocationItem> getMarketCaps() {
    return marketCaps;
  }


  @JsonProperty(value = JSON_PROPERTY_MARKET_CAPS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMarketCaps(@javax.annotation.Nullable List<AllocationItem> marketCaps) {
    this.marketCaps = marketCaps;
  }


  public AllocationResponse stocks(@javax.annotation.Nullable List<AllocationItem> stocks) {
    this.stocks = stocks;
    return this;
  }

  public AllocationResponse addStocksItem(AllocationItem stocksItem) {
    if (this.stocks == null) {
      this.stocks = new ArrayList<>();
    }
    this.stocks.add(stocksItem);
    return this;
  }

  /**
   * Get stocks
   * @return stocks
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STOCKS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<AllocationItem> getStocks() {
    return stocks;
  }


  @JsonProperty(value = JSON_PROPERTY_STOCKS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStocks(@javax.annotation.Nullable List<AllocationItem> stocks) {
    this.stocks = stocks;
  }


  /**
   * Return true if this AllocationResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AllocationResponse allocationResponse = (AllocationResponse) o;
    return Objects.equals(this.portfolioId, allocationResponse.portfolioId) &&
        Objects.equals(this.sectors, allocationResponse.sectors) &&
        Objects.equals(this.assetClasses, allocationResponse.assetClasses) &&
        Objects.equals(this.marketCaps, allocationResponse.marketCaps) &&
        Objects.equals(this.stocks, allocationResponse.stocks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(portfolioId, sectors, assetClasses, marketCaps, stocks);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AllocationResponse {\n");
    sb.append("    portfolioId: ").append(toIndentedString(portfolioId)).append("\n");
    sb.append("    sectors: ").append(toIndentedString(sectors)).append("\n");
    sb.append("    assetClasses: ").append(toIndentedString(assetClasses)).append("\n");
    sb.append("    marketCaps: ").append(toIndentedString(marketCaps)).append("\n");
    sb.append("    stocks: ").append(toIndentedString(stocks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `portfolioId` to the URL query string
    if (getPortfolioId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sportfolioId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPortfolioId()))));
    }

    // add `sectors` to the URL query string
    if (getSectors() != null) {
      for (int i = 0; i < getSectors().size(); i++) {
        if (getSectors().get(i) != null) {
          joiner.add(getSectors().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%ssectors%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `assetClasses` to the URL query string
    if (getAssetClasses() != null) {
      for (int i = 0; i < getAssetClasses().size(); i++) {
        if (getAssetClasses().get(i) != null) {
          joiner.add(getAssetClasses().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sassetClasses%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `marketCaps` to the URL query string
    if (getMarketCaps() != null) {
      for (int i = 0; i < getMarketCaps().size(); i++) {
        if (getMarketCaps().get(i) != null) {
          joiner.add(getMarketCaps().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%smarketCaps%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `stocks` to the URL query string
    if (getStocks() != null) {
      for (int i = 0; i < getStocks().size(); i++) {
        if (getStocks().get(i) != null) {
          joiner.add(getStocks().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sstocks%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

