/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.analysis.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.portfolio.client.analysis.invoker.ApiClient;
/**
 * AllocationHolding
 */
@JsonPropertyOrder({
  AllocationHolding.JSON_PROPERTY_SYMBOL,
  AllocationHolding.JSON_PROPERTY_NAME,
  AllocationHolding.JSON_PROPERTY_VALUE,
  AllocationHolding.JSON_PROPERTY_PERCENTAGE,
  AllocationHolding.JSON_PROPERTY_PORTFOLIO_PERCENTAGE,
  AllocationHolding.JSON_PROPERTY_DAY_CHANGE_PERCENTAGE,
  AllocationHolding.JSON_PROPERTY_DAY_CHANGE_AMOUNT,
  AllocationHolding.JSON_PROPERTY_TOTAL_CHANGE_PERCENTAGE,
  AllocationHolding.JSON_PROPERTY_TOTAL_CHANGE_AMOUNT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-15T18:03:19.826558600+05:30[Asia/Calcutta]", comments = "Generator version: 7.19.0")
public class AllocationHolding {
  public static final String JSON_PROPERTY_SYMBOL = "symbol";
  @javax.annotation.Nullable
  private String symbol;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_VALUE = "value";
  @javax.annotation.Nullable
  private BigDecimal value;

  public static final String JSON_PROPERTY_PERCENTAGE = "percentage";
  @javax.annotation.Nullable
  private Double percentage;

  public static final String JSON_PROPERTY_PORTFOLIO_PERCENTAGE = "portfolioPercentage";
  @javax.annotation.Nullable
  private Double portfolioPercentage;

  public static final String JSON_PROPERTY_DAY_CHANGE_PERCENTAGE = "dayChangePercentage";
  @javax.annotation.Nullable
  private Double dayChangePercentage;

  public static final String JSON_PROPERTY_DAY_CHANGE_AMOUNT = "dayChangeAmount";
  @javax.annotation.Nullable
  private BigDecimal dayChangeAmount;

  public static final String JSON_PROPERTY_TOTAL_CHANGE_PERCENTAGE = "totalChangePercentage";
  @javax.annotation.Nullable
  private Double totalChangePercentage;

  public static final String JSON_PROPERTY_TOTAL_CHANGE_AMOUNT = "totalChangeAmount";
  @javax.annotation.Nullable
  private BigDecimal totalChangeAmount;

  public AllocationHolding() { 
  }

  public AllocationHolding symbol(@javax.annotation.Nullable String symbol) {
    this.symbol = symbol;
    return this;
  }

  /**
   * Get symbol
   * @return symbol
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SYMBOL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSymbol() {
    return symbol;
  }


  @JsonProperty(value = JSON_PROPERTY_SYMBOL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSymbol(@javax.annotation.Nullable String symbol) {
    this.symbol = symbol;
  }


  public AllocationHolding name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public AllocationHolding value(@javax.annotation.Nullable BigDecimal value) {
    this.value = value;
    return this;
  }

  /**
   * Get value
   * @return value
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getValue() {
    return value;
  }


  @JsonProperty(value = JSON_PROPERTY_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValue(@javax.annotation.Nullable BigDecimal value) {
    this.value = value;
  }


  public AllocationHolding percentage(@javax.annotation.Nullable Double percentage) {
    this.percentage = percentage;
    return this;
  }

  /**
   * Get percentage
   * @return percentage
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PERCENTAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getPercentage() {
    return percentage;
  }


  @JsonProperty(value = JSON_PROPERTY_PERCENTAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPercentage(@javax.annotation.Nullable Double percentage) {
    this.percentage = percentage;
  }


  public AllocationHolding portfolioPercentage(@javax.annotation.Nullable Double portfolioPercentage) {
    this.portfolioPercentage = portfolioPercentage;
    return this;
  }

  /**
   * Get portfolioPercentage
   * @return portfolioPercentage
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PORTFOLIO_PERCENTAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getPortfolioPercentage() {
    return portfolioPercentage;
  }


  @JsonProperty(value = JSON_PROPERTY_PORTFOLIO_PERCENTAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPortfolioPercentage(@javax.annotation.Nullable Double portfolioPercentage) {
    this.portfolioPercentage = portfolioPercentage;
  }


  public AllocationHolding dayChangePercentage(@javax.annotation.Nullable Double dayChangePercentage) {
    this.dayChangePercentage = dayChangePercentage;
    return this;
  }

  /**
   * Get dayChangePercentage
   * @return dayChangePercentage
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DAY_CHANGE_PERCENTAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getDayChangePercentage() {
    return dayChangePercentage;
  }


  @JsonProperty(value = JSON_PROPERTY_DAY_CHANGE_PERCENTAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDayChangePercentage(@javax.annotation.Nullable Double dayChangePercentage) {
    this.dayChangePercentage = dayChangePercentage;
  }


  public AllocationHolding dayChangeAmount(@javax.annotation.Nullable BigDecimal dayChangeAmount) {
    this.dayChangeAmount = dayChangeAmount;
    return this;
  }

  /**
   * Get dayChangeAmount
   * @return dayChangeAmount
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DAY_CHANGE_AMOUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getDayChangeAmount() {
    return dayChangeAmount;
  }


  @JsonProperty(value = JSON_PROPERTY_DAY_CHANGE_AMOUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDayChangeAmount(@javax.annotation.Nullable BigDecimal dayChangeAmount) {
    this.dayChangeAmount = dayChangeAmount;
  }


  public AllocationHolding totalChangePercentage(@javax.annotation.Nullable Double totalChangePercentage) {
    this.totalChangePercentage = totalChangePercentage;
    return this;
  }

  /**
   * Get totalChangePercentage
   * @return totalChangePercentage
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOTAL_CHANGE_PERCENTAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getTotalChangePercentage() {
    return totalChangePercentage;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL_CHANGE_PERCENTAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalChangePercentage(@javax.annotation.Nullable Double totalChangePercentage) {
    this.totalChangePercentage = totalChangePercentage;
  }


  public AllocationHolding totalChangeAmount(@javax.annotation.Nullable BigDecimal totalChangeAmount) {
    this.totalChangeAmount = totalChangeAmount;
    return this;
  }

  /**
   * Get totalChangeAmount
   * @return totalChangeAmount
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOTAL_CHANGE_AMOUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getTotalChangeAmount() {
    return totalChangeAmount;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL_CHANGE_AMOUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalChangeAmount(@javax.annotation.Nullable BigDecimal totalChangeAmount) {
    this.totalChangeAmount = totalChangeAmount;
  }


  /**
   * Return true if this AllocationHolding object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AllocationHolding allocationHolding = (AllocationHolding) o;
    return Objects.equals(this.symbol, allocationHolding.symbol) &&
        Objects.equals(this.name, allocationHolding.name) &&
        Objects.equals(this.value, allocationHolding.value) &&
        Objects.equals(this.percentage, allocationHolding.percentage) &&
        Objects.equals(this.portfolioPercentage, allocationHolding.portfolioPercentage) &&
        Objects.equals(this.dayChangePercentage, allocationHolding.dayChangePercentage) &&
        Objects.equals(this.dayChangeAmount, allocationHolding.dayChangeAmount) &&
        Objects.equals(this.totalChangePercentage, allocationHolding.totalChangePercentage) &&
        Objects.equals(this.totalChangeAmount, allocationHolding.totalChangeAmount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(symbol, name, value, percentage, portfolioPercentage, dayChangePercentage, dayChangeAmount, totalChangePercentage, totalChangeAmount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AllocationHolding {\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    percentage: ").append(toIndentedString(percentage)).append("\n");
    sb.append("    portfolioPercentage: ").append(toIndentedString(portfolioPercentage)).append("\n");
    sb.append("    dayChangePercentage: ").append(toIndentedString(dayChangePercentage)).append("\n");
    sb.append("    dayChangeAmount: ").append(toIndentedString(dayChangeAmount)).append("\n");
    sb.append("    totalChangePercentage: ").append(toIndentedString(totalChangePercentage)).append("\n");
    sb.append("    totalChangeAmount: ").append(toIndentedString(totalChangeAmount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `symbol` to the URL query string
    if (getSymbol() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssymbol%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSymbol()))));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `value` to the URL query string
    if (getValue() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%svalue%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getValue()))));
    }

    // add `percentage` to the URL query string
    if (getPercentage() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spercentage%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPercentage()))));
    }

    // add `portfolioPercentage` to the URL query string
    if (getPortfolioPercentage() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sportfolioPercentage%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPortfolioPercentage()))));
    }

    // add `dayChangePercentage` to the URL query string
    if (getDayChangePercentage() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdayChangePercentage%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDayChangePercentage()))));
    }

    // add `dayChangeAmount` to the URL query string
    if (getDayChangeAmount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdayChangeAmount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDayChangeAmount()))));
    }

    // add `totalChangePercentage` to the URL query string
    if (getTotalChangePercentage() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stotalChangePercentage%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTotalChangePercentage()))));
    }

    // add `totalChangeAmount` to the URL query string
    if (getTotalChangeAmount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stotalChangeAmount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTotalChangeAmount()))));
    }

    return joiner.toString();
  }
}

