/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.analysis.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.am.portfolio.client.analysis.model.DataPoint;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.portfolio.client.analysis.invoker.ApiClient;
/**
 * PerformanceResponse
 */
@JsonPropertyOrder({
  PerformanceResponse.JSON_PROPERTY_PORTFOLIO_ID,
  PerformanceResponse.JSON_PROPERTY_TIME_FRAME,
  PerformanceResponse.JSON_PROPERTY_TOTAL_RETURN_PERCENTAGE,
  PerformanceResponse.JSON_PROPERTY_TOTAL_RETURN_VALUE,
  PerformanceResponse.JSON_PROPERTY_CHART_DATA,
  PerformanceResponse.JSON_PROPERTY_ERROR_MESSAGE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-15T18:03:19.826558600+05:30[Asia/Calcutta]", comments = "Generator version: 7.19.0")
public class PerformanceResponse {
  public static final String JSON_PROPERTY_PORTFOLIO_ID = "portfolioId";
  @javax.annotation.Nullable
  private String portfolioId;

  public static final String JSON_PROPERTY_TIME_FRAME = "timeFrame";
  @javax.annotation.Nullable
  private String timeFrame;

  public static final String JSON_PROPERTY_TOTAL_RETURN_PERCENTAGE = "totalReturnPercentage";
  @javax.annotation.Nullable
  private Double totalReturnPercentage;

  public static final String JSON_PROPERTY_TOTAL_RETURN_VALUE = "totalReturnValue";
  @javax.annotation.Nullable
  private BigDecimal totalReturnValue;

  public static final String JSON_PROPERTY_CHART_DATA = "chartData";
  @javax.annotation.Nullable
  private List<DataPoint> chartData = new ArrayList<>();

  public static final String JSON_PROPERTY_ERROR_MESSAGE = "errorMessage";
  @javax.annotation.Nullable
  private String errorMessage;

  public PerformanceResponse() { 
  }

  public PerformanceResponse portfolioId(@javax.annotation.Nullable String portfolioId) {
    this.portfolioId = portfolioId;
    return this;
  }

  /**
   * Get portfolioId
   * @return portfolioId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PORTFOLIO_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPortfolioId() {
    return portfolioId;
  }


  @JsonProperty(value = JSON_PROPERTY_PORTFOLIO_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPortfolioId(@javax.annotation.Nullable String portfolioId) {
    this.portfolioId = portfolioId;
  }


  public PerformanceResponse timeFrame(@javax.annotation.Nullable String timeFrame) {
    this.timeFrame = timeFrame;
    return this;
  }

  /**
   * Get timeFrame
   * @return timeFrame
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIME_FRAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTimeFrame() {
    return timeFrame;
  }


  @JsonProperty(value = JSON_PROPERTY_TIME_FRAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimeFrame(@javax.annotation.Nullable String timeFrame) {
    this.timeFrame = timeFrame;
  }


  public PerformanceResponse totalReturnPercentage(@javax.annotation.Nullable Double totalReturnPercentage) {
    this.totalReturnPercentage = totalReturnPercentage;
    return this;
  }

  /**
   * Get totalReturnPercentage
   * @return totalReturnPercentage
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOTAL_RETURN_PERCENTAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getTotalReturnPercentage() {
    return totalReturnPercentage;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL_RETURN_PERCENTAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalReturnPercentage(@javax.annotation.Nullable Double totalReturnPercentage) {
    this.totalReturnPercentage = totalReturnPercentage;
  }


  public PerformanceResponse totalReturnValue(@javax.annotation.Nullable BigDecimal totalReturnValue) {
    this.totalReturnValue = totalReturnValue;
    return this;
  }

  /**
   * Get totalReturnValue
   * @return totalReturnValue
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOTAL_RETURN_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getTotalReturnValue() {
    return totalReturnValue;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL_RETURN_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalReturnValue(@javax.annotation.Nullable BigDecimal totalReturnValue) {
    this.totalReturnValue = totalReturnValue;
  }


  public PerformanceResponse chartData(@javax.annotation.Nullable List<DataPoint> chartData) {
    this.chartData = chartData;
    return this;
  }

  public PerformanceResponse addChartDataItem(DataPoint chartDataItem) {
    if (this.chartData == null) {
      this.chartData = new ArrayList<>();
    }
    this.chartData.add(chartDataItem);
    return this;
  }

  /**
   * Get chartData
   * @return chartData
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CHART_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<DataPoint> getChartData() {
    return chartData;
  }


  @JsonProperty(value = JSON_PROPERTY_CHART_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChartData(@javax.annotation.Nullable List<DataPoint> chartData) {
    this.chartData = chartData;
  }


  public PerformanceResponse errorMessage(@javax.annotation.Nullable String errorMessage) {
    this.errorMessage = errorMessage;
    return this;
  }

  /**
   * Get errorMessage
   * @return errorMessage
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ERROR_MESSAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getErrorMessage() {
    return errorMessage;
  }


  @JsonProperty(value = JSON_PROPERTY_ERROR_MESSAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setErrorMessage(@javax.annotation.Nullable String errorMessage) {
    this.errorMessage = errorMessage;
  }


  /**
   * Return true if this PerformanceResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PerformanceResponse performanceResponse = (PerformanceResponse) o;
    return Objects.equals(this.portfolioId, performanceResponse.portfolioId) &&
        Objects.equals(this.timeFrame, performanceResponse.timeFrame) &&
        Objects.equals(this.totalReturnPercentage, performanceResponse.totalReturnPercentage) &&
        Objects.equals(this.totalReturnValue, performanceResponse.totalReturnValue) &&
        Objects.equals(this.chartData, performanceResponse.chartData) &&
        Objects.equals(this.errorMessage, performanceResponse.errorMessage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(portfolioId, timeFrame, totalReturnPercentage, totalReturnValue, chartData, errorMessage);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PerformanceResponse {\n");
    sb.append("    portfolioId: ").append(toIndentedString(portfolioId)).append("\n");
    sb.append("    timeFrame: ").append(toIndentedString(timeFrame)).append("\n");
    sb.append("    totalReturnPercentage: ").append(toIndentedString(totalReturnPercentage)).append("\n");
    sb.append("    totalReturnValue: ").append(toIndentedString(totalReturnValue)).append("\n");
    sb.append("    chartData: ").append(toIndentedString(chartData)).append("\n");
    sb.append("    errorMessage: ").append(toIndentedString(errorMessage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `portfolioId` to the URL query string
    if (getPortfolioId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sportfolioId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPortfolioId()))));
    }

    // add `timeFrame` to the URL query string
    if (getTimeFrame() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stimeFrame%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTimeFrame()))));
    }

    // add `totalReturnPercentage` to the URL query string
    if (getTotalReturnPercentage() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stotalReturnPercentage%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTotalReturnPercentage()))));
    }

    // add `totalReturnValue` to the URL query string
    if (getTotalReturnValue() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stotalReturnValue%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTotalReturnValue()))));
    }

    // add `chartData` to the URL query string
    if (getChartData() != null) {
      for (int i = 0; i < getChartData().size(); i++) {
        if (getChartData().get(i) != null) {
          joiner.add(getChartData().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%schartData%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `errorMessage` to the URL query string
    if (getErrorMessage() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%serrorMessage%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getErrorMessage()))));
    }

    return joiner.toString();
  }
}

