/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.analysis.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.am.portfolio.client.analysis.model.MoverItem;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.portfolio.client.analysis.invoker.ApiClient;
/**
 * TopMoversResponse
 */
@JsonPropertyOrder({
  TopMoversResponse.JSON_PROPERTY_GAINERS,
  TopMoversResponse.JSON_PROPERTY_LOSERS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-15T18:03:19.826558600+05:30[Asia/Calcutta]", comments = "Generator version: 7.19.0")
public class TopMoversResponse {
  public static final String JSON_PROPERTY_GAINERS = "gainers";
  @javax.annotation.Nullable
  private List<MoverItem> gainers = new ArrayList<>();

  public static final String JSON_PROPERTY_LOSERS = "losers";
  @javax.annotation.Nullable
  private List<MoverItem> losers = new ArrayList<>();

  public TopMoversResponse() { 
  }

  public TopMoversResponse gainers(@javax.annotation.Nullable List<MoverItem> gainers) {
    this.gainers = gainers;
    return this;
  }

  public TopMoversResponse addGainersItem(MoverItem gainersItem) {
    if (this.gainers == null) {
      this.gainers = new ArrayList<>();
    }
    this.gainers.add(gainersItem);
    return this;
  }

  /**
   * Get gainers
   * @return gainers
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_GAINERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<MoverItem> getGainers() {
    return gainers;
  }


  @JsonProperty(value = JSON_PROPERTY_GAINERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGainers(@javax.annotation.Nullable List<MoverItem> gainers) {
    this.gainers = gainers;
  }


  public TopMoversResponse losers(@javax.annotation.Nullable List<MoverItem> losers) {
    this.losers = losers;
    return this;
  }

  public TopMoversResponse addLosersItem(MoverItem losersItem) {
    if (this.losers == null) {
      this.losers = new ArrayList<>();
    }
    this.losers.add(losersItem);
    return this;
  }

  /**
   * Get losers
   * @return losers
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LOSERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<MoverItem> getLosers() {
    return losers;
  }


  @JsonProperty(value = JSON_PROPERTY_LOSERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLosers(@javax.annotation.Nullable List<MoverItem> losers) {
    this.losers = losers;
  }


  /**
   * Return true if this TopMoversResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TopMoversResponse topMoversResponse = (TopMoversResponse) o;
    return Objects.equals(this.gainers, topMoversResponse.gainers) &&
        Objects.equals(this.losers, topMoversResponse.losers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(gainers, losers);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TopMoversResponse {\n");
    sb.append("    gainers: ").append(toIndentedString(gainers)).append("\n");
    sb.append("    losers: ").append(toIndentedString(losers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `gainers` to the URL query string
    if (getGainers() != null) {
      for (int i = 0; i < getGainers().size(); i++) {
        if (getGainers().get(i) != null) {
          joiner.add(getGainers().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sgainers%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `losers` to the URL query string
    if (getLosers() != null) {
      for (int i = 0; i < getLosers().size(); i++) {
        if (getLosers().get(i) != null) {
          joiner.add(getLosers().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%slosers%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

